Repository farcasterxyz/hub-monorepo, pull requests merged in 2022-12, with the labels that each got.

#258 feat: grpc event service and store event handler
  src/network/rpc/flatbuffers/client.ts
  src/network/rpc/flatbuffers/eventService.test.ts
  src/network/rpc/flatbuffers/eventService.ts
  src/network/rpc/flatbuffers/server.ts
  src/storage/engine/flatbuffers/index.test.ts
  src/storage/engine/flatbuffers/index.ts
  src/storage/sets/flatbuffers/castStore.test.ts
  src/storage/sets/flatbuffers/castStore.ts
  src/storage/sets/flatbuffers/followStore.test.ts
  src/storage/sets/flatbuffers/followStore.ts
  src/storage/sets/flatbuffers/reactionStore.test.ts
  src/storage/sets/flatbuffers/reactionStore.ts
  src/storage/sets/flatbuffers/signerStore.test.ts
  src/storage/sets/flatbuffers/signerStore.ts
  src/storage/sets/flatbuffers/storeEventHandler.ts
  src/storage/sets/flatbuffers/userDataStore.test.ts
  src/storage/sets/flatbuffers/userDataStore.ts
  src/storage/sets/flatbuffers/verificationStore.test.ts
  src/storage/sets/flatbuffers/verificationStore.ts
  src/utils/generated/farcaster/event-response.ts
  src/utils/generated/farcaster/event-type.ts
  src/utils/generated/farcaster/subscribe-request.ts
  src/utils/generated/rpc_generated.ts
  src/utils/schemas/rpc.fbs
  yarn.lock
Labels: feat

#259 feat: handle signer revocation and emit revokeMessage events
  src/storage/engine/flatbuffers/index.test.ts
  src/storage/engine/flatbuffers/index.ts
  src/storage/flatbuffers/contractEventModel.ts
  src/storage/flatbuffers/messageModel.ts
  src/storage/sets/flatbuffers/castStore.ts
  src/storage/sets/flatbuffers/followStore.ts
  src/storage/sets/flatbuffers/reactionStore.ts
  src/storage/sets/flatbuffers/signerStore.test.ts
  src/storage/sets/flatbuffers/signerStore.ts
  src/storage/sets/flatbuffers/userDataStore.ts
  src/storage/sets/flatbuffers/verificationStore.ts
  src/test/factories.ts
  src/test/factories/flatbuffer.ts
  src/utils/generated/farcaster/contract-event-type.ts
  src/utils/generated/farcaster/contract-event.ts
  src/utils/schemas/contract_event.fbs
Labels: feat

#254 documentation: Add space to README.md
  README.md
Labels: docs

#265 feat: prune messages in CastStore
  src/storage/flatbuffers/messageModel.ts
  src/storage/sets/flatbuffers/castStore.test.ts
  src/storage/sets/flatbuffers/castStore.ts
Labels: feat

#271 feat: follow store pruning
  src/storage/flatbuffers/messageModel.test.ts
  src/storage/flatbuffers/messageModel.ts
  src/storage/flatbuffers/types.ts
  src/storage/sets/flatbuffers/castStore.ts
  src/storage/sets/flatbuffers/followStore.test.ts
  src/storage/sets/flatbuffers/followStore.ts
  src/utils/generated/message_generated.ts
  src/utils/schemas/message.fbs
Labels: feat

#273 feat: add pruneMessages method to ReactionStore
  src/storage/sets/flatbuffers/followStore.test.ts
  src/storage/sets/flatbuffers/followStore.ts
  src/storage/sets/flatbuffers/reactionStore.test.ts
  src/storage/sets/flatbuffers/reactionStore.ts
Labels: feat

#253 fix(RPCServer): use result value instead of result in multiaddr str
  src/network/rpc/server.ts
Labels: bug

#261 chore: enable noUncheckedIndexedAccess
  src/hub.ts
  src/network/p2p/node.test.ts
  src/network/sync/syncEngine.test.ts
  src/network/sync/trieNode.test.ts
  src/network/sync/trieNode.ts
  src/storage/flatbuffers/utils.ts
  src/storage/provider/idRegistryProvider.ts
  src/test/e2e/differentialSync.test.ts
  src/test/e2e/hub.test.ts
  src/test/perf/bench.ts
  src/test/perf/setup.ts
  src/test/perf/utils.ts
  src/urls/castUrl.ts
  src/urls/chainAccountUrl.ts
  src/urls/chainUrl.ts
  src/urls/userUrl.ts
  src/urls/utils.ts
  tsconfig.json
Labels: chore

#293 chore: upgrade packages (dec 16, 2022)
  package.json
  yarn.lock
Labels: chore

#294 chore: remove set tests since sets will be deprecated
  src/storage/sets/castSet.test.ts
  src/storage/sets/followSet.test.ts
  src/storage/sets/reactionSet.test.ts
  src/storage/sets/signerSet.test.ts
  src/storage/sets/verificationSet.test.ts
Labels: chore

#298 perf: replace all calls to Wallet.createRandom() to speed up tests
  src/network/rpc/flatbuffers/castService.test.ts
  src/network/rpc/flatbuffers/eventService.test.ts
  src/network/rpc/flatbuffers/followService.test.ts
  src/network/rpc/flatbuffers/reactionService.test.ts
  src/network/rpc/flatbuffers/signerService.test.ts
  src/network/rpc/flatbuffers/submitService.test.ts
  src/network/rpc/flatbuffers/syncService.test.ts
  src/network/rpc/flatbuffers/userDataService.test.ts
  src/network/rpc/flatbuffers/verificationService.test.ts
  src/storage/engine/engine.verification.test.ts
  src/storage/engine/flatbuffers/index.test.ts
  src/storage/flatbuffers/validations.test.ts
  src/storage/sets/flatbuffers/userDataStore.test.ts
  src/test/factories/flatbuffer.ts
  src/utils/eip712.test.ts
Labels: chore

#299 fix: clean up contract event handlers when stopping hub
  src/hub.ts
  src/storage/engine/flatbuffers/providers/ethEventsProvider.ts
  src/test/e2e/hub.test.ts
Labels: bug

#300 perf: speed up gossip node tests
  src/network/p2p/node.test.ts
Labels: chore

#301 perf: shard tests and run them as a matrix in CI
  .github/workflows/ci.yml
  codecov.yml
  src/network/p2p/node.test.ts
Labels: chore

#305 docs: README for starting the Hub correctly
  README.md
  src/cli.ts
Labels: docs

#310 refactor: update logging for engine and hub
  src/flatbuffers/hub.ts
  src/network/rpc/flatbuffers/server.ts
  src/network/rpc/flatbuffers/submitService.test.ts
  src/storage/engine/flatbuffers/index.test.ts
  src/storage/engine/flatbuffers/index.ts
  src/storage/engine/flatbuffers/providers/ethEventsProvider.ts
  src/storage/flatbuffers/idRegistryEventModel.test.ts
  src/storage/flatbuffers/idRegistryEventModel.ts
  src/storage/flatbuffers/messageModel.test.ts
  src/storage/flatbuffers/messageModel.ts
  src/storage/flatbuffers/nameRegistryEventModel.test.ts
  src/storage/flatbuffers/nameRegistryEventModel.ts
  src/storage/flatbuffers/types.ts
  src/utils/logger.ts
Labels: chore

#320 refactor: submit all messages and on-chain events through Hub
  src/eth/abis.ts
  src/eth/ethEventsProvider.test.ts
  src/eth/ethEventsProvider.ts
  src/flatbufferHub.ts
  src/flatbuffers/models/types.ts
  src/hub.ts
  src/rpc/client/index.ts
  src/rpc/server/index.ts
  src/rpc/server/serviceImplementations/submitImplementation.ts
  src/rpc/serviceDefinitions/submitDefinition.ts
  src/rpc/test/ampService.test.ts
  src/rpc/test/castService.test.ts
  src/rpc/test/eventService.test.ts
  src/rpc/test/reactionService.test.ts
  src/rpc/test/signerService.test.ts
  src/rpc/test/submitService.test.ts
  src/rpc/test/syncService.test.ts
  src/rpc/test/userDataService.test.ts
  src/rpc/test/verificationService.test.ts
  src/storage/engine/flatbuffers/index.ts
  src/test/mocks.ts
Labels: chore

#323 chore: add fid to unknown user error for debugging
  src/flatbuffers/utils/bytes.ts
  src/rpc/test/submitService.test.ts
  src/storage/engine/index.test.ts
  src/storage/engine/index.ts
Labels: chore

#324 fix: use little-endian conversion instead of big endian
  src/flatbuffers/utils/bytes.ts
Labels: bug

#326 fix: numberToBytes method and validate fid is not padded
  src/flatbuffers/factories/flatbuffer.ts
  src/flatbuffers/models/validations.test.ts
  src/flatbuffers/models/validations.ts
  src/flatbuffers/utils/bytes.test.ts
  src/flatbuffers/utils/bytes.ts
Labels: chore

#327 refactor: move flatbuffer factories
  src/eth/ethEventsProvider.test.ts
  src/flatbuffers/factories.test.ts
  src/flatbuffers/factories.ts
  src/flatbuffers/models/idRegistryEventModel.test.ts
  src/flatbuffers/models/messageModel.test.ts
  src/flatbuffers/models/nameRegistryEventModel.test.ts
  src/flatbuffers/models/validations.test.ts
  src/flatbuffers/utils/eip712.test.ts
  src/network/p2p/node.test.ts
  src/rpc/test/ampService.test.ts
  src/rpc/test/castService.test.ts
  src/rpc/test/eventService.test.ts
  src/rpc/test/reactionService.test.ts
  src/rpc/test/signerService.test.ts
  src/rpc/test/submitService.test.ts
  src/rpc/test/syncService.test.ts
  src/rpc/test/userDataService.test.ts
  src/rpc/test/verificationService.test.ts
  src/storage/engine/index.test.ts
  src/storage/stores/ampStore.test.ts
  src/storage/stores/castStore.test.ts
  src/storage/stores/reactionStore.test.ts
  src/storage/stores/signerStore.test.ts
  src/storage/stores/userDataStore.test.ts
  src/storage/stores/verificationStore.test.ts
Labels: chore

#328 chore: upgrade minor + patch versions of libp2p
  src/network/p2p/node.ts
  yarn.lock
Labels: chore

#332 chore: configure no-unused-var to ignore '^_' args
  .eslintrc.cjs
  src/network/p2p/connectionFilter.test.ts
Labels: chore

#331 feat: add RevokeSignerJob class and queue signer revocation from hub
  jest.config.ts
  package.json
  src/flatbuffers/factories.ts
  src/flatbuffers/generated/job_generated.ts
  src/flatbuffers/models/idRegistryEventModel.ts
  src/flatbuffers/models/types.ts
  src/flatbuffers/schemas/job.fbs
  src/flatbuffers/utils/bytes.test.ts
  src/flatbuffers/utils/bytes.ts
  src/hub.ts
  src/storage/engine/seed.ts
  src/storage/jobs/revokeSignerJob.test.ts
  src/storage/jobs/revokeSignerJob.ts
  src/storage/stores/signerStore.ts
  src/utils/logger.ts
  yarn.lock
Labels: feat

#339 refactor: update gRPC EventResponse to use bytes directly
  src/flatbuffers/generated/rpc_generated.ts
  src/flatbuffers/schemas/rpc.fbs
  src/rpc/client/index.ts
  src/rpc/server/serviceImplementations/eventImplementation.ts
  src/rpc/test/ampService.test.ts
  src/rpc/test/castService.test.ts
  src/rpc/test/eventService.test.ts
  src/rpc/test/reactionService.test.ts
  src/rpc/test/signerService.test.ts
  src/rpc/test/syncService.test.ts
  src/rpc/test/userDataService.test.ts
  src/rpc/test/verificationService.test.ts
Labels: chore
