Repository farcasterxyz/hub-monorepo, pull requests merged in 2022-11, with the labels that each got.

#193 feat: flatbuffers signer set
  src/storage/flatbuffers/contractEventModel.test.ts
  src/storage/flatbuffers/contractEventModel.ts
  src/storage/flatbuffers/model.ts
  src/storage/flatbuffers/typeguards.ts
  src/storage/flatbuffers/types.ts
  src/storage/sets/flatbuffers/signerSet.test.ts
  src/storage/sets/flatbuffers/signerSet.ts
  src/storage/sets/flatbuffers/verificationSet.test.ts
  src/test/factories/flatbuffer.test.ts
  src/test/factories/flatbuffer.ts
  src/utils/eip712.test.ts
  src/utils/eip712.ts
  src/utils/generated/contract_event_generated.ts
  src/utils/generated/farcaster/contract-event-type.ts
  src/utils/generated/farcaster/contract-event.ts
  src/utils/generated/farcaster/message-body.ts
  src/utils/generated/farcaster/message-data.ts
  src/utils/generated/farcaster/message.ts
  src/utils/generated/farcaster/signer-body.ts
  src/utils/generated/message_generated.ts
  src/utils/schemas/contract_event.fbs
  src/utils/schemas/message.fbs
  src/utils/verification.test.ts
  src/utils/verification.ts
Labels: feat

#194 chore: disable noUnusedLocals in tsconfig
  tsconfig.json
Labels: chore

#190 feat: add reaction set
  src/storage/flatbuffers/contractEventModel.ts
  src/storage/flatbuffers/messageModel.test.ts
  src/storage/flatbuffers/messageModel.ts
  src/storage/flatbuffers/typeguards.ts
  src/storage/flatbuffers/types.ts
  src/storage/sets/flatbuffers/castSet.test.ts
  src/storage/sets/flatbuffers/castSet.ts
  src/storage/sets/flatbuffers/followSet.test.ts
  src/storage/sets/flatbuffers/followSet.ts
  src/storage/sets/flatbuffers/reactionSet.test.ts
  src/storage/sets/flatbuffers/reactionSet.ts
  src/storage/sets/flatbuffers/signerSet.test.ts
  src/storage/sets/flatbuffers/signerSet.ts
  src/storage/sets/flatbuffers/verificationSet.test.ts
  src/storage/sets/flatbuffers/verificationSet.ts
  src/test/factories/flatbuffer.ts
Labels: feat

#196 refactor: rename timestampHash to tsHash
  src/storage/flatbuffers/messageModel.test.ts
  src/storage/flatbuffers/messageModel.ts
  src/storage/sets/flatbuffers/castSet.test.ts
  src/storage/sets/flatbuffers/castSet.ts
  src/storage/sets/flatbuffers/followSet.test.ts
  src/storage/sets/flatbuffers/followSet.ts
  src/storage/sets/flatbuffers/reactionSet.test.ts
  src/storage/sets/flatbuffers/reactionSet.ts
  src/storage/sets/flatbuffers/signerSet.test.ts
  src/storage/sets/flatbuffers/signerSet.ts
  src/storage/sets/flatbuffers/verificationSet.test.ts
  src/storage/sets/flatbuffers/verificationSet.ts
  src/test/factories/flatbuffer.ts
Labels: chore

#197 refactor(CastSet): rename hash to tsHash
  src/storage/sets/flatbuffers/castSet.ts
Labels: chore

#198 fix: reaction merge should use lww-rw-hash comparisons to avoid unexpected user behavior
  src/storage/sets/flatbuffers/reactionSet.test.ts
  src/storage/sets/flatbuffers/reactionSet.ts
Labels: bug

#200 refactor(flatbuffers): rename hash to tsHash, targetTsHash for clarity
  CONTRIBUTING.md
  src/storage/sets/flatbuffers/castSet.test.ts
  src/storage/sets/flatbuffers/castSet.ts
  src/storage/sets/flatbuffers/followSet.test.ts
  src/storage/sets/flatbuffers/reactionStore.test.ts
  src/storage/sets/flatbuffers/reactionStore.ts
  src/test/factories/flatbuffer.test.ts
  src/test/factories/flatbuffer.ts
  src/utils/generated/farcaster/cast-add-body.ts
  src/utils/generated/farcaster/cast-id.ts
  src/utils/generated/farcaster/cast-remove-body.ts
  src/utils/generated/farcaster/follow-body.ts
  src/utils/generated/farcaster/reaction-body.ts
  src/utils/generated/farcaster/user-id.ts
  src/utils/generated/message_generated.ts
  src/utils/schemas/message.fbs
Labels: chore

#201 refactor(sets): rename flatbuffer sets to stores
  src/storage/db/cast.ts
  src/storage/db/follow.ts
  src/storage/db/signer.ts
  src/storage/db/verification.ts
  src/storage/sets/flatbuffers/castStore.test.ts
  src/storage/sets/flatbuffers/castStore.ts
  src/storage/sets/flatbuffers/followStore.test.ts
  src/storage/sets/flatbuffers/followStore.ts
  src/storage/sets/flatbuffers/signerStore.test.ts
  src/storage/sets/flatbuffers/signerStore.ts
  src/storage/sets/flatbuffers/verificationStore.test.ts
  src/storage/sets/flatbuffers/verificationStore.ts
Labels: chore

#195 feat: flatbuffers userdataset
  src/storage/flatbuffers/messageModel.ts
  src/storage/flatbuffers/typeguards.ts
  src/storage/flatbuffers/types.ts
  src/storage/sets/flatbuffers/userDataSet.test.ts
  src/storage/sets/flatbuffers/userDataSet.ts
  src/test/factories/flatbuffer.ts
  src/utils/generated/farcaster/message-body.ts
  src/utils/generated/farcaster/message-data.ts
  src/utils/generated/farcaster/message-type.ts
  src/utils/generated/farcaster/user-data-body.ts
  src/utils/generated/farcaster/user-data-type.ts
  src/utils/generated/message_generated.ts
  src/utils/schemas/message.fbs
Labels: feat

#204 fix(libp2p): add debug logs
  src/network/p2p/connectionFilter.ts
Labels: chore

#205 fix(benchmark): improve the bench client's throughput
  src/hub.ts
  src/network/rpc/client.ts
  src/network/sync/syncEngine.ts
  src/storage/engine/index.ts
  src/test/perf/scenario.ts
  src/test/perf/utils.ts
Labels: bug

#206 chore: Add test coverage for batched submissions
  src/network/rpc/rpc.test.ts
  src/test/perf/scenario.ts
  src/test/perf/utils.ts
Labels: chore

#208 chore: do not fail coverage if patch is below target
  codecov.yml
Labels: chore

#209 feat: flatbuffers engine
  src/storage/engine/flatbuffers/index.test.ts
  src/storage/engine/flatbuffers/index.ts
  src/storage/flatbuffers/contractEventModel.ts
  src/storage/flatbuffers/messageModel.test.ts
  src/storage/flatbuffers/messageModel.ts
  src/storage/flatbuffers/utils.test.ts
  src/storage/flatbuffers/utils.ts
  src/storage/flatbuffers/validations.test.ts
  src/storage/flatbuffers/validations.ts
  src/storage/sets/flatbuffers/userDataStore.test.ts
  src/storage/sets/flatbuffers/userDataStore.ts
  src/test/factories/flatbuffer.test.ts
  src/test/factories/flatbuffer.ts
  src/utils/errors.ts
  src/utils/generated/farcaster/message-data.ts
  src/utils/generated/farcaster/signature-scheme.ts
  src/utils/schemas/message.fbs
  tsconfig.json
Labels: feat

#212 fix(config): Default to IPv6 for Gossip and RPC
  .config/hub.config.ts
  src/network/rpc/server.ts
Labels: bug

#214 fix(gossip): store addresses from existing connections into the address book
  src/hub.ts
  src/network/p2p/node.ts
Labels: bug

#210 test(signerStore): improve coverage and documentation
  .vscode/settings.json
  src/storage/engine/flatbuffers/index.test.ts
  src/storage/engine/flatbuffers/index.ts
  src/storage/flatbuffers/contractEventModel.test.ts
  src/storage/flatbuffers/contractEventModel.ts
  src/storage/flatbuffers/types.ts
  src/storage/flatbuffers/utils.test.ts
  src/storage/flatbuffers/utils.ts
  src/storage/sets/flatbuffers/reactionStore.test.ts
  src/storage/sets/flatbuffers/reactionStore.ts
  src/storage/sets/flatbuffers/signerStore.test.ts
  src/storage/sets/flatbuffers/signerStore.ts
  src/test/factories/flatbuffer.ts
  src/utils/generated/farcaster/contract-event-type.ts
  src/utils/generated/farcaster/contract-event.ts
  src/utils/schemas/contract_event.fbs
Labels: bug, docs, chore

#217 test(SignerStore): fix incorrect variable names and casts
  src/storage/sets/flatbuffers/signerStore.test.ts
Labels: chore

#216 fix(VerificationStore): increase test coverage, change conflict resolution, add docs
  src/storage/flatbuffers/types.ts
  src/storage/sets/flatbuffers/signerStore.ts
  src/storage/sets/flatbuffers/verificationStore.test.ts
  src/storage/sets/flatbuffers/verificationStore.ts
Labels: bug, docs, chore

#225 chore(readme): document identity creation step
  README.md
Labels: chore

#226 feat: prototype new error handling pattern and refactor one method to use it
  src/network/p2p/node.test.ts
  src/network/p2p/node.ts
  src/utils/hubErrors.ts
Labels: feat

#227 refactor(p2p): network/p2p uses HubResults and HubErrors
  CONTRIBUTING.md
  src/cli.ts
  src/hub.ts
  src/network/p2p/connectionFilter.ts
  src/network/p2p/node.test.ts
  src/network/p2p/node.ts
  src/network/p2p/protocol.ts
  src/network/rpc/client.ts
  src/network/sync/syncEngine.ts
  src/network/sync/syncId.ts
  src/test/perf/bench.ts
  src/utils/hubErrors.ts
  src/utils/p2p.test.ts
  src/utils/p2p.ts
  src/utils/safe.ts
Labels: chore

#228 refactor(followStore): add unit test coverage, change conflict logic
  src/storage/sets/flatbuffers/followStore.test.ts
  src/storage/sets/flatbuffers/followStore.ts
  src/storage/sets/flatbuffers/reactionStore.ts
  src/storage/sets/followSet.ts
Labels: bug, chore

#230 refactor(Errors): replace *Error with HubError wherever possible
  src/hub.ts
  src/network/p2p/node.test.ts
  src/network/rpc/rpc.test.ts
  src/storage/db/binaryrocksdb.test.ts
  src/storage/db/binaryrocksdb.ts
  src/storage/db/cast.test.ts
  src/storage/db/follow.test.ts
  src/storage/db/reaction.test.ts
  src/storage/db/rocksdb.test.ts
  src/storage/db/rocksdb.ts
  src/storage/db/verification.test.ts
  src/storage/engine/engine.signer.test.ts
  src/storage/engine/flatbuffers/index.test.ts
  src/storage/engine/flatbuffers/index.ts
  src/storage/engine/index.ts
  src/storage/flatbuffers/contractEventModel.test.ts
  src/storage/flatbuffers/messageModel.test.ts
  src/storage/flatbuffers/utils.test.ts
  src/storage/flatbuffers/utils.ts
  src/storage/flatbuffers/validations.test.ts
  src/storage/flatbuffers/validations.ts
  src/storage/provider/idRegistryProvider.ts
  src/storage/sets/flatbuffers/castStore.test.ts
  src/storage/sets/flatbuffers/castStore.ts
  src/storage/sets/flatbuffers/followStore.test.ts
  src/storage/sets/flatbuffers/reactionStore.test.ts
  src/storage/sets/flatbuffers/reactionStore.ts
  src/storage/sets/flatbuffers/signerStore.test.ts
  src/storage/sets/flatbuffers/signerStore.ts
  src/storage/sets/flatbuffers/userDataStore.test.ts
  src/storage/sets/flatbuffers/userDataStore.ts
  src/storage/sets/flatbuffers/verificationStore.test.ts
  src/storage/sets/flatbuffers/verificationStore.ts
  src/storage/sets/followSet.test.ts
  src/storage/sets/reactionSet.test.ts
  src/storage/sets/verificationSet.test.ts
  src/test/e2e/hub.test.ts
  src/utils/errors.ts
  src/utils/hubErrors.ts
  src/utils/p2p.ts
Labels: chore

#219 feat: casts gRPC implementation
  package.json
  src/network/rpc/flatbuffers/castService.test.ts
  src/network/rpc/flatbuffers/castService.ts
  src/network/rpc/flatbuffers/client.ts
  src/network/rpc/flatbuffers/server.ts
  src/storage/engine/flatbuffers/index.test.ts
  src/storage/engine/flatbuffers/index.ts
  src/storage/flatbuffers/utils.ts
  src/storage/flatbuffers/validations.test.ts
  src/storage/flatbuffers/validations.ts
  src/utils/generated/farcaster/get-all-cast-messages-by-user-request.ts
  src/utils/generated/farcaster/get-cast-request.ts
  src/utils/generated/farcaster/get-casts-by-mention-request.ts
  src/utils/generated/farcaster/get-casts-by-parent-request.ts
  src/utils/generated/farcaster/get-casts-by-user-request.ts
  src/utils/generated/farcaster/messages-response.ts
  src/utils/generated/rpc_generated.ts
  src/utils/hubErrors.ts
  src/utils/schemas/rpc.fbs
  yarn.lock
Labels: feat

#232 feat: 128-bit blake3 hashes
  src/storage/flatbuffers/messageModel.test.ts
  src/storage/flatbuffers/messageModel.ts
  src/storage/flatbuffers/validations.test.ts
  src/storage/flatbuffers/validations.ts
  src/test/factories/flatbuffer.test.ts
  src/test/factories/flatbuffer.ts
  src/utils/generated/farcaster/hash-scheme.ts
  src/utils/generated/farcaster/message.ts
  src/utils/schemas/message.fbs
Labels: feat

#241 feat: gRPC for follows
  src/network/rpc/flatbuffers/castService.test.ts
  src/network/rpc/flatbuffers/castService.ts
  src/network/rpc/flatbuffers/client.ts
  src/network/rpc/flatbuffers/followService.test.ts
  src/network/rpc/flatbuffers/followService.ts
  src/network/rpc/flatbuffers/server.ts
  src/storage/engine/flatbuffers/index.ts
  src/utils/generated/farcaster/get-cast-request.ts
  src/utils/generated/farcaster/get-casts-by-fid-request.ts
  src/utils/generated/farcaster/get-casts-by-mention-request.ts
  src/utils/generated/farcaster/get-casts-by-parent-request.ts
  src/utils/generated/farcaster/get-follow-request.ts
  src/utils/generated/farcaster/get-follows-by-fid-request.ts
  src/utils/generated/farcaster/get-follows-by-user-request.ts
  src/utils/generated/rpc_generated.ts
  src/utils/schemas/rpc.fbs
Labels: feat

#242 test(CastStore): add coverage for edge cases
  src/storage/sets/flatbuffers/castStore.test.ts
  src/storage/sets/flatbuffers/castStore.ts
  src/storage/sets/flatbuffers/reactionStore.ts
Labels: chore

#243 test(UserDataStore): increase test coverage
  src/storage/sets/flatbuffers/followStore.ts
  src/storage/sets/flatbuffers/reactionStore.ts
  src/storage/sets/flatbuffers/signerStore.ts
  src/storage/sets/flatbuffers/userDataStore.test.ts
  src/storage/sets/flatbuffers/userDataStore.ts
  src/storage/sets/flatbuffers/verificationStore.ts
Labels: chore

#244 feat: grpc reactions service
  src/network/rpc/flatbuffers/client.ts
  src/network/rpc/flatbuffers/reactionService.test.ts
  src/network/rpc/flatbuffers/reactionService.ts
  src/network/rpc/flatbuffers/server.ts
  src/storage/engine/flatbuffers/index.ts
  src/storage/sets/flatbuffers/reactionStore.test.ts
  src/storage/sets/flatbuffers/reactionStore.ts
  src/utils/generated/farcaster/get-reaction-request.ts
  src/utils/generated/farcaster/get-reactions-by-cast-request.ts
  src/utils/generated/farcaster/get-reactions-by-fid-request.ts
  src/utils/generated/rpc_generated.ts
  src/utils/schemas/rpc.fbs
Labels: feat

#245 feat: configure gRpc port
  src/network/rpc/flatbuffers/server.ts
Labels: feat

#246 feat: verifications gRPC service
  src/network/rpc/flatbuffers/client.ts
  src/network/rpc/flatbuffers/followService.test.ts
  src/network/rpc/flatbuffers/followService.ts
  src/network/rpc/flatbuffers/reactionService.test.ts
  src/network/rpc/flatbuffers/server.ts
  src/network/rpc/flatbuffers/verificationService.test.ts
  src/network/rpc/flatbuffers/verificationService.ts
  src/storage/engine/flatbuffers/index.ts
  src/storage/flatbuffers/validations.ts
  src/utils/generated/farcaster/get-verification-request.ts
  src/utils/generated/farcaster/get-verifications-by-fid-request.ts
  src/utils/generated/rpc_generated.ts
  src/utils/schemas/rpc.fbs
Labels: feat

#249 perf: Improve trie memory efficiency
  src/network/sync/merkleTrie.test.ts
  src/network/sync/trieNode.test.ts
  src/network/sync/trieNode.ts
  src/test/factories.ts
Labels: chore

#250 feat: gRPC signers service and user data service
  src/network/rpc/flatbuffers/client.ts
  src/network/rpc/flatbuffers/server.ts
  src/network/rpc/flatbuffers/signerService.test.ts
  src/network/rpc/flatbuffers/signerService.ts
  src/network/rpc/flatbuffers/userDataService.test.ts
  src/network/rpc/flatbuffers/userDataService.ts
  src/storage/engine/flatbuffers/index.test.ts
  src/storage/engine/flatbuffers/index.ts
  src/storage/flatbuffers/contractEventModel.ts
  src/storage/flatbuffers/types.ts
  src/storage/sets/flatbuffers/signerStore.test.ts
  src/storage/sets/flatbuffers/signerStore.ts
  src/test/e2e/hub.test.ts
  src/utils/generated/farcaster/fids-response.ts
  src/utils/generated/farcaster/get-custody-event-request.ts
  src/utils/generated/farcaster/get-fids-request.ts
  src/utils/generated/farcaster/get-signer-request.ts
  src/utils/generated/farcaster/get-signers-by-fid-request.ts
  src/utils/generated/farcaster/get-user-data-by-fid-request.ts
  src/utils/generated/farcaster/get-user-data-request.ts
  src/utils/generated/rpc_generated.ts
  src/utils/schemas/rpc.fbs
Labels: feat

#251 feat: gRPC sync service
  src/network/rpc/flatbuffers/client.ts
  src/network/rpc/flatbuffers/server.ts
  src/network/rpc/flatbuffers/syncService.test.ts
  src/network/rpc/flatbuffers/syncService.ts
  src/storage/engine/flatbuffers/index.ts
  src/test/factories/flatbuffer.test.ts
  src/utils/generated/farcaster/get-all-messages-by-fid-request.ts
  src/utils/generated/rpc_generated.ts
  src/utils/schemas/rpc.fbs
Labels: feat
