Repository farcasterxyz/hub-monorepo, pull requests merged in 2022-10, with the labels that each got.

#137 chore: create executeable entrypoint (server.ts) using tsx
  nodemon.json
  package.json
  src/server.ts
  yarn.lock
Labels: chore

#142 test: fix yarn jest failing on node.test.ts
  jest.config.ts
  package.json
Labels: bug

#140 feat: hub executable
  package.json
  src/hub.test.ts
  src/hub.ts
  src/server.ts
  yarn.lock
Labels: feat

#143 fix(CastSet): remove-wins should trump last-write-wins
  src/engine/index.ts
  src/sets/castSet.test.ts
  src/sets/castSet.ts
Labels: bug, docs

#147 test(SignerSet): improve coverage, fix incorrect assertions, update class documentation
  src/sets/signerSet.test.ts
  src/sets/signerSet.ts
Labels: chore

#148 chore: upgrade node to v18.7.0 to sync with other farcaster repos
  .github/workflows/ci.yml
  package.json
Labels: chore

#146 feat: Script to benchmark a network of Hubs
  package.json
  src/bench.ts
  src/engine/mock.ts
  src/hub.ts
  src/network/node.test.ts
  src/network/node.ts
  src/network/rpc.ts
  src/server.ts
  src/types/typeguards.ts
  tsconfig.json
Labels: feat

#152 feat: add mentions to cast and rename cast body attributes
  src/storage/db/cast.test.ts
  src/storage/db/cast.ts
  src/storage/engine/engine.cast.test.ts
  src/storage/engine/index.ts
  src/test/client.test.ts
  src/test/client.ts
  src/test/factories.ts
  src/types/index.ts
  src/types/typeguards.ts
Labels: feat

#153 fix: broken package.json commands, broken named imports due to node --experimental-modules
  package.json
  src/network/rpc/index.ts
Labels: bug

#159 fix: allow configuration of libp2p listen port
  src/cli.ts
  src/hub.ts
  src/network/p2p/node.ts
  src/storage/engine/engine.mock.test.ts
Labels: feat

#160 chore: add eslint-plugin-security to linting to catch security issues
  .eslintrc.cjs
  Dockerfile
  package.json
  yarn.lock
Labels: chore

#164 feat: add support for persistent peerIds
  .gitignore
  package.json
  src/cli.ts
  src/hub.ts
  src/network/p2p/node.ts
Labels: feat

#165 chore: remove unused dep node-fetch
  package.json
  yarn.lock
Labels: chore

#168 feat: peer allow-list to restrict connections
  package.json
  src/cli.ts
  src/hub.ts
  src/network/p2p/connectionFilter.test.ts
  src/network/p2p/connectionFilter.ts
  src/network/p2p/node.test.ts
  src/network/p2p/node.ts
  yarn.lock
Labels: feat

#169 feat: add pino for logging
  .eslintrc.cjs
  package.json
  src/cli.ts
  src/hub.ts
  src/network/p2p/connectionFilter.ts
  src/network/p2p/node.ts
  src/network/rpc/server.ts
  src/test/perf/bench.ts
  src/utils/logger.ts
  yarn.lock
Labels: feat

#170 chore: add more detail to hub, node, and rpc logs
  src/hub.ts
  src/network/p2p/node.ts
  src/network/rpc/server.ts
  src/utils/logger.ts
Labels: chore

#171 feat: Generate multiple PeerIds
  src/cli.ts
Labels: feat

#174 fix: update dockerfile to specify rpc and p2p ports
  Dockerfile
  src/hub.ts
Labels: bug

#175 fix: Dockerfile
  Dockerfile
Labels: bug

#176 refactor: IDRegistry to IdRegistry to align with protocol naming
  src/hub.ts
  src/network/p2p/protocol.test.ts
  src/network/p2p/protocol.ts
  src/network/rpc/client.ts
  src/network/rpc/interfaces.ts
  src/network/rpc/rpc.test.ts
  src/network/rpc/server.ts
  src/storage/db/signer.ts
  src/storage/engine/engine.cast.test.ts
  src/storage/engine/engine.follow.test.ts
  src/storage/engine/engine.reaction.test.ts
  src/storage/engine/engine.revoke.test.ts
  src/storage/engine/engine.signer.test.ts
  src/storage/engine/engine.verification.test.ts
  src/storage/engine/index.ts
  src/storage/engine/mock.ts
  src/storage/provider/abis.ts
  src/storage/provider/idRegistryProvider.ts
  src/storage/sets/signerSet.test.ts
  src/storage/sets/signerSet.ts
  src/test/e2e/hub.test.ts
  src/test/e2e/rpcSync.test.ts
  src/test/factories.ts
  src/test/perf/bench.ts
  src/types/index.ts
  src/types/typeguards.ts
Labels: chore

#177 chore: use IP address strings to specify hub address
  .config/hub.config.ts
  src/cli.ts
  src/hub.ts
  src/network/p2p/node.test.ts
  src/network/p2p/node.ts
  src/test/perf/bench.ts
  src/utils/p2p.test.ts
  src/utils/p2p.ts
Labels: chore

#181 feat: add flatbuffers implementation for cast set
  .eslintrc.cjs
  jest.config.ts
  package.json
  src/network/sync/syncEngine.test.ts
  src/storage/db/binaryrocksdb.test.ts
  src/storage/db/binaryrocksdb.ts
  src/storage/db/jestUtils.ts
  src/storage/flatbuffers/model.test.ts
  src/storage/flatbuffers/model.ts
  src/storage/flatbuffers/typeguards.ts
  src/storage/flatbuffers/types.ts
  src/storage/flatbuffers/utils.test.ts
  src/storage/flatbuffers/utils.ts
  src/storage/sets/flatbuffers/castSet.test.ts
  src/storage/sets/flatbuffers/castSet.ts
  src/test/factories.ts
  src/test/factories/flatbuffer.test.ts
  src/test/factories/flatbuffer.ts
  src/types/index.ts
  src/utils/generated/farcaster/cast-add-body.ts
  src/utils/generated/farcaster/cast-id.ts
  src/utils/generated/farcaster/cast-remove-body.ts
  src/utils/generated/farcaster/farcaster-network.ts
  src/utils/generated/farcaster/follow-body.ts
  src/utils/generated/farcaster/hash-scheme.ts
  src/utils/generated/farcaster/message-body.ts
  src/utils/generated/farcaster/message-data.ts
  src/utils/generated/farcaster/message-type.ts
  src/utils/generated/farcaster/message.ts
  src/utils/generated/farcaster/reaction-body.ts
  src/utils/generated/farcaster/reaction-type.ts
  src/utils/generated/farcaster/signature-scheme.ts
  src/utils/generated/farcaster/user-id.ts
  src/utils/generated/message_generated.ts
  src/utils/schemas/message.fbs
  yarn.lock
Labels: feat

#184 feat: add flatbuffer followset
  src/storage/flatbuffers/model.ts
  src/storage/flatbuffers/typeguards.ts
  src/storage/flatbuffers/types.ts
  src/storage/sets/flatbuffers/castSet.ts
  src/storage/sets/flatbuffers/followSet.test.ts
  src/storage/sets/flatbuffers/followSet.ts
  src/test/factories/flatbuffer.ts
Labels: feat

#188 feat: flatbuffers verification set
  src/storage/flatbuffers/model.ts
  src/storage/flatbuffers/typeguards.ts
  src/storage/flatbuffers/types.ts
  src/storage/sets/flatbuffers/verificationSet.test.ts
  src/storage/sets/flatbuffers/verificationSet.ts
  src/test/factories/flatbuffer.test.ts
  src/test/factories/flatbuffer.ts
  src/utils/generated/farcaster/message-body.ts
  src/utils/generated/farcaster/message-data.ts
  src/utils/generated/farcaster/message-type.ts
  src/utils/generated/farcaster/verification-add-eth-address-body.ts
  src/utils/generated/farcaster/verification-remove-body.ts
  src/utils/generated/message_generated.ts
  src/utils/schemas/message.fbs
  src/utils/verification.test.ts
  src/utils/verification.ts
  tsconfig.json
Labels: feat

#179 feat: Implement diff sync
  package.json
  src/hub.ts
  src/network/p2p/protocol.test.ts
  src/network/p2p/protocol.ts
  src/network/rpc/client.ts
  src/network/rpc/interfaces.ts
  src/network/rpc/rpc.test.ts
  src/network/rpc/server.ts
  src/network/sync/merkleTrie.test.ts
  src/network/sync/merkleTrie.ts
  src/network/sync/syncEngine.test.ts
  src/network/sync/syncEngine.ts
  src/network/sync/trieNode.ts
  src/storage/engine/index.ts
  src/storage/engine/mock.ts
  src/test/e2e/differentialSync.test.ts
  src/test/e2e/hub.test.ts
  src/test/e2e/rpcSync.test.ts
  src/test/factories.ts
  src/types/index.ts
  src/types/typeguards.ts
  yarn.lock
Labels: feat

#192 chore: add progress logs to perf tests
  .config/hub.config.ts
  package.json
  src/cli.ts
  src/test/perf/bench.ts
  src/test/perf/scenario.ts
  src/test/perf/utils.ts
  src/test/perf/verify.ts
  yarn.lock
Labels: chore
