Repository farcasterxyz/hub-monorepo, pull requests merged in 2022-08, with the labels that each got.

#77 feat: follow set
  src/client.test.ts
  src/client.ts
  src/engine/engine.follow.test.ts
  src/engine/engine.revoke.test.ts
  src/engine/index.ts
  src/factories.ts
  src/sets/followSet.test.ts
  src/sets/followSet.ts
  src/types/index.ts
  src/types/typeguards.ts
Labels: documentation, feature

#80 bugfix: Faker imported twice in client.test.ts
  src/client.test.ts
Labels: bugfix

#81 chore: use fid instead of username to identify accounts
  src/client.test.ts
  src/client.ts
  src/engine/engine.cast.test.ts
  src/engine/engine.follow.test.ts
  src/engine/engine.reaction.test.ts
  src/engine/engine.revoke.test.ts
  src/engine/engine.signer.test.ts
  src/engine/engine.verification.test.ts
  src/engine/index.ts
  src/factories.ts
  src/farcasterNode.ts
  src/node.ts
  src/sets/reactionSet.ts
  src/sets/verificationSet.test.ts
  src/types/index.ts
Labels: chore

#82 chore: idempotent merge functions
  src/engine/engine.cast.test.ts
  src/engine/engine.reaction.test.ts
  src/engine/engine.verification.test.ts
  src/engine/index.ts
  src/sets/castSet.test.ts
  src/sets/castSet.ts
  src/sets/followSet.test.ts
  src/sets/followSet.ts
  src/sets/reactionSet.test.ts
  src/sets/reactionSet.ts
  src/sets/signerSet.test.ts
  src/sets/signerSet.ts
  src/sets/verificationSet.test.ts
  src/sets/verificationSet.ts
Labels: chore

#86 feat: IDRegistryProvider
  src/engine/engine.cast.test.ts
  src/engine/engine.follow.test.ts
  src/engine/engine.reaction.test.ts
  src/engine/engine.revoke.test.ts
  src/engine/engine.signer.test.ts
  src/engine/engine.verification.test.ts
  src/engine/index.ts
  src/provider/abis.ts
  src/provider/idRegistryProvider.ts
Labels: feature

#90 feat: one custody address per fid
  src/client.test.ts
  src/client.ts
  src/engine/engine.reaction.test.ts
  src/engine/engine.revoke.test.ts
  src/engine/engine.signer.test.ts
  src/engine/engine.verification.test.ts
  src/engine/index.ts
  src/factories.ts
  src/sets/signerSet.test.ts
  src/sets/signerSet.ts
  src/types/index.ts
  src/types/typeguards.ts
Labels: documentation, feature

#92 feat: message types and network IDs
  src/client.test.ts
  src/client.ts
  src/engine/engine.cast.test.ts
  src/engine/engine.follow.test.ts
  src/engine/engine.reaction.test.ts
  src/engine/engine.revoke.test.ts
  src/engine/engine.signer.test.ts
  src/engine/engine.verification.test.ts
  src/engine/index.ts
  src/factories.ts
  src/sets/castSet.test.ts
  src/sets/castSet.ts
  src/sets/followSet.test.ts
  src/sets/followSet.ts
  src/sets/reactionSet.test.ts
  src/sets/reactionSet.ts
  src/sets/signerSet.test.ts
  src/sets/verificationSet.test.ts
  src/sets/verificationSet.ts
  src/types/index.ts
  src/types/typeguards.ts
Labels: documentation, feature

#33 feat: URLs
  .eslintrc.js
  .vscode/settings.json
  package.json
  src/engine/engine.cast.test.ts
  src/engine/engine.follow.test.ts
  src/engine/engine.reaction.test.ts
  src/engine/engine.verification.test.ts
  src/engine/index.ts
  src/factories.ts
  src/types/index.ts
  src/types/typeguards.ts
  src/urls/baseUrl.ts
  src/urls/castUrl.ts
  src/urls/chainAccountUrl.ts
  src/urls/chainUrl.ts
  src/urls/index.ts
  src/urls/test/cast.test.ts
  src/urls/test/chain.test.ts
  src/urls/test/chainAccount.test.ts
  src/urls/test/index.test.ts
  src/urls/test/user.test.ts
  src/urls/test/utils.ts
  src/urls/userUrl.ts
  src/urls/utils.ts
  src/urls/web2Url.ts
  src/utils.ts
  yarn.lock
Labels: documentation, feature

#93 feat: Add Dockerfile for containerized builds
  Dockerfile
Labels: feature

#94 feat: allow checksummed, lowercased, or uppercased externalUri for verifications
  src/engine/engine.verification.test.ts
  src/engine/index.ts
  src/factories.ts
Labels: feature
