Repository farcasterxyz/hub-monorepo, pull requests merged in 2022-09, with the labels that each got.

#96 feat: add a generic merge handler for the engine
  src/engine/engine.cast.test.ts
  src/engine/engine.follow.test.ts
  src/engine/engine.reaction.test.ts
  src/engine/engine.revoke.test.ts
  src/engine/engine.signer.test.ts
  src/engine/engine.verification.test.ts
  src/engine/index.ts
Labels: feature

#97 refactor: use esm instead of cjs
  .eslintrc.cjs
  .prettierrc.cjs
  .prettierrc.js
  package.json
  tsconfig.json
Labels: chore

#99 feat: Implement a JSON RPC server and client
  package.json
  src/engine/index.ts
  src/network/rpc.test.ts
  src/network/rpc.ts
  src/sets/castSet.ts
  src/sets/signerSet.ts
  yarn.lock
Labels: feature

#100 chore: bump node version and upgrade packages
  package.json
  src/network/rpc.ts
  yarn.lock
Labels: chore

#105 feat(utils): Generate a large number of mock events to populate an Engine
  src/engine/engine.mock.test.ts
  src/factories.ts
Labels: feature

#106 feat(sync): Implement a simple Engine sync over RPC
  src/engine/index.ts
  src/network/rpc.test.ts
  src/network/rpc.ts
  src/network/rpcSync.test.ts
Labels: feature

#110 chore: upgrade jest and related packages to latest
  package.json
  yarn.lock
Labels: chore

#111 chore: delete package-lock.json
  package-lock.json
Labels: chore

#95 feat: add libp2p and initial support for sync
  jest.config.ts
  package.json
  src/network/node.test.ts
  src/network/node.ts
  src/network/protocol.test.ts
  src/network/protocol.ts
  src/network/rpc.ts
  src/network/typeguards.ts
  src/types/typeguards.ts
  tsconfig.json
  yarn.lock
Labels: feature

#127 chore: update packages (sep 2022)
  package.json
  yarn.lock
Labels: chore

#107 feat: rocksdb persistence and make CastSet a LWW CRDT
  .gitignore
  jest.config.ts
  package.json
  src/abstract-leveldown.d.ts
  src/db/cast.test.ts
  src/db/cast.ts
  src/db/follow.test.ts
  src/db/follow.ts
  src/db/jestUtils.ts
  src/db/message.test.ts
  src/db/message.ts
  src/db/reaction.test.ts
  src/db/reaction.ts
  src/db/rocksdb.test.ts
  src/db/rocksdb.ts
  src/db/signer.test.ts
  src/db/signer.ts
  src/db/verification.test.ts
  src/db/verification.ts
  src/engine/engine.cast.test.ts
  src/engine/engine.follow.test.ts
  src/engine/engine.mock.test.ts
  src/engine/engine.reaction.test.ts
  src/engine/engine.revoke.test.ts
  src/engine/engine.signer.test.ts
  src/engine/engine.verification.test.ts
  src/engine/index.ts
  src/engine/mock.ts
  src/errors.ts
  src/network/rpc.test.ts
  src/network/rpc.ts
  src/network/rpcSync.test.ts
  src/provider/idRegistryProvider.ts
  src/rocksdb.d.ts
  src/sets/castSet.test.ts
  src/sets/castSet.ts
  src/sets/followSet.test.ts
  src/sets/followSet.ts
  src/sets/reactionSet.test.ts
  src/sets/reactionSet.ts
  src/sets/signerSet.test.ts
  src/sets/signerSet.ts
  src/sets/verificationSet.test.ts
  src/sets/verificationSet.ts
  src/types/typeguards.ts
  src/urls/castUrl.ts
  src/urls/chainAccountUrl.ts
  src/urls/chainUrl.ts
  src/urls/index.ts
  src/urls/test/index.test.ts
  src/urls/userUrl.ts
  tsconfig.json
  yarn.lock
Labels: feature

#133 ci: should not fail on every project coverage decrease
  codecov.yml
Labels: chore

#130 feat: Hubs
  package.json
  src/engine/engine.mock.test.ts
  src/engine/index.ts
  src/engine/mock.ts
  src/hub.test.ts
  src/hub.ts
  src/network/node.test.ts
  src/network/node.ts
  src/network/protocol.test.ts
  src/network/protocol.ts
  src/network/rpc.test.ts
  src/network/rpc.ts
  src/network/rpcSync.test.ts
  src/network/typeguards.ts
  yarn.lock
Labels: feat
