Repository farcasterxyz/hub-monorepo, pull requests merged in 2023-09, with the labels that each got.

#1313 fix: Count peer validation errors during sync
  .changeset/sweet-planets-deliver.md
  apps/hubble/src/network/sync/syncEngine.ts
  packages/hub-nodejs/examples/chron-feed/index.ts
Labels: t-bug

#1314 chore: Remove pre-fetching signers during sync
  .changeset/fresh-wombats-sing.md
  apps/hubble/src/network/sync/syncEngine.ts
Labels: t-chore

#1315 chore: Update docs to explicitly state restart
  apps/hubble/src/cli.ts
  apps/hubble/www/docs/intro/install.md
  apps/hubble/www/docs/intro/monitoring.md
Labels: t-docs

#1317 chore: Deprecate "status" command
  .changeset/empty-sloths-drum.md
  apps/hubble/src/cli.ts
  apps/hubble/www/docs/docs/cli.md
  apps/hubble/www/docs/intro/install.md
Labels: t-chore

#1316 chore: Update dashboard with sync details
  .changeset/swift-nails-suffer.md
  apps/hubble/grafana/grafana-dashboard.json
Labels: t-chore

#1319 fix: Fix progress bar for non-tty
  .changeset/clever-students-join.md
  apps/hubble/docker-compose.yml
  apps/hubble/src/utils/progressBars.ts
Labels: t-bug

#1320 fix: Grafana dashboards - update descriptions
  .changeset/four-jokes-battle.md
  apps/hubble/grafana/grafana-dashboard.json
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/utils/statsd.ts
Labels: t-devex

#1321 fix: Supress progress logs during tests
  .changeset/hungry-camels-kiss.md
  apps/hubble/src/utils/progressBars.ts
Labels: t-chore

#1322 fix: Custom linter for Grafana JSON
  .changeset/eight-jeans-sell.md
  apps/hubble/grafana/grafana-dashboard.json
  apps/hubble/package.json
  apps/hubble/scripts/linter.cjs
Labels: t-devex

#1323 fix: storage cache progress bar
  .changeset/late-crabs-switch.md
  apps/hubble/package.json
  apps/hubble/src/storage/stores/storageCache.ts
Labels: t-bug

#1330 feat: HTTP API
  .changeset/kind-windows-laugh.md
  apps/hubble/package.json
  apps/hubble/src/rpc/httpServer.ts
  apps/hubble/src/rpc/test/httpServer.test.ts
  apps/hubble/src/test/utils.ts
  apps/hubble/src/utils/progressBars.ts
  packages/hub-nodejs/src/index.ts
  yarn.lock
Labels: t-feat

#1340 chore: Update descriptions in replicator example README
  packages/hub-nodejs/examples/replicate-data-postgres/README.md
Labels: t-docs, t-chore

#1343 feat: move storage limit constants to core
  .changeset/tricky-fans-confess.md
  apps/hubble/src/rpc/test/server.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/jobs/pruneMessagesJob.test.ts
  apps/hubble/src/storage/stores/castStore.ts
  apps/hubble/src/storage/stores/linkStore.ts
  apps/hubble/src/storage/stores/reactionStore.ts
  apps/hubble/src/storage/stores/store.ts
  apps/hubble/src/storage/stores/userDataStore.ts
  apps/hubble/src/storage/stores/usernameProofStore.test.ts
  apps/hubble/src/storage/stores/usernameProofStore.ts
  apps/hubble/src/storage/stores/verificationStore.ts
  packages/core/src/index.ts
  packages/core/src/limits.ts
  packages/core/src/protobufs/generated/request_response.ts
  packages/hub-nodejs/src/generated/request_response.ts
  packages/hub-web/src/generated/request_response.ts
  protobufs/schemas/request_response.proto
Labels: t-feat

#1353 chore: Add cli docs linter
  .changeset/perfect-spoons-serve.md
  .github/workflows/ci.yml
  apps/hubble/scripts/clidocs.cjs
  apps/hubble/scripts/grafanadash.cjs
  apps/hubble/scripts/linter.cjs
  apps/hubble/src/cli.ts
  apps/hubble/www/docs/docs/cli.md
Labels: t-chore

#1352 feat: Add hub operator's FID
  .changeset/serious-students-happen.md
  apps/hubble/docker-compose.yml
  apps/hubble/grafana/grafana-dashboard.json
  apps/hubble/scripts/clidocs.cjs
  apps/hubble/src/cli.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/test/mocks.ts
  apps/hubble/www/docs/docs/cli.md
  apps/hubble/www/docs/intro/install.md
  packages/core/src/protobufs/generated/request_response.ts
  packages/hub-nodejs/src/generated/request_response.ts
  protobufs/schemas/request_response.proto
  scripts/hubble.sh
Labels: t-feat

#1355 chore: release 1.5.2
  .changeset/big-buckets-work.md
  .changeset/clever-students-join.md
  .changeset/eight-jeans-sell.md
  .changeset/eleven-bulldogs-laugh.md
  .changeset/empty-sloths-drum.md
  .changeset/four-jokes-battle.md
  .changeset/fresh-wombats-sing.md
  .changeset/hungry-camels-kiss.md
  .changeset/kind-windows-laugh.md
  .changeset/late-crabs-switch.md
  .changeset/perfect-spoons-serve.md
  .changeset/purple-windows-travel.md
  .changeset/serious-students-happen.md
  .changeset/stupid-apricots-peel.md
  .changeset/sweet-planets-deliver.md
  .changeset/swift-nails-suffer.md
  .changeset/tricky-fans-confess.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#1217 Upgrading libp2p to v0.43.4
  apps/hubble/package.json
  yarn.lock
Labels: t-chore

#1327 feat: Add parameter to configure the max RPC subscribers per IP
  apps/hubble/src/cli.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/eventService.test.ts
  apps/hubble/www/docs/docs/cli.md
Labels: t-feat

#1354 fix: Fix onchain event dedup bug
  .changeset/breezy-ghosts-buy.md
  apps/hubble/src/eth/l2EventsProvider.ts
  apps/hubble/src/storage/stores/onChainEventStore.ts
  apps/hubble/src/storage/stores/onchainEventStore.test.ts
  packages/core/src/protobufs/generated/onchain_event.ts
  packages/hub-nodejs/src/generated/onchain_event.ts
  packages/hub-web/src/generated/onchain_event.ts
  protobufs/schemas/onchain_event.proto
Labels: t-bug

#1368 fix: Fix edge case where txIndex is the same as logIndex
  apps/hubble/src/storage/stores/onChainEventStore.ts
  apps/hubble/src/storage/stores/onchainEventStore.test.ts
Labels: t-bug

#1382 fix: Update links store size to be 2500 in the future
  .changeset/clean-buckets-kiss.md
  apps/hubble/src/rpc/test/server.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/jobs/pruneMessagesJob.test.ts
  apps/hubble/src/storage/stores/castStore.ts
  apps/hubble/src/storage/stores/linkStore.test.ts
  apps/hubble/src/storage/stores/linkStore.ts
  apps/hubble/src/storage/stores/reactionStore.ts
  apps/hubble/src/storage/stores/store.ts
  apps/hubble/src/storage/stores/userDataStore.ts
  apps/hubble/src/storage/stores/usernameProofStore.test.ts
  apps/hubble/src/storage/stores/usernameProofStore.ts
  apps/hubble/src/storage/stores/verificationStore.ts
  packages/core/src/limits.ts
Labels: t-bug

#1383 chore: release 1.5.4
  .changeset/bright-ducks-invent.md
  .changeset/clean-buckets-kiss.md
  .changeset/pink-eggs-kiss.md
  .changeset/red-moons-sip.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
Labels: t-chore

#1384 [docs] Update docs post migration
  apps/hubble/src/cli.ts
  apps/hubble/src/defaultConfig.ts
  apps/hubble/src/hubble.ts
  apps/hubble/www/README.md
  apps/hubble/www/docs/.vitepress/config.ts
  apps/hubble/www/docs/docs/api.md
  apps/hubble/www/docs/docs/cli.md
  apps/hubble/www/docs/docs/events.md
  apps/hubble/www/docs/docs/messages.md
  apps/hubble/www/docs/docs/onchain_events.md
  protobufs/README.md
  protobufs/docs/message.md
  protobufs/docs/rpc.md
Labels: t-docs

#1388 [feat] Add a function to parse timestamp from the eventId
  .changeset/real-islands-flash.md
  apps/hubble/src/storage/stores/storeEventHandler.test.ts
  packages/core/src/time.ts
Labels: t-feat

#1404 feat: add autouprade to hubble.sh
  apps/hubble/src/storage/stores/linkStore.test.ts
  scripts/hubble.sh
Labels: t-feat

#1409 chore: cleanup links store limit default
  .changeset/smooth-dancers-march.md
  packages/core/src/limits.ts
Labels: t-chore

#1412 chore: Release 1.5.5
  .changeset/bright-carrots-study.md
  .changeset/bright-planes-lay.md
  .changeset/fair-peas-check.md
  .changeset/four-crabs-reflect.md
  .changeset/modern-emus-behave.md
  .changeset/nasty-paws-hope.md
  .changeset/real-islands-flash.md
  .changeset/smooth-dancers-march.md
  .changeset/tricky-donkeys-do.md
  .changeset/wicked-wasps-kiss.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#1414 [feat] Support fname and onChainEvent SyncIds
  .changeset/silly-beers-fail.md
  apps/hubble/src/network/sync/merkleTrie.ts
  apps/hubble/src/network/sync/mock.ts
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/network/sync/syncId.test.ts
  apps/hubble/src/network/sync/syncId.ts
  apps/hubble/src/network/utils/factories.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/test/bench/helpers.ts
  packages/core/src/factories.ts
Labels: t-feat

#1424 feat: Repair sync trie when events and fnames are already present
  .changeset/green-ducks-sip.md
  apps/hubble/src/network/sync/merkleTrie.ts
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/userDataStore.test.ts
  apps/hubble/src/storage/stores/userDataStore.ts
  apps/hubble/src/storage/stores/utils.ts
Labels: t-feat

#1439 [feat] Add a flag to clear L2 events
  .changeset/forty-cycles-cough.md
  apps/hubble/src/cli.ts
  apps/hubble/src/hubble.ts
  apps/hubble/www/docs/docs/cli.md
Labels: t-feat
