Repository farcasterxyz/hub-monorepo, pull requests merged in 2023-02, with the labels that each got.

#492 chore: port subscribe gRPC method and event streaming to protobufs
  .changeset/perfect-cars-remain.md
  apps/hubble/src/rpc/server/index.ts
  apps/hubble/src/rpc/server/test/eventService.test.ts
  packages/js/src/client.ts
  packages/js/src/types.ts
  packages/js/src/utils.ts
  packages/protobufs/package.json
  packages/protobufs/src/generated/rpc.ts
  packages/protobufs/src/index.ts
  packages/protobufs/src/schemas/rpc.proto
  packages/utils/src/client.ts
  yarn.lock
Labels: chore

#496 chore: remove unused dependencies from packages
  .changeset/fair-dodos-smoke.md
  packages/js/package.json
  packages/js/src/types.ts
  packages/protobufs/package.json
  yarn.lock
Labels: chore

#498 chore: bump versions
  .changeset/fair-dodos-smoke.md
  .changeset/perfect-cars-remain.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/js/CHANGELOG.md
  packages/js/package.json
  packages/protobufs/CHANGELOG.md
  packages/protobufs/package.json
  packages/utils/CHANGELOG.md
  packages/utils/package.json
Labels: chore

#499 fix: create id registry events with tx hash
  apps/hubble/src/eth/ethEventsProvider.ts
Labels: bug

#501 feat: injest ethEventsProvider event logs in batches
  .gitignore
  apps/hubble/src/eth/ethEventsProvider.ts
Labels: feat

#503 fix: Docker image builds post Hub→Hubble rename
  Dockerfile
  package.json
Labels: bug

#505 fix: Update Turbo 1.6.3 → 1.7.3.canary.1 to fix Docker builds
  package.json
  yarn.lock
Labels: bug

#506 fix: Pin Turbo to 1.7.0 to fix Docker builds
  Dockerfile
  package.json
  yarn.lock
Labels: bug

#508 fix: Expose gossip protocol port outside of container by default
  Dockerfile
Labels: bug

#514 chore: upgrade packages [feb 2023]
  apps/hubble/package.json
  package.json
  packages/eslint-config-custom/package.json
  packages/js/package.json
  packages/protobufs/package.json
  packages/utils/package.json
  yarn.lock
Labels: chore

#516 chore: upgrade commander to 10
  apps/hubble/package.json
  yarn.lock
Labels: chore

#517 fix: Docker build failing after package removal
  Dockerfile
Labels: bug

#518 chore: Test Docker builds in CI
  .github/workflows/ci.yml
Labels: chore

#522 feat: increase SequentialMergeStore timeout
  apps/hubble/src/storage/stores/sequentialMergeStore.ts
Labels: feat

#532 chore: make version pinning stricter
  apps/hubble/package.json
  yarn.lock
Labels: chore

#534 chore: upgrade libp2p to 0.42.2
  .vscode/settings.json
  apps/hubble/package.json
  apps/hubble/src/network/p2p/gossipNode.test.ts
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/test/e2e/gossipNetwork.test.ts
  yarn.lock
Labels: chore

#544 docs: libp2p upgrade instructions
  apps/hubble/README.md
Labels: docs

#545 feat: improve hub logging
  apps/hubble/src/eth/ethEventsProvider.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/utils/logger.ts
Labels: feat

#547 fix: use msg instead of message for logs
  apps/hubble/src/hubble.ts
Labels: bug

#549 fix: 2 bugs that cause sync to run incorrectly
  apps/hubble/src/network/sync/merkleTrie.test.ts
  apps/hubble/src/network/sync/syncEngine.test.ts
  apps/hubble/src/network/sync/syncEnginePerf.test.ts
  apps/hubble/src/network/sync/trieNode.ts
Labels: bug

#553 feat: asynchronously fetch NameRegistryEvent expiry
  .changeset/slow-monkeys-serve.md
  apps/hubble/src/eth/ethEventsProvider.ts
  apps/hubble/src/eth/utils.test.ts
  apps/hubble/src/eth/utils.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/storage/db/nameRegistryEvent.test.ts
  apps/hubble/src/storage/db/nameRegistryEvent.ts
  apps/hubble/src/storage/db/types.ts
  apps/hubble/src/storage/jobs/updateNameRegistryEventExpiryJob.ts
  packages/protobufs/src/generated/job.ts
  packages/protobufs/src/schemas/job.proto
Labels: feat

#568 feat: add mentionsPositions to CastAddBody
  .changeset/eight-bats-leave.md
  packages/js/src/builders.test.ts
  packages/js/src/types.ts
  packages/js/src/utils.ts
  packages/protobufs/src/generated/message.ts
  packages/protobufs/src/schemas/message.proto
  packages/utils/src/factories.ts
  packages/utils/src/validations.test.ts
  packages/utils/src/validations.ts
Labels: feat

#569 fix: resolve out of range errors
  apps/hubble/src/network/sync/periodSyncJob.ts
  apps/hubble/src/storage/jobs/revokeSignerJob.ts
  apps/hubble/src/storage/jobs/updateNameRegistryEventExpiryJob.ts
Labels: bug

#571 chore: replace SequentialMergeStore with locks
  apps/hubble/package.json
  apps/hubble/src/rpc/server/test/concurrency.test.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/stores/ampStore.ts
  apps/hubble/src/storage/stores/castStore.ts
  apps/hubble/src/storage/stores/reactionStore.ts
  apps/hubble/src/storage/stores/sequentialMergeStore.test.ts
  apps/hubble/src/storage/stores/sequentialMergeStore.ts
  apps/hubble/src/storage/stores/signerStore.ts
  apps/hubble/src/storage/stores/types.ts
  apps/hubble/src/storage/stores/userDataStore.ts
  apps/hubble/src/storage/stores/verificationStore.ts
  packages/utils/src/errors.ts
  yarn.lock
Labels: chore

#572 chore: update changeset versions
  .changeset/bright-grapes-flash.md
  .changeset/eight-bats-leave.md
  .changeset/silly-boats-cry.md
  .changeset/slow-monkeys-serve.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/js/CHANGELOG.md
  packages/js/package.json
  packages/protobufs/CHANGELOG.md
  packages/protobufs/package.json
  packages/utils/CHANGELOG.md
  packages/utils/package.json
Labels: chore

#574 feat: support Renew events from the name registry contract
  apps/hubble/src/eth/ethEventsProvider.test.ts
  apps/hubble/src/eth/ethEventsProvider.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/storage/stores/userDataStore.ts
Labels: feat

#564 fix: relative path on hubble docs not resolving to contributing.md
  apps/hubble/README.md
Labels: docs

#562 feat: grpc api documentation
  packages/js/src/client.ts
  packages/protobufs/README.md
  packages/protobufs/docs/message.md
  packages/protobufs/docs/rpc.md
  packages/protobufs/src/schemas/message.proto
Labels: docs

#591 fix: Allow empty cast text
  .changeset/silly-trees-tickle.md
  packages/utils/src/validations.test.ts
  packages/utils/src/validations.ts
Labels: bug

#592 chore: bump package versions
  .changeset/silly-trees-tickle.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/js/CHANGELOG.md
  packages/js/package.json
  packages/utils/CHANGELOG.md
  packages/utils/package.json
Labels: chore

#594 chore: bump changeset versions
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  package.json
  packages/js/CHANGELOG.md
  packages/js/package.json
  packages/protobufs/CHANGELOG.md
  packages/protobufs/package.json
  packages/utils/CHANGELOG.md
  packages/utils/package.json
Labels: chore

#596 fix: Allow duplicate `mentionsPositions`
  .changeset/slimy-jobs-do.md
  packages/utils/src/validations.test.ts
  packages/utils/src/validations.ts
Labels: bug

#597 chore: bump changeset versions
  .changeset/slimy-jobs-do.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/js/CHANGELOG.md
  packages/js/package.json
  packages/utils/CHANGELOG.md
  packages/utils/package.json
Labels: chore

#601 docs: update READMEs to match latest behavior
  CONTRIBUTING.md
  README.md
  apps/hubble/README.md
  packages/protobufs/README.md
Labels: docs

#602 feat: add hub events log and delete amps (for now)
  .changeset/hot-pigs-wave.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/rpc/server/index.ts
  apps/hubble/src/rpc/server/test/ampService.test.ts
  apps/hubble/src/rpc/server/test/bulkService.test.ts
  apps/hubble/src/rpc/server/test/eventService.test.ts
  apps/hubble/src/rpc/server/test/userDataService.test.ts
  apps/hubble/src/storage/db/message.test.ts
  apps/hubble/src/storage/db/message.ts
  apps/hubble/src/storage/db/types.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/jobs/pruneMessagesJob.test.ts
  apps/hubble/src/storage/jobs/revokeSignerJob.test.ts
  apps/hubble/src/storage/stores/ampStore.test.ts
  apps/hubble/src/storage/stores/ampStore.ts
  apps/hubble/src/storage/stores/castStore.test.ts
  apps/hubble/src/storage/stores/castStore.ts
  apps/hubble/src/storage/stores/reactionStore.test.ts
  apps/hubble/src/storage/stores/reactionStore.ts
  apps/hubble/src/storage/stores/signerStore.test.ts
  apps/hubble/src/storage/stores/signerStore.ts
  apps/hubble/src/storage/stores/storeEventHandler.test.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
  apps/hubble/src/storage/stores/userDataStore.test.ts
  apps/hubble/src/storage/stores/userDataStore.ts
  apps/hubble/src/storage/stores/verificationStore.test.ts
  apps/hubble/src/storage/stores/verificationStore.ts
  apps/hubble/src/test/bench/syncEngine.ts
  apps/hubble/src/test/mocks.ts
  packages/js/src/builders.test.ts
  packages/js/src/builders.ts
  packages/js/src/client.ts
  packages/js/src/types.ts
  packages/js/src/utils.test.ts
  packages/js/src/utils.ts
  packages/protobufs/src/generated/hub_event.ts
  packages/protobufs/src/generated/message.ts
  packages/protobufs/src/generated/rpc.ts
  packages/protobufs/src/index.ts
  packages/protobufs/src/schemas/hub_event.proto
  packages/protobufs/src/schemas/message.proto
  packages/protobufs/src/schemas/rpc.proto
  packages/protobufs/src/typeguards.ts
  packages/protobufs/src/types.ts
  packages/utils/src/factories.test.ts
  packages/utils/src/factories.ts
  packages/utils/src/time.ts
  packages/utils/src/validations.test.ts
  packages/utils/src/validations.ts
Labels: feat

#603 chore: remove location
  .changeset/poor-bears-thank.md
  apps/hubble/src/rpc/server/test/userDataService.test.ts
  apps/hubble/src/storage/stores/userDataStore.test.ts
  packages/protobufs/docs/message.md
  packages/protobufs/src/generated/message.ts
  packages/protobufs/src/schemas/message.proto
  packages/utils/src/factories.ts
  packages/utils/src/validations.test.ts
  packages/utils/src/validations.ts
Labels: chore

#604 feat: support fromId param in subscribe method
  .changeset/great-eagles-explain.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/rpc/server/index.ts
  apps/hubble/src/rpc/server/test/eventService.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
  packages/js/src/client.ts
  packages/protobufs/src/generated/rpc.ts
  packages/protobufs/src/schemas/rpc.proto
  packages/utils/src/client.ts
Labels: feat

#615 chore: bump changeset versions
  .changeset/great-eagles-explain.md
  .changeset/hot-pigs-wave.md
  .changeset/poor-bears-thank.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/js/CHANGELOG.md
  packages/js/package.json
  packages/protobufs/CHANGELOG.md
  packages/protobufs/package.json
  packages/utils/CHANGELOG.md
  packages/utils/package.json
Labels: chore

#444 docs: add TSDoc annotations to time functions and properties
  packages/js/src/builders.ts
  packages/js/src/types.ts
  packages/utils/src/time.ts
Labels: docs
