Repository farcasterxyz/hub-monorepo, pull requests merged in 2023-01, with the labels that each got.

#343 docs: update READMEs
  CONTRIBUTING.md
  README.md
  app/README.md
  packages/flatbuffers/README.md
Labels: docs

#353 fix: replace relative paths with ~ paths
  app/src/eth/ethEventsProvider.test.ts
  app/src/flatbuffers/models/idRegistryEventModel.test.ts
  app/src/flatbuffers/models/nameRegistryEventModel.test.ts
  app/src/hub.ts
  app/src/network/sync/merkleTrie.ts
  app/src/network/sync/multiPeerSyncEngine.test.ts
  app/src/network/sync/syncEngine.ts
  app/src/utils/contractEvent.ts
Labels: chore

#357 feat: add PruneMessagesJobScheduler
  app/src/hub.ts
  app/src/storage/engine/index.ts
  app/src/storage/jobs/pruneMessagesJob.test.ts
  app/src/storage/jobs/pruneMessagesJob.ts
  app/src/storage/jobs/revokeSignerJob.ts
Labels: feat

#375 refactor: use little endian byte arrays
  app/src/eth/ethEventsProvider.test.ts
  app/src/eth/ethEventsProvider.ts
  app/src/eth/utils.test.ts
  app/src/eth/utils.ts
  app/src/flatbuffers/factories.test.ts
  app/src/flatbuffers/factories.ts
  app/src/flatbuffers/models/nameRegistryEventModel.test.ts
  app/src/flatbuffers/models/types.ts
  app/src/flatbuffers/models/validations.test.ts
  app/src/flatbuffers/models/validations.ts
  app/src/flatbuffers/utils/bytes.test.ts
  app/src/flatbuffers/utils/bytes.ts
  app/src/flatbuffers/utils/eip712.test.ts
  app/src/flatbuffers/utils/eip712.ts
  app/src/network/sync/multiPeerSyncEngine.test.ts
  app/src/network/sync/syncEngine.test.ts
  app/src/rpc/client/index.ts
  app/src/rpc/client/serviceRequests/userDataRequests.ts
  app/src/rpc/server/serviceImplementations/userDataImplementation.ts
  app/src/rpc/serviceDefinitions/userDataDefinition.ts
  app/src/rpc/test/ampService.test.ts
  app/src/rpc/test/castService.test.ts
  app/src/rpc/test/eventService.test.ts
  app/src/rpc/test/reactionService.test.ts
  app/src/rpc/test/signerService.test.ts
  app/src/rpc/test/submitService.test.ts
  app/src/rpc/test/syncService.test.ts
  app/src/rpc/test/userDataService.test.ts
  app/src/rpc/test/verificationService.test.ts
  app/src/storage/engine/index.test.ts
  app/src/storage/engine/index.ts
  app/src/storage/engine/seed.ts
  app/src/storage/jobs/revokeSignerJob.test.ts
  app/src/storage/jobs/revokeSignerJob.ts
  app/src/storage/stores/signerStore.test.ts
  app/src/storage/stores/userDataStore.test.ts
  app/src/storage/stores/verificationStore.test.ts
  app/src/utils/logger.ts
  packages/flatbuffers/package.json
  packages/flatbuffers/src/generated/rpc_generated.ts
  packages/flatbuffers/src/schemas/rpc.fbs
Labels: chore

#376 refactor: purge hexlify usage
  app/src/utils/crypto.test.ts
  app/src/utils/crypto.ts
Labels: chore

#377 feat: make cast parent and reaction target unions
  app/src/flatbuffers/factories.ts
  app/src/flatbuffers/models/validations.test.ts
  app/src/flatbuffers/models/validations.ts
  app/src/rpc/test/castService.test.ts
  app/src/rpc/test/reactionService.test.ts
  app/src/storage/engine/index.test.ts
  app/src/storage/stores/castStore.test.ts
  app/src/storage/stores/castStore.ts
  app/src/storage/stores/reactionStore.test.ts
  app/src/storage/stores/reactionStore.ts
  packages/flatbuffers/src/generated/message_generated.ts
  packages/flatbuffers/src/schemas/message.fbs
Labels: feat

#378 feat: add ed25519 utils and Signer classes
  app/package.json
  app/src/flatbuffers/factories.test.ts
  app/src/flatbuffers/factories.ts
  app/src/flatbuffers/models/messageModel.test.ts
  app/src/flatbuffers/models/nameRegistryEventModel.test.ts
  app/src/flatbuffers/models/types.ts
  app/src/flatbuffers/models/validations.test.ts
  app/src/flatbuffers/models/validations.ts
  app/src/flatbuffers/utils/ed25519.test.ts
  app/src/flatbuffers/utils/ed25519.ts
  app/src/flatbuffers/utils/eip712.test.ts
  app/src/hub.ts
  app/src/network/sync/multiPeerSyncEngine.test.ts
  app/src/network/sync/syncEngine.test.ts
  app/src/rpc/test/ampService.test.ts
  app/src/rpc/test/castService.test.ts
  app/src/rpc/test/eventService.test.ts
  app/src/rpc/test/reactionService.test.ts
  app/src/rpc/test/signerService.test.ts
  app/src/rpc/test/submitService.test.ts
  app/src/rpc/test/syncService.test.ts
  app/src/rpc/test/userDataService.test.ts
  app/src/rpc/test/verificationService.test.ts
  app/src/signers/ed25519Signer.test.ts
  app/src/signers/ed25519Signer.ts
  app/src/signers/eip712Signer.test.ts
  app/src/signers/eip712Signer.ts
  app/src/signers/index.ts
  app/src/signers/signer.ts
  app/src/storage/engine/index.test.ts
  app/src/storage/engine/mock.ts
  app/src/storage/engine/seed.ts
  app/src/storage/jobs/pruneMessagesJob.test.ts
  app/src/storage/jobs/revokeSignerJob.test.ts
  app/src/storage/stores/signerStore.test.ts
  app/src/storage/stores/userDataStore.test.ts
  app/src/storage/stores/verificationStore.test.ts
  app/src/utils/crypto.test.ts
  app/src/utils/crypto.ts
  packages/bytes/package.json
  packages/bytes/tsconfig.json
  packages/flatbuffers/package.json
Labels: chore

#391 fix: validate fid as part of validateMessage
  app/src/flatbuffers/models/validations.test.ts
  app/src/flatbuffers/models/validations.ts
Labels: bug

#386 docs: fix contributing link in app/README.md
  app/README.md
Labels: docs

#394 feat: @hub/js gRPC client
  app/src/rpc/test/ampService.test.ts
  app/src/rpc/test/castService.test.ts
  app/src/rpc/test/reactionService.test.ts
  packages/grpc/src/client.ts
  packages/grpc/src/requests/ampRequests.ts
  packages/grpc/src/requests/castRequests.ts
  packages/grpc/src/requests/reactionRequests.ts
  packages/js/src/builder.test.ts
  packages/js/src/builders.ts
  packages/js/src/client.test.ts
  packages/js/src/client.ts
  packages/js/src/index.ts
  packages/js/src/message.ts
  packages/js/src/types.ts
  packages/js/src/utils.test.ts
  packages/js/src/utils.ts
  packages/utils/src/validations.ts
Labels: feat

#397 fix: ensure BytesFactory does not produce padded array
  .gitignore
  packages/utils/src/factories.test.ts
  packages/utils/src/factories.ts
Labels: bug

#396 chore: add readme to @farcaster/js
  packages/js/README.md
  packages/js/package.json
  packages/js/src/index.ts
Labels: chore

#407 fix: make utils/bytes non-mutating
  packages/utils/src/bytes.test.ts
  packages/utils/src/bytes.ts
Labels: chore

#408 fix: force messages to be merged sequentially in stores
  apps/hub/src/rpc/test/concurrency.test.ts
  apps/hub/src/storage/engine/index.test.ts
  apps/hub/src/storage/engine/index.ts
  apps/hub/src/storage/stores/ampStore.ts
  apps/hub/src/storage/stores/castStore.ts
  apps/hub/src/storage/stores/reactionStore.ts
  apps/hub/src/storage/stores/sequentialMergeStore.test.ts
  apps/hub/src/storage/stores/sequentialMergeStore.ts
  apps/hub/src/storage/stores/signerStore.ts
  apps/hub/src/storage/stores/userDataStore.ts
  apps/hub/src/storage/stores/verificationStore.ts
Labels: chore

#410 feat: validate network in engine
  apps/hub/.config/hub.config.ts
  apps/hub/src/cli.ts
  apps/hub/src/eth/ethEventsProvider.test.ts
  apps/hub/src/eth/ethEventsProvider.ts
  apps/hub/src/hub.ts
  apps/hub/src/network/p2p/multiPeerGossip.test.ts
  apps/hub/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hub/src/network/sync/syncEngine.test.ts
  apps/hub/src/rpc/test/ampService.test.ts
  apps/hub/src/rpc/test/bulkService.test.ts
  apps/hub/src/rpc/test/castService.test.ts
  apps/hub/src/rpc/test/concurrency.test.ts
  apps/hub/src/rpc/test/eventService.test.ts
  apps/hub/src/rpc/test/reactionService.test.ts
  apps/hub/src/rpc/test/signerService.test.ts
  apps/hub/src/rpc/test/submitService.test.ts
  apps/hub/src/rpc/test/userDataService.test.ts
  apps/hub/src/rpc/test/verificationService.test.ts
  apps/hub/src/storage/engine/index.test.ts
  apps/hub/src/storage/engine/index.ts
  apps/hub/src/storage/jobs/pruneMessagesJob.test.ts
  apps/hub/src/storage/jobs/revokeSignerJob.test.ts
  apps/hub/src/storage/stores/sequentialMergeStore.test.ts
  apps/hub/src/storage/stores/userDataStore.test.ts
  apps/hub/src/test/mocks.ts
Labels: feat

#413 chore: bump package versions
  apps/hub/package.json
  packages/flatbuffers/package.json
  packages/grpc/package.json
  packages/js/package.json
  packages/utils/package.json
  yarn.lock
Labels: chore

#414 chore: add readme to all packages and update @farcaster/js docs with comments
  README.md
  packages/grpc/README.md
  packages/js/README.md
  packages/utils/README.md
Labels: chore

#415 fix: cli should parse network arg correctly
  apps/hub/src/cli.ts
Labels: bug

#419 feat: add message data builders
  packages/js/src/builder.test.ts
  packages/js/src/builders.test.ts
  packages/js/src/builders.ts
  packages/js/src/index.ts
  packages/js/src/signers.ts
  packages/js/src/types.ts
Labels: feat

#420 chore: bump packages version
  apps/hub/package.json
  packages/flatbuffers/package.json
  packages/grpc/package.json
  packages/js/package.json
  packages/utils/package.json
Labels: chore

#426 fix: Add required `--eth-rpc-url` flag to Docker image default command
  Dockerfile
Labels: bug

#428 feat: update stores to return error statuses for duplicates and conflicts
  apps/hub/src/flatbuffers/models/types.ts
  apps/hub/src/network/sync/syncEngine.ts
  apps/hub/src/rpc/server/index.ts
  apps/hub/src/rpc/test/concurrency.test.ts
  apps/hub/src/rpc/test/submitService.test.ts
  apps/hub/src/storage/db/rocksdb.ts
  apps/hub/src/storage/engine/index.test.ts
  apps/hub/src/storage/engine/index.ts
  apps/hub/src/storage/jobs/revokeSignerJob.ts
  apps/hub/src/storage/stores/ampStore.test.ts
  apps/hub/src/storage/stores/ampStore.ts
  apps/hub/src/storage/stores/castStore.test.ts
  apps/hub/src/storage/stores/castStore.ts
  apps/hub/src/storage/stores/reactionStore.test.ts
  apps/hub/src/storage/stores/reactionStore.ts
  apps/hub/src/storage/stores/sequentialMergeStore.test.ts
  apps/hub/src/storage/stores/sequentialMergeStore.ts
  apps/hub/src/storage/stores/signerStore.test.ts
  apps/hub/src/storage/stores/signerStore.ts
  apps/hub/src/storage/stores/storeEventHandler.ts
  apps/hub/src/storage/stores/userDataStore.test.ts
  apps/hub/src/storage/stores/userDataStore.ts
  apps/hub/src/storage/stores/verificationStore.test.ts
  apps/hub/src/storage/stores/verificationStore.ts
  packages/utils/src/bytes.test.ts
  packages/utils/src/bytes.ts
  packages/utils/src/errors.ts
  packages/utils/src/tsHash.test.ts
  packages/utils/src/tsHash.ts
Labels: feat

#433 chore: introduce changesets for package versioning and publishing
  .changeset/README.md
  .changeset/config.json
  apps/hub/CHANGELOG.md
  apps/hub/package.json
  package.json
  packages/flatbuffers/CHANGELOG.md
  packages/flatbuffers/package.json
  packages/grpc/CHANGELOG.md
  packages/grpc/package.json
  packages/js/CHANGELOG.md
  packages/js/package.json
  packages/utils/CHANGELOG.md
  packages/utils/package.json
  yarn.lock
Labels: docs, chore

#431 fix: validate inputs before serialization in @farcaster/js
  apps/hub/src/storage/stores/signerStore.test.ts
  packages/js/jest.config.ts
  packages/js/src/builders.test.ts
  packages/js/src/utils.test.ts
  packages/js/src/utils.ts
  packages/js/src/validations.ts
  packages/utils/src/crypto/eip712.test.ts
  packages/utils/src/factories.ts
  packages/utils/src/signers/eip712Signer.test.ts
  packages/utils/src/validations.test.ts
  packages/utils/src/validations.ts
Labels: bug

#436 chore: clean up unused syncThreshold test in syncEngine
  apps/hub/src/network/sync/syncEngine.test.ts
Labels: chore

#432 chore: refactor functions in `packages/*` to return HubResult
  .changeset/thirty-tools-drum.md
  apps/hub/src/hub.ts
  apps/hub/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hub/src/network/sync/syncEngine.test.ts
  apps/hub/src/network/sync/syncEngine.ts
  apps/hub/src/rpc/server/serviceImplementations/syncImplementation.ts
  apps/hub/src/storage/stores/ampStore.test.ts
  apps/hub/src/storage/stores/ampStore.ts
  apps/hub/src/storage/stores/castStore.test.ts
  apps/hub/src/storage/stores/castStore.ts
  apps/hub/src/storage/stores/reactionStore.test.ts
  apps/hub/src/storage/stores/reactionStore.ts
  apps/hub/src/storage/stores/signerStore.test.ts
  apps/hub/src/storage/stores/userDataStore.test.ts
  apps/hub/src/storage/stores/verificationStore.test.ts
  packages/js/README.md
  packages/js/src/builders.test.ts
  packages/js/src/builders.ts
  packages/utils/src/bytes.test.ts
  packages/utils/src/bytes.ts
  packages/utils/src/factories.test.ts
  packages/utils/src/factories.ts
  packages/utils/src/signers/ed25519Signer.test.ts
  packages/utils/src/signers/ed25519Signer.ts
  packages/utils/src/signers/eip712Signer.test.ts
  packages/utils/src/signers/eip712Signer.ts
  packages/utils/src/time.test.ts
  packages/utils/src/time.ts
  packages/utils/src/tsHash.test.ts
  packages/utils/src/validations.test.ts
  packages/utils/src/validations.ts
Labels: chore

#437 chore: Cleanup command classes
  apps/hub/src/console/castsCommand.ts
  apps/hub/src/console/console.ts
  apps/hub/src/console/infoCommand.ts
  apps/hub/src/console/syncTrieCommand.ts
Labels: chore

#429 feat: add support for /subscribe gRPC method in @farcaster/js package
  .changeset/tall-mirrors-smile.md
  apps/hub/src/rpc/server/serviceImplementations/eventImplementation.ts
  apps/hub/src/rpc/test/eventService.test.ts
  packages/flatbuffers/src/generated/rpc_generated.ts
  packages/flatbuffers/src/schemas/rpc.fbs
  packages/grpc/src/client.ts
  packages/grpc/src/requests/eventRequests.test.ts
  packages/grpc/src/requests/eventRequests.ts
  packages/grpc/src/requests/index.ts
  packages/js/src/client.ts
  packages/js/src/types.ts
  packages/js/src/utils.test.ts
  packages/js/src/utils.ts
  packages/utils/src/factories.test.ts
  packages/utils/src/factories.ts
Labels: feat

#439 fix: Display objects (instead of string) in console
  apps/hub/package.json
  apps/hub/src/cli.ts
  apps/hub/src/console/castsCommand.ts
  apps/hub/src/console/console.ts
  apps/hub/src/console/infoCommand.ts
  apps/hub/src/console/syncTrieCommand.ts
  apps/hub/src/storage/engine/index.test.ts
  apps/hub/src/storage/engine/index.ts
  apps/hub/src/test/perf/bench.ts
  apps/hub/src/test/perf/flatbuffers/bench.ts
  apps/hub/src/test/perf/flatbuffers/playback.ts
  apps/hub/src/test/perf/flatbuffers/scenario.ts
  apps/hub/src/test/perf/flatbuffers/setup.ts
  apps/hub/src/test/perf/playback.ts
  apps/hub/src/test/perf/scenario.ts
  apps/hub/src/test/perf/setup.ts
  apps/hub/src/test/perf/verify.ts
  apps/hub/src/utils/command.ts
Labels: chore

#442 chore: run changeset version
  .changeset/tall-mirrors-smile.md
  .changeset/thirty-tools-drum.md
  apps/hub/CHANGELOG.md
  apps/hub/package.json
  packages/flatbuffers/CHANGELOG.md
  packages/flatbuffers/package.json
  packages/grpc/CHANGELOG.md
  packages/grpc/package.json
  packages/js/CHANGELOG.md
  packages/js/package.json
  packages/utils/CHANGELOG.md
  packages/utils/package.json
Labels: chore

#448 feat: Protobuf and RPC definitions for Sync, Gossip, IdRegistry and HubState
  packages/protobufs/src/generated/gossip.ts
  packages/protobufs/src/generated/hub_state.ts
  packages/protobufs/src/generated/id_registry_event.ts
  packages/protobufs/src/generated/rpc.ts
  packages/protobufs/src/schemas/gossip.proto
  packages/protobufs/src/schemas/hub_state.proto
  packages/protobufs/src/schemas/id_registry_event.proto
  packages/protobufs/src/schemas/rpc.proto
Labels: feat

#452 feat: protobufs cast store
  apps/protohub/src/storage/db/message.ts
  apps/protohub/src/storage/engine/index.test.ts
  apps/protohub/src/storage/engine/index.ts
  apps/protohub/src/storage/stores/castStore.test.ts
  apps/protohub/src/storage/stores/castStore.ts
  apps/protohub/src/storage/stores/reactionStore.ts
Labels: feat

#460 fix: nameRegistryEvent test using duplicate db name
  apps/protohub/src/storage/db/nameRegistryEvent.test.ts
Labels: bug

#464 fix: enforce fixed size for protobuf addresses and hashes and fix flaky test
  .changeset/six-melons-tease.md
  apps/protohub/src/storage/jobs/revokeSignerJob.test.ts
  packages/protoutils/src/crypto/ed25519.test.ts
  packages/protoutils/src/crypto/eip712.test.ts
  packages/protoutils/src/factories.ts
  packages/protoutils/src/signers/ed25519Signer.test.ts
  packages/protoutils/src/signers/eip712Signer.test.ts
  packages/protoutils/src/validations.test.ts
  packages/protoutils/src/validations.ts
Labels: bug

#469 feat: update js package to use protobufs
  .changeset/tiny-experts-check.md
  apps/protohub/src/console/castsCommand.ts
  apps/protohub/src/console/console.ts
  apps/protohub/src/console/infoCommand.ts
  apps/protohub/src/console/syncTrieCommand.ts
  apps/protohub/src/hub.ts
  apps/protohub/src/network/sync/syncEngine.test.ts
  apps/protohub/src/network/sync/syncEngine.ts
  apps/protohub/src/rpc/server/index.ts
  apps/protohub/src/rpc/server/test/castService.test.ts
  apps/protohub/src/rpc/server/test/reactionService.test.ts
  apps/protohub/src/rpc/server/test/signerService.test.ts
  apps/protohub/src/rpc/server/test/verificationService.test.ts
  packages/js/package.json
  packages/js/src/builders.test.ts
  packages/js/src/builders.ts
  packages/js/src/client.ts
  packages/js/src/index.ts
  packages/js/src/signers.ts
  packages/js/src/types.ts
  packages/js/src/utils.test.ts
  packages/js/src/utils.ts
  packages/js/src/validations.ts
  packages/protobufs/package.json
  packages/protobufs/src/generated/rpc.ts
  packages/protobufs/src/schemas/rpc.proto
  packages/protoutils/src/client.ts
  packages/protoutils/src/index.ts
Labels: feat

#446 docs: update documentation to match code
  CONTRIBUTING.md
Labels: docs

#477 chore: port ethEventsProvider to protobufs
  apps/protohub/src/eth/abis.ts
  apps/protohub/src/eth/ethEventsProvider.test.ts
  apps/protohub/src/eth/ethEventsProvider.ts
  apps/protohub/src/eth/utils.test.ts
  apps/protohub/src/eth/utils.ts
  apps/protohub/src/hub.ts
Labels: chore

#478 chore: port hub state to protobufs
  apps/protohub/src/eth/ethEventsProvider.ts
  apps/protohub/src/hub.ts
  apps/protohub/src/storage/db/hubState.ts
  apps/protohub/src/utils/logger.ts
  packages/protobufs/src/schemas/hub_state.proto
Labels: chore

#481 chore: run changeset version
  .changeset/clean-hats-march.md
  .changeset/clever-trains-shake.md
  .changeset/dry-vans-drop.md
  .changeset/early-fireants-approve.md
  .changeset/honest-ghosts-cover.md
  .changeset/six-melons-tease.md
  .changeset/tiny-experts-check.md
  apps/hub/CHANGELOG.md
  apps/hub/package.json
  packages/js/CHANGELOG.md
  packages/js/package.json
  packages/protobufs/CHANGELOG.md
  packages/protobufs/package.json
  packages/utils/CHANGELOG.md
  packages/utils/package.json
Labels: chore

#484 chore: bump versions
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/hubble/src/storage/db/rocksdb.ts
  apps/hubble/src/storage/jobs/revokeSignerJob.ts
  apps/hubble/src/storage/stores/ampStore.test.ts
  apps/hubble/src/storage/stores/castStore.test.ts
  apps/hubble/src/storage/stores/reactionStore.test.ts
  apps/hubble/src/storage/stores/signerStore.test.ts
  apps/hubble/src/storage/stores/userDataStore.test.ts
  apps/hubble/src/storage/stores/verificationStore.test.ts
  packages/js/CHANGELOG.md
  packages/js/package.json
  packages/protobufs/CHANGELOG.md
  packages/protobufs/package.json
  packages/protobufs/tsup.config.ts
  packages/utils/CHANGELOG.md
  packages/utils/package.json
  packages/utils/src/bytes.test.ts
  packages/utils/src/bytes.ts
Labels: chore

#487 refactor: improve documentation in networking and cleanup some error handling
  apps/hubble/src/network/p2p/connectionFilter.ts
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/p2p/protocol.ts
  apps/hubble/src/network/sync/merkleTrie.ts
  apps/hubble/src/network/sync/syncId.ts
  apps/hubble/src/network/sync/trieNode.ts
Labels: docs, chore
