Repository farcasterxyz/hub-monorepo, pull requests merged in 2023-07, with the labels that each got.

#1065 chore: Release 1.3.3
  .changeset/pink-ears-learn.md
  .changeset/seven-adults-sing.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#1066 fix: Update adityapk00 key
  apps/hubble/src/allowedPeers.mainnet.ts
Labels: t-chore

#1067 fix: Better error if hub config is misspecified
  .changeset/six-eyes-drive.md
  apps/hubble/src/cli.ts
Labels: t-devex

#1072 chore: update peer ids
  apps/hubble/src/allowedPeers.mainnet.ts
Labels: t-chore

#1075 chore: run rome format --write on examples in packages
  packages/hub-nodejs/examples/chron-feed/index.ts
  packages/hub-nodejs/examples/make-cast/index.ts
  packages/hub-nodejs/examples/replicate-data-postgres/db.ts
  packages/hub-nodejs/examples/replicate-data-postgres/hubReplicator.ts
  packages/hub-nodejs/examples/replicate-data-postgres/hubSubscriber.ts
  packages/hub-nodejs/examples/replicate-data-postgres/index.ts
  packages/hub-nodejs/examples/replicate-data-postgres/log.ts
  packages/hub-nodejs/examples/replicate-data-postgres/migrations/001_initial_migration.ts
  packages/hub-nodejs/examples/replicate-data-postgres/util.ts
  packages/hub-nodejs/examples/write-data/index.ts
  packages/hub-web/examples/chron-feed/index.ts
Labels: t-chore

#1077 chore: prepare for rome migration
  apps/hubble/src/allowedPeers.mainnet.ts
  apps/hubble/src/cli.ts
  apps/hubble/src/console/console.ts
  apps/hubble/src/console/rpcClientCommand.ts
  apps/hubble/src/eth/fnameRegistryEventsProvider.ts
  apps/hubble/src/eth/watchContractEvent.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/p2p/connectionFilter.test.ts
  apps/hubble/src/network/p2p/connectionFilter.ts
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/sync/mock.ts
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/network/sync/syncEnginePerf.test.ts
  apps/hubble/src/network/sync/trieNode.test.ts
  apps/hubble/src/rocksdb.d.ts
  apps/hubble/src/rpc/bufferedStreamWriter.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/eventService.test.ts
  apps/hubble/src/rpc/test/rpcAuth.test.ts
  apps/hubble/src/storage/db/nameRegistryEvent.ts
  apps/hubble/src/storage/db/rocksdb.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/engine/seed.ts
  apps/hubble/src/storage/jobs/revokeMessagesBySignerJob.ts
  apps/hubble/src/storage/jobs/updateNameRegistryEventExpiryJob.ts
  apps/hubble/src/storage/stores/castStore.ts
  apps/hubble/src/storage/stores/linkStore.ts
  apps/hubble/src/storage/stores/reactionStore.ts
  apps/hubble/src/storage/stores/store.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
  apps/hubble/src/test/bench/merkleTrie.ts
  apps/hubble/src/test/bench/syncEngine.ts
  apps/hubble/src/test/bench/utils.ts
  apps/hubble/src/test/e2e/gossipNetwork.test.ts
  apps/hubble/src/test/utils.ts
  apps/hubble/src/utils/p2p.ts
  apps/hubble/src/utils/versions.test.ts
  packages/core/src/bytes.ts
  packages/core/src/errors.ts
  packages/core/src/validations.test.ts
  packages/core/src/validations.ts
  packages/hub-nodejs/examples/chron-feed/index.ts
  packages/hub-nodejs/examples/replicate-data-postgres/db.ts
  packages/hub-nodejs/examples/replicate-data-postgres/hubReplicator.ts
  packages/hub-nodejs/examples/replicate-data-postgres/hubSubscriber.ts
  packages/hub-nodejs/examples/replicate-data-postgres/migrations/001_initial_migration.ts
  packages/hub-nodejs/examples/replicate-data-postgres/util.ts
  packages/hub-nodejs/src/client.ts
  packages/hub-web/examples/chron-feed/index.ts
  packages/hub-web/src/client.ts
Labels: t-chore

#1085 Add rocksDB storage profiling
  .changeset/twenty-chairs-switch.md
  apps/hubble/package.json
  apps/hubble/src/cli.ts
  apps/hubble/src/profile.ts
Labels: t-devex

#1087 fix: Add overheads to storage profile
  apps/hubble/src/profile.ts
Labels: t-devex

#1088 chore: Include bad_request.prunable in list of INVALID_ARGUMENT errors
  .changeset/fast-olives-promise.md
  apps/hubble/src/rpc/server.ts
Labels: t-chore

#1099 chore: Remove hubs from allowed peers list running old versions
  apps/hubble/src/allowedPeers.mainnet.ts
Labels: t-chore

#1100 chore: Remove one more old hub
  apps/hubble/src/allowedPeers.mainnet.ts
Labels: t-chore

#1047 fix: Display correct app version when run in Docker container
  .changeset/early-swans-clean.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/package.json
  apps/hubble/tsconfig.json
  package.json
  yarn.lock
Labels: t-bug

#1102 fix: Prevent connecting to peers not in allowed peer list
  .changeset/angry-lizards-hammer.md
  apps/hubble/src/hubble.ts
Labels: t-bug

#1101 feat: Support ENS names in the hub
  .changeset/rotten-keys-smell.md
  apps/hubble/README.md
  apps/hubble/docker-compose.yml
  apps/hubble/src/cli.ts
  apps/hubble/src/defaultConfig.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/userDataService.test.ts
  apps/hubble/src/storage/db/message.ts
  apps/hubble/src/storage/db/nameRegistryEvent.ts
  apps/hubble/src/storage/db/types.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/storageCache.ts
  apps/hubble/src/storage/stores/store.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
  apps/hubble/src/storage/stores/userDataStore.ts
  apps/hubble/src/storage/stores/usernameProofStore.test.ts
  apps/hubble/src/storage/stores/usernameProofStore.ts
  docker-compose-multinode.yml
  packages/core/src/factories.ts
  packages/core/src/protobufs/generated/hub_event.ts
  packages/core/src/protobufs/generated/hub_state.ts
  packages/core/src/protobufs/generated/id_registry_event.ts
  packages/core/src/protobufs/generated/job.ts
  packages/core/src/protobufs/generated/message.ts
  packages/core/src/protobufs/generated/name_registry_event.ts
  packages/core/src/protobufs/generated/request_response.ts
  packages/core/src/protobufs/generated/sync_trie.ts
  packages/core/src/protobufs/generated/username_proof.ts
  packages/core/src/protobufs/typeguards.ts
  packages/core/src/protobufs/types.ts
  packages/core/src/validations.test.ts
  packages/core/src/validations.ts
  packages/hub-nodejs/src/generated/hub_event.ts
  packages/hub-nodejs/src/generated/id_registry_event.ts
  packages/hub-nodejs/src/generated/message.ts
  packages/hub-nodejs/src/generated/name_registry_event.ts
  packages/hub-nodejs/src/generated/request_response.ts
  packages/hub-nodejs/src/generated/rpc.ts
  packages/hub-nodejs/src/generated/username_proof.ts
  packages/hub-web/src/generated/hub_event.ts
  packages/hub-web/src/generated/id_registry_event.ts
  packages/hub-web/src/generated/message.ts
  packages/hub-web/src/generated/name_registry_event.ts
  packages/hub-web/src/generated/request_response.ts
  packages/hub-web/src/generated/rpc.ts
  packages/hub-web/src/generated/username_proof.ts
  protobufs/schemas/hub_event.proto
  protobufs/schemas/message.proto
  protobufs/schemas/request_response.proto
  protobufs/schemas/rpc.proto
  protobufs/schemas/username_proof.proto
  rome.json
Labels: t-feat

#1103 fix: Correct allowed peer IDs behavior
  apps/hubble/src/hubble.ts
Labels: t-bug

#1098 perf: Add a Sync Profiler
  .changeset/tidy-roses-crash.md
  apps/hubble/src/cli.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/network/sync/syncEngineProfiler.ts
  apps/hubble/src/profile.ts
Labels: t-perf

#1096 [WIP] perf: Prevent un-necessary network calls when syncing
  .changeset/forty-onions-grin.md
  apps/hubble/src/network/sync/merkleTrie.ts
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
Labels: t-perf

#1108 chore: Rename UserDataType.FNAME to USERNAME
  .changeset/violet-radios-beam.md
  apps/hubble/src/rpc/test/userDataService.test.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/userDataStore.test.ts
  packages/core/src/factories.ts
  packages/core/src/protobufs/generated/message.ts
  packages/core/src/validations.test.ts
  packages/core/src/validations.ts
  packages/hub-nodejs/docs/Messages.md
  packages/hub-nodejs/examples/chron-feed/index.ts
  packages/hub-nodejs/src/generated/message.ts
  packages/hub-web/examples/chron-feed/index.ts
  packages/hub-web/src/generated/message.ts
  protobufs/docs/message.md
  protobufs/schemas/message.proto
Labels: t-chore

#1109 chore: Release 1.3.4
  .changeset/angry-lizards-hammer.md
  .changeset/early-swans-clean.md
  .changeset/fast-olives-promise.md
  .changeset/flat-trainers-hide.md
  .changeset/forty-onions-grin.md
  .changeset/perfect-baboons-visit.md
  .changeset/plenty-trainers-raise.md
  .changeset/rotten-keys-smell.md
  .changeset/six-eyes-drive.md
  .changeset/tidy-roses-crash.md
  .changeset/twenty-chairs-switch.md
  .changeset/violet-radios-beam.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#1107 fix: Improve open iterator logging
  .changeset/stupid-rice-laugh.md
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/storage/db/rocksdb.ts
Labels: t-devex

#1116 chore: hard fail on missing rpc urls
  .changeset/dull-onions-sniff.md
  .github/workflows/ci.yml
  apps/hubble/src/hubble.ts
Labels: t-chore

#1052 feat: storage registry support
  .changeset/shiny-rivers-hang.md
  apps/hubble/src/cli.ts
  apps/hubble/src/defaultConfig.ts
  apps/hubble/src/eth/abis.ts
  apps/hubble/src/eth/l2EventsProvider.test.ts
  apps/hubble/src/eth/l2EventsProvider.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/rpc/adminServer.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/storage/db/storageRegistryEvent.test.ts
  apps/hubble/src/storage/db/storageRegistryEvent.ts
  apps/hubble/src/storage/db/types.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/storageEventStore.test.ts
  apps/hubble/src/storage/stores/storageEventStore.ts
  apps/hubble/src/test/constants.ts
  apps/hubble/src/test/mocks.ts
  apps/hubble/src/test/utils.ts
  apps/hubble/src/utils/logger.ts
  packages/core/src/factories.test.ts
  packages/core/src/factories.ts
  packages/core/src/protobufs/generated/hub_event.ts
  packages/core/src/protobufs/generated/request_response.ts
  packages/core/src/protobufs/generated/storage_event.ts
  packages/core/src/protobufs/index.ts
  packages/core/src/protobufs/typeguards.ts
  packages/core/src/protobufs/types.ts
  packages/hub-nodejs/src/generated/hub_event.ts
  packages/hub-nodejs/src/generated/request_response.ts
  packages/hub-nodejs/src/generated/rpc.ts
  packages/hub-nodejs/src/generated/storage_event.ts
  packages/hub-web/src/generated/hub_event.ts
  packages/hub-web/src/generated/request_response.ts
  packages/hub-web/src/generated/rpc.ts
  packages/hub-web/src/generated/storage_event.ts
  protobufs/schemas/hub_event.proto
  protobufs/schemas/request_response.proto
  protobufs/schemas/rpc.proto
  protobufs/schemas/storage_event.proto
Labels: t-feat

#1125 perf: Get exact diff nodes during incremental sync
  .changeset/tiny-chicken-marry.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/merkleTrie.ts
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
Labels: t-perf

#1120 fix: Throw error if unable to fetch fname server signature
  .changeset/four-beds-prove.md
  apps/hubble/src/eth/fnameRegistryEventsProvider.test.ts
  apps/hubble/src/eth/fnameRegistryEventsProvider.ts
Labels: t-bug

#1132 fix: Only revoke the username if the name proof matches
  .changeset/selfish-cougars-bathe.md
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
Labels: t-bug

#1123 fix: Adjust chunk size to 1000
  .changeset/slow-roses-dream.md
  apps/hubble/src/eth/ethEventsProvider.ts
  apps/hubble/src/eth/l2EventsProvider.ts
Labels: t-bug

#1105 chore: remove obsolete ethers dependency from hub-nodejs
  .changeset/blue-spoons-double.md
  packages/hub-nodejs/package.json
  yarn.lock
Labels: t-chore, dependencies

#1134 fix: Add managed Iterators
  .changeset/modern-spies-study.md
  apps/hubble/src/profile.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/storage/db/message.ts
  apps/hubble/src/storage/db/rocksdb.test.ts
  apps/hubble/src/storage/db/rocksdb.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/storageEventStore.test.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
Labels: t-bug

#1135 chore: Decrease block confirmations from 6 to 3 for L1 ETH events
  .changeset/hot-numbers-help.md
  apps/hubble/src/eth/ethEventsProvider.ts
Labels: t-chore

#1133 feat: support direct peering
  .changeset/many-games-exist.md
  apps/hubble/src/cli.ts
  apps/hubble/src/defaultConfig.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/p2p/gossipNode.ts
Labels: t-feat, t-chore

#1138 chore: Automate Docker Hub publishing
  .github/workflows/publish.yml
  scripts/publish-image.sh
Labels: t-chore

#1141 docs(hubble): port documentation to vitepress site
  .gitignore
  apps/hubble/www/docs/.vitepress/config.ts
  apps/hubble/www/docs/docs/api.md
  apps/hubble/www/docs/docs/architecture.md
  apps/hubble/www/docs/docs/cli.md
  apps/hubble/www/docs/docs/messages.md
  apps/hubble/www/docs/index.md
  apps/hubble/www/docs/installation/docker.md
  apps/hubble/www/docs/installation/source.md
  apps/hubble/www/docs/installation/upgrades.md
  apps/hubble/www/docs/intro/hubble.md
  apps/hubble/www/docs/intro/install.md
  apps/hubble/www/docs/intro/introduction.md
  apps/hubble/www/docs/intro/networks.md
  apps/hubble/www/docs/intro/tutorials.md
  apps/hubble/www/docs/syncing/mainnet.md
  apps/hubble/www/docs/syncing/testnet.md
  apps/hubble/www/docs/syncing/troubleshooting.md
Labels: t-docs

#1143 chore: release hubble v1.4.1 and new package versions
  .changeset/blue-spoons-double.md
  .changeset/four-beds-prove.md
  .changeset/hot-numbers-help.md
  .changeset/many-games-exist.md
  .changeset/modern-spies-study.md
  .changeset/selfish-cougars-bathe.md
  .changeset/shiny-rivers-hang.md
  .changeset/slow-roses-dream.md
  .changeset/tasty-countries-jump.md
  .changeset/tiny-chicken-marry.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#1144 docs: update hubble documentation
  README.md
  apps/hubble/README.md
Labels: t-docs

#1148 docs(hubble): update api, event and message docs
  .gitignore
  apps/hubble/www/docs/.vitepress/config.ts
  apps/hubble/www/docs/docs/api.md
  apps/hubble/www/docs/docs/events.md
  apps/hubble/www/docs/docs/messages.md
  apps/hubble/www/docs/intro/install.md
  protobufs/README.md
Labels: t-docs

#1150 docs: add documentation requirement and instructions to pr template
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: t-docs

#1151 fix: fix testnet defaulting to no allowed peers
  apps/hubble/src/hubble.ts
Labels: t-bug

#1153 chore(hubble) add vercel analytics to www
  apps/hubble/www/docs/.vitepress/config.ts
Labels: t-chore

#1155 chore(hubble): release v1.4.2
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
Labels: t-chore

#1161 fix: Fix typing for merge username proof events
  .changeset/moody-cups-work.md
  packages/core/src/protobufs/types.ts
Labels: t-bug

#1159 feat: validateOrRevoke fid-by-fid
  .changeset/little-comics-exist.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/profile.ts
  apps/hubble/src/storage/db/rocksdb.ts
  apps/hubble/src/storage/jobs/validateOrRevokeMessagesJob.ts
  apps/hubble/src/storage/stores/store.ts
Labels: t-feat

#1164 fix: fix username proof timestamp validation + add builders for UsernameProofData and UsernameProofMessage
  .changeset/early-trains-shake.md
  apps/hubble/src/storage/engine/index.test.ts
  packages/core/src/builders.test.ts
  packages/core/src/builders.ts
  packages/core/src/factories.ts
  packages/core/src/signers/testUtils.ts
  packages/core/src/validations.ts
Labels: t-chore

#1171 feat: Use a web based allowlist
  .changeset/spicy-radios-jump.md
  apps/hubble/src/cli.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/p2p/connectionFilter.ts
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/network/utils/networkConfig.test.ts
  apps/hubble/src/network/utils/networkConfig.ts
  apps/hubble/src/storage/jobs/updateNetworkConfigJob.ts
Labels: t-devex

#1173 chore: release 1.4.3
  .changeset/early-trains-shake.md
  .changeset/large-items-rescue.md
  .changeset/little-comics-exist.md
  .changeset/moody-cups-work.md
  .changeset/nervous-rivers-dance.md
  .changeset/silver-dolls-accept.md
  .changeset/spicy-radios-jump.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
Labels: t-chore

#1172 feat: validate name proofs against fid instead of custody address
  .changeset/khaki-clouds-attack.md
  apps/hubble/src/rpc/test/userDataService.test.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
Labels: t-feat

#1177 feat: revoke signers 1hr after custody event
  .changeset/fifty-feet-punch.md
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/jobs/revokeMessagesBySignerJob.ts
Labels: t-feat

#1165 feat: Adds support for storage/logging if would be pruned
  .changeset/dull-glasses-admire.md
  apps/hubble/src/storage/stores/storageCache.test.ts
  apps/hubble/src/storage/stores/storageCache.ts
  apps/hubble/src/storage/stores/storageEventStore.ts
  apps/hubble/src/storage/stores/store.test.ts
  apps/hubble/src/storage/stores/store.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
  packages/core/src/factories.ts
Labels: t-feat

#1180 feat: Scale validation workers by number of CPUs
  .changeset/thirty-radios-search.md
  apps/hubble/src/cli.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/network/sync/syncEngineProfiler.ts
  apps/hubble/src/profile/profile.ts
  apps/hubble/src/profile/rpcProfile.ts
  apps/hubble/src/storage/engine/index.ts
Labels: t-perf

#1186 chore: Adjust rent-based prune warning to debug for now
  .changeset/tiny-bears-peel.md
  apps/hubble/src/storage/stores/store.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
Labels: t-chore

#1192 fix: Bugfix where testnet would restrict peers
  .changeset/breezy-swans-brake.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/utils/networkConfig.ts
Labels: t-bug

#1195 fix: Fetch network config only on mainnet
  .changeset/empty-eggs-cough.md
  apps/hubble/src/hubble.ts
Labels: t-chore

#1196 test: Add rust tests
  packages/core/src/addon/src/lib.rs
  packages/core/src/rustfunctions.test.ts
Labels: t-chore
