Repository farcasterxyz/hub-monorepo, pull requests merged in 2023-04, with the labels that each got.

#797 feat: add hub-web package to only depend on grpc-web
  .changeset/chatty-singers-relate.md
  apps/hubble/envoy/README.md
  apps/hubble/envoy/envoy-start.sh
  apps/hubble/envoy/envoy.yaml
  apps/hubble/envoy/install-docker.sh
  envoy/README.md
  envoy/envoy-start.sh
  envoy/envoy.yaml
  envoy/install-docker.sh
  packages/hub-web/.eslintrc.cjs
  packages/hub-web/README.md
  packages/hub-web/package.json
  packages/hub-web/src/client.ts
  packages/hub-web/src/generated/hub_event.ts
  packages/hub-web/src/generated/id_registry_event.ts
  packages/hub-web/src/generated/message.ts
  packages/hub-web/src/generated/name_registry_event.ts
  packages/hub-web/src/generated/rpc.ts
  packages/hub-web/src/index.ts
  packages/hub-web/tsconfig.json
  packages/hub-web/tsup.config.ts
Labels: feat

#795 feat: expire hubs
  apps/hubble/src/hubble.ts
  apps/hubble/src/storage/jobs/checkFarcasterVersionJob.ts
  apps/hubble/src/utils/versions.ts
  yarn.lock
Labels: feat

#801 feat: add validate or revoke messages cleanup job
  apps/hubble/src/hubble.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/jobs/validateOrRevokeMessagesJob.ts
Labels: feat

#805 chore: set codecov to ignore generated files
  codecov.yml
Labels: chore

#806 chore: fix codecov.yml
  codecov.yml
Labels: chore

#790 docs: update docs to close() grpc connection
  .changeset/thick-tips-invite.md
  apps/hubble/src/network/p2p/gossipNode.test.ts
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/rpc/test/bulkService.test.ts
  apps/hubble/src/rpc/test/castService.test.ts
  apps/hubble/src/rpc/test/concurrency.test.ts
  apps/hubble/src/rpc/test/reactionService.test.ts
  apps/hubble/src/rpc/test/rpcAuth.test.ts
  apps/hubble/src/rpc/test/signerService.test.ts
  apps/hubble/src/rpc/test/submitService.test.ts
  apps/hubble/src/rpc/test/userDataService.test.ts
  apps/hubble/src/rpc/test/verificationService.test.ts
  apps/hubble/src/utils/periodicTestDataJob.ts
  packages/hub-nodejs/README.md
  packages/hub-nodejs/docs/Client.md
  packages/hub-nodejs/examples/chron-feed/index.ts
  packages/hub-nodejs/examples/make-cast/index.ts
  packages/hub-nodejs/examples/write-data/index.ts
  packages/utils/src/client.ts
Labels: docs

#808 feat: ignore hubs below minimum version for sync
  .changeset/tasty-grapes-decide.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/utils/versions.test.ts
  apps/hubble/src/utils/versions.ts
  packages/protobufs/src/generated/gossip.ts
  packages/protobufs/src/schemas/gossip.proto
Labels: feat

#520 chore: Test gRPC server is running in Docker image
  .github/workflows/ci.yml
Labels: chore

#815 chore: Remove unnecessary flag for smoke test
  .github/workflows/ci.yml
Labels: chore

#811 feat: wrap hub-web client to provide consistent APIs with hub-nodejs
  .changeset/young-ravens-join.md
  envoy/README.md
  envoy/envoy-start.sh
  envoy/envoy.yaml
  envoy/install-docker.sh
  packages/hub-web/README.md
  packages/hub-web/package.json
  packages/hub-web/src/client.ts
  packages/hub-web/src/generated/rpc.ts
Labels: feat

#816 chore: run changeset version
  .changeset/beige-lemons-float.md
  .changeset/big-apricots-clean.md
  .changeset/chatty-singers-relate.md
  .changeset/chilled-cats-wave.md
  .changeset/honest-news-own.md
  .changeset/kind-wasps-fly.md
  .changeset/light-hounds-arrive.md
  .changeset/little-bats-lick.md
  .changeset/pretty-llamas-grow.md
  .changeset/quick-donuts-shave.md
  .changeset/tasty-grapes-decide.md
  .changeset/thick-tips-invite.md
  .changeset/young-ravens-join.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
  packages/protobufs/CHANGELOG.md
  packages/protobufs/package.json
  packages/utils/CHANGELOG.md
  packages/utils/package.json
Labels: chore

#820 chore: run changeset version
  .changeset/gold-pots-double.md
  .changeset/new-paws-change.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: chore

#821 chore: enable getSSLHubRpcClient
  .changeset/neat-dingos-fry.md
  packages/hub-web/src/client.ts
Labels: chore

#824 fix: Fix build due to merge conflict with main
  apps/hubble/src/storage/jobs/gossipContactInfoJob.test.ts
  apps/hubble/src/storage/jobs/gossipContactInfoJob.ts
Labels: bug

#822 chore: export getAuthMetadata & getHubRpcClient
  .changeset/three-zoos-train.md
  packages/hub-web/README.md
  packages/hub-web/src/client.ts
Labels: chore

#827 chore: fiix error code for no connection
  .changeset/stale-berries-fold.md
  packages/hub-web/src/client.ts
Labels: chore

#828 fix: add grpc error code as fallback
  .changeset/twenty-beans-draw.md
  packages/hub-web/src/client.ts
Labels: bug

#829 update readme
  packages/hub-web/README.md
Labels: docs

#826 chore: run changeset version
  .changeset/neat-dingos-fry.md
  .changeset/three-zoos-train.md
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: chore

#832 fix: map grpc error codes to hub error codes
  .changeset/light-gifts-remember.md
  packages/hub-web/src/client.ts
Labels: bug

#833 fix: handle invalid version strings
  apps/hubble/src/hubble.ts
  apps/hubble/src/utils/versions.test.ts
  apps/hubble/src/utils/versions.ts
Labels: bug

#837 feat: ensure hub networks match when syncing with peers
  .changeset/eighty-buckets-shout.md
  apps/hubble/src/hubble.ts
  packages/core/src/protobufs/generated/gossip.ts
  protobufs/schemas/gossip.proto
Labels: feat

#839 chore: run changeset version (apr 6 2023)
  .changeset/eighty-buckets-shout.md
  .changeset/light-gifts-remember.md
  .changeset/stale-berries-fold.md
  .changeset/twenty-beans-draw.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: chore

#842 docs: minor fix to root readme
  README.md
Labels: docs

#836 chore: Add test to ensure verification and claim must have same network
  apps/hubble/src/storage/engine/index.test.ts
  packages/core/src/factories.ts
Labels: chore

#830 feat: make commit lock queue size and timeout configurable
  .changeset/few-kids-suffer.md
  apps/hubble/.config/hub.config.ts
  apps/hubble/src/cli.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/syncEngine.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/castStore.test.ts
  apps/hubble/src/storage/stores/reactionStore.test.ts
  apps/hubble/src/storage/stores/signerStore.test.ts
  apps/hubble/src/storage/stores/storageCache.test.ts
  apps/hubble/src/storage/stores/storageCache.ts
  apps/hubble/src/storage/stores/storeEventHandler.test.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
  apps/hubble/src/storage/stores/userDataStore.test.ts
  apps/hubble/src/storage/stores/verificationStore.test.ts
  apps/hubble/src/test/bench/syncEngine.ts
Labels: t-feat

#853 chore: upgrade turbo and add protoc command
  package.json
  turbo.json
  yarn.lock
Labels: t-chore

#859 chore: changeset version and publish @farcaster/hub-web
  .changeset/breezy-ducks-admire.md
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#858 chore: add peer ids for trusted mainnet hubs from users
  apps/hubble/src/allowedPeers.mainnet.ts
Labels: t-chore

#862 add release-packages workflow
  .github/workflows/release-packages.yml
  package.json
Labels: t-chore

#834 docs: update examples for making casts and writing data
  packages/hub-nodejs/examples/make-cast/index.ts
  packages/hub-nodejs/examples/write-data/index.ts
Labels: t-docs

#865 chore: log sync status for better visibility
  .changeset/wicked-planets-walk.md
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/test/bench/syncEngine.ts
Labels: t-chore

#868 chore: Add mainnet peer for sanjay
  apps/hubble/src/allowedPeers.mainnet.ts
Labels: t-chore

#861 feat: Include network id in gossip topics to keep networks isolated
  .changeset/spotty-dryers-kneel.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/p2p/protocol.ts
  apps/hubble/src/network/utils/factories.ts
  apps/hubble/src/test/e2e/gossipNetwork.test.ts
Labels: t-feat

#870 chore: add release.yml github action
  .github/workflows/release.yml
Labels: t-chore

#878 chore: re-organize sync engine to use submitMessage rather than mergeMessage
  .changeset/twelve-files-push.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/p2p/gossipNode.test.ts
  apps/hubble/src/network/sync/merkleTrie.ts
  apps/hubble/src/network/sync/mock.ts
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/network/sync/syncEnginePerf.test.ts
  apps/hubble/src/rpc/adminServer.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/bulkService.test.ts
  apps/hubble/src/rpc/test/castService.test.ts
  apps/hubble/src/rpc/test/concurrency.test.ts
  apps/hubble/src/rpc/test/reactionService.test.ts
  apps/hubble/src/rpc/test/rpcAuth.test.ts
  apps/hubble/src/rpc/test/signerService.test.ts
  apps/hubble/src/rpc/test/submitService.test.ts
  apps/hubble/src/rpc/test/userDataService.test.ts
  apps/hubble/src/rpc/test/verificationService.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/test/bench/syncEngine.ts
  apps/hubble/src/test/mocks.ts
  packages/hub-web/examples/chron-feed/package.json
  packages/hub-web/examples/chron-feed/yarn.lock
Labels: t-chore

#886 chore: add new peerid for @df
  apps/hubble/src/allowedPeers.mainnet.ts
Labels: t-chore

#880 chore: add new mainnet peer for molo
  apps/hubble/src/allowedPeers.mainnet.ts
Labels: t-chore

#888 chore: fail the build if current version is too close to expiry
  apps/hubble/src/utils/versions.test.ts
Labels: t-chore

#847 feat: support arbitrary target types
  .changeset/config.json
  .changeset/eight-bugs-rhyme.md
  .changeset/tough-fireants-confess.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/castService.test.ts
  apps/hubble/src/rpc/test/reactionService.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/castStore.test.ts
  apps/hubble/src/storage/stores/castStore.ts
  apps/hubble/src/storage/stores/reactionStore.test.ts
  apps/hubble/src/storage/stores/reactionStore.ts
  apps/hubble/src/utils/periodicTestDataJob.ts
  packages/core/src/builders.test.ts
  packages/core/src/factories.ts
  packages/core/src/protobufs/generated/message.ts
  packages/core/src/protobufs/generated/request_response.ts
  packages/core/src/validations.test.ts
  packages/core/src/validations.ts
  packages/hub-nodejs/src/generated/message.ts
  packages/hub-nodejs/src/generated/request_response.ts
  packages/hub-nodejs/src/generated/rpc.ts
  packages/hub-web/src/generated/message.ts
  packages/hub-web/src/generated/request_response.ts
  packages/hub-web/src/generated/rpc.ts
  protobufs/schemas/message.proto
  protobufs/schemas/request_response.proto
  protobufs/schemas/rpc.proto
Labels: t-feat

#899 fix: Fix off by one error when retrying id registry event on sync
  .changeset/moody-rocks-greet.md
  apps/hubble/src/cli.ts
  apps/hubble/src/eth/ethEventsProvider.test.ts
  apps/hubble/src/eth/ethEventsProvider.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/test/mocks.ts
Labels: t-bug

#900 docs(hub-nodejs): update example
  packages/hub-nodejs/README.md
Labels: t-docs

#903 docs(hubble): add instructions for connecting to mainnet
  CONTRIBUTING.md
  apps/hubble/README.md
  apps/hubble/src/eth/ethEventsProvider.test.ts
Labels: t-docs

#905 chore(hub-nodejs): add hub urls, steps to chron-feed examples
  packages/hub-nodejs/examples/chron-feed/README.md
  packages/hub-nodejs/examples/chron-feed/index.ts
  packages/hub-nodejs/examples/chron-feed/package.json
  packages/hub-nodejs/examples/chron-feed/yarn.lock
  packages/hub-web/examples/chron-feed/index.ts
Labels: t-chore

#910 chore(hub-nodejs): update write-data example
  packages/hub-nodejs/examples/chron-feed/README.md
  packages/hub-nodejs/examples/write-data/README.md
  packages/hub-nodejs/examples/write-data/index.ts
  packages/hub-nodejs/examples/write-data/package.json
  packages/hub-nodejs/examples/write-data/yarn.lock
Labels: t-chore

#912 docs(hubble): use hubble/latest instead of a specific version
  apps/hubble/README.md
Labels: t-docs

#913 docs(hubble): add pm2 logrotate, exponential backoff to address failures
  README.md
  apps/hubble/README.md
Labels: t-docs

#915 chore(hub-nodejs): update write-cast example for v0.7
  packages/hub-nodejs/examples/make-cast/README.md
  packages/hub-nodejs/examples/make-cast/index.ts
  packages/hub-nodejs/examples/make-cast/package.json
  packages/hub-nodejs/examples/make-cast/yarn.lock
  packages/hub-nodejs/examples/write-data/README.md
  packages/hub-nodejs/examples/write-data/index.ts
Labels: t-chore

#917 fix: Dedup eth events retries by block number to save api calls
  .changeset/kind-bugs-wave.md
  apps/hubble/src/eth/ethEventsProvider.ts
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
Labels: t-bug

#916 feat: Add sync stats to getInfo call
  .changeset/tall-turtles-shake.md
  apps/hubble/src/cli.ts
  apps/hubble/src/console/console.ts
  apps/hubble/src/eth/ethEventsProvider.test.ts
  apps/hubble/src/eth/ethEventsProvider.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/rpcAuth.test.ts
  packages/core/src/protobufs/generated/request_response.ts
  packages/hub-nodejs/src/generated/request_response.ts
  packages/hub-nodejs/src/generated/rpc.ts
  packages/hub-web/src/generated/request_response.ts
  packages/hub-web/src/generated/rpc.ts
  protobufs/schemas/request_response.proto
  protobufs/schemas/rpc.proto
Labels: t-feat

#920 feat: Remember bad peers during sync and ignore them for a while.
  .changeset/tall-squids-speak.md
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/network/sync/syncEnginePerf.test.ts
  apps/hubble/src/test/bench/syncEngine.ts
Labels: t-feat

#787 feat: implement ViemLocalEip712Signer
  .changeset/angry-fireants-melt.md
  packages/core/package.json
  packages/core/src/crypto/eip712.ts
  packages/core/src/signers/ethersEip712Signer.test.ts
  packages/core/src/signers/ethersV5Eip712Signer.test.ts
  packages/core/src/signers/nobleEd25519Signer.test.ts
  packages/core/src/signers/testUtils.ts
  packages/core/src/signers/viemLocalEip712Signer.test.ts
  packages/core/src/signers/viemLocalEip712Signer.ts
  yarn.lock
Labels: t-feat, s-ready

#925 chore: Release 1.2.1
  .changeset/angry-fireants-melt.md
  .changeset/kind-bugs-wave.md
  .changeset/moody-rocks-greet.md
  .changeset/tall-squids-speak.md
  .changeset/tall-turtles-shake.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#926 chore: added jam.so peer id to mainnet allowed peers
  apps/hubble/src/allowedPeers.mainnet.ts
Labels: t-chore

#927 chore: add @yanisme to allowlist
  apps/hubble/src/allowedPeers.mainnet.ts
Labels: t-chore
