Repository farcasterxyz/hub-monorepo, pull requests merged in 2023-03, with the labels that each got.

#623 feat: add ability to change contract configuration via cli
  apps/hubble/src/cli.ts
  apps/hubble/src/eth/ethEventsProvider.test.ts
  apps/hubble/src/eth/ethEventsProvider.ts
  apps/hubble/src/hubble.ts
Labels: feat

#627 feat: add name field to signers
  .changeset/rotten-lamps-serve.md
  apps/hubble/src/console/genCommand.ts
  apps/hubble/src/console/warpcastTestCommand.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/p2p/gossipNode.test.ts
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.test.ts
  apps/hubble/src/network/sync/syncEnginePerf.test.ts
  apps/hubble/src/rpc/server/test/bulkService.test.ts
  apps/hubble/src/rpc/server/test/castService.test.ts
  apps/hubble/src/rpc/server/test/eventService.test.ts
  apps/hubble/src/rpc/server/test/reactionService.test.ts
  apps/hubble/src/rpc/server/test/rpcAuth.test.ts
  apps/hubble/src/rpc/server/test/signerService.test.ts
  apps/hubble/src/rpc/server/test/submitService.test.ts
  apps/hubble/src/rpc/server/test/userDataService.test.ts
  apps/hubble/src/rpc/server/test/verificationService.test.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/seed.ts
  apps/hubble/src/storage/stores/signerStore.test.ts
  apps/hubble/src/storage/stores/signerStore.ts
  packages/js/src/builders.ts
  packages/js/src/types.ts
  packages/js/src/utils.test.ts
  packages/js/src/utils.ts
  packages/protobufs/package.json
  packages/protobufs/src/generated/gossip.ts
  packages/protobufs/src/generated/hub_event.ts
  packages/protobufs/src/generated/id_registry_event.ts
  packages/protobufs/src/generated/message.ts
  packages/protobufs/src/generated/name_registry_event.ts
  packages/protobufs/src/schemas/message.proto
  packages/protobufs/src/typeguards.ts
  packages/protobufs/src/types.ts
  packages/utils/src/factories.ts
  packages/utils/src/validations.test.ts
  packages/utils/src/validations.ts
Labels: feat

#629 chore: changeset version
  .changeset/eighty-items-serve.md
  .changeset/rotten-lamps-serve.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/js/CHANGELOG.md
  packages/js/package.json
  packages/protobufs/CHANGELOG.md
  packages/protobufs/package.json
  packages/utils/CHANGELOG.md
  packages/utils/package.json
Labels: chore

#632 chore: force shutdown when stopping grpc server
  apps/hubble/src/hubble.ts
  apps/hubble/src/rpc/server/index.ts
Labels: chore

#633 fix: validate length limits in terms of utf8 bytes and allow up to 10 mentions
  .changeset/ten-shrimps-know.md
  packages/utils/src/bytes.ts
  packages/utils/src/validations.test.ts
  packages/utils/src/validations.ts
Labels: bug

#637 chore: changeset version
  .changeset/ten-shrimps-know.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/js/CHANGELOG.md
  packages/js/package.json
  packages/utils/CHANGELOG.md
  packages/utils/package.json
Labels: chore

#638 fix: Validate embed URLs using utf8 byte length
  .changeset/old-dancers-promise.md
  packages/utils/src/validations.test.ts
  packages/utils/src/validations.ts
Labels: bug

#640 chore: changeset version
  .changeset/old-dancers-promise.md
  .changeset/strange-humans-change.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/js/CHANGELOG.md
  packages/js/package.json
  packages/utils/CHANGELOG.md
  packages/utils/package.json
Labels: chore

#639 docs: remove typedoc and outdated docs
  hideSig.js
  package.json
  packages/utils/src/signers/ed25519Signer.ts
  packages/utils/src/signers/eip712Signer.ts
  typedoc.json
  yarn.lock
Labels: docs

#610 feat: pagination for list queries and gRPC
  .changeset/real-bananas-grin.md
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/rpc/server/index.ts
  apps/hubble/src/rpc/server/test/bulkService.test.ts
  apps/hubble/src/rpc/server/test/castService.test.ts
  apps/hubble/src/rpc/server/test/concurrency.test.ts
  apps/hubble/src/rpc/server/test/reactionService.test.ts
  apps/hubble/src/rpc/server/test/signerService.test.ts
  apps/hubble/src/rpc/server/test/userDataService.test.ts
  apps/hubble/src/storage/db/message.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/jobs/pruneMessagesJob.test.ts
  apps/hubble/src/storage/jobs/pruneMessagesJob.ts
  apps/hubble/src/storage/stores/castStore.test.ts
  apps/hubble/src/storage/stores/castStore.ts
  apps/hubble/src/storage/stores/reactionStore.test.ts
  apps/hubble/src/storage/stores/reactionStore.ts
  apps/hubble/src/storage/stores/signerStore.test.ts
  apps/hubble/src/storage/stores/signerStore.ts
  apps/hubble/src/storage/stores/types.ts
  apps/hubble/src/storage/stores/userDataStore.test.ts
  apps/hubble/src/storage/stores/userDataStore.ts
  apps/hubble/src/storage/stores/utils.ts
  apps/hubble/src/storage/stores/verificationStore.test.ts
  apps/hubble/src/storage/stores/verificationStore.ts
  apps/hubble/src/utils/logger.ts
  packages/protobufs/src/generated/rpc.ts
  packages/protobufs/src/schemas/rpc.proto
Labels: feat

#650 chore: move submitIdRegistryEvent and submitNameRegistryEvent to admin grpc service
  .changeset/twenty-eggs-perform.md
  apps/hubble/src/console/adminCommand.ts
  apps/hubble/src/console/console.ts
  apps/hubble/src/console/genCommand.ts
  apps/hubble/src/console/warpcastTestCommand.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/p2p/gossipNode.test.ts
  apps/hubble/src/rpc/adminServer.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/bulkService.test.ts
  apps/hubble/src/rpc/test/castService.test.ts
  apps/hubble/src/rpc/test/concurrency.test.ts
  apps/hubble/src/rpc/test/eventService.test.ts
  apps/hubble/src/rpc/test/reactionService.test.ts
  apps/hubble/src/rpc/test/rpcAuth.test.ts
  apps/hubble/src/rpc/test/signerService.test.ts
  apps/hubble/src/rpc/test/submitService.test.ts
  apps/hubble/src/rpc/test/userDataService.test.ts
  apps/hubble/src/rpc/test/verificationService.test.ts
  packages/protobufs/src/generated/rpc.ts
  packages/protobufs/src/schemas/rpc.proto
  packages/utils/src/client.ts
Labels: chore

#656 chore: upgrade typescript to v5 from v5beta
  package.json
  yarn.lock
Labels: chore

#658 refactor(farcaster/hub-nodejs): rename farcaster/js to farcaster/hub-nodejs
  .changeset/dirty-weeks-watch.md
  CONTRIBUTING.md
  README.md
  apps/hubble/README.md
  packages/hub-nodejs/.eslintrc.cjs
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/README.md
  packages/hub-nodejs/docs/Builders.md
  packages/hub-nodejs/docs/Client.md
  packages/hub-nodejs/docs/Events.md
  packages/hub-nodejs/docs/Messages.md
  packages/hub-nodejs/docs/README.md
  packages/hub-nodejs/docs/signers/Ed25519Signer.md
  packages/hub-nodejs/docs/signers/Eip712Signer.md
  packages/hub-nodejs/examples/README.md
  packages/hub-nodejs/examples/write-signer.md
  packages/hub-nodejs/jest.config.ts
  packages/hub-nodejs/package.json
  packages/hub-nodejs/src/index.test.ts
  packages/hub-nodejs/src/index.ts
  packages/hub-nodejs/tsconfig.json
Labels: chore

#659 chore: upgrade minor and patch versions of monorepo dependencies
  package.json
  yarn.lock
Labels: chore

#664 docs(hub-nodejs): improve docs based on feedback
  packages/hub-nodejs/docs/Builders.md
  packages/hub-nodejs/docs/Messages.md
  packages/hub-nodejs/docs/README.md
  packages/hub-nodejs/docs/Utils.md
  packages/hub-nodejs/examples/write-signer.md
  packages/protobufs/docs/message.md
Labels: docs

#674 chore: improve engine error messages
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
Labels: chore

#676 chore: changeset version bumps
  .changeset/breezy-glasses-search.md
  .changeset/chilly-deers-sit.md
  .changeset/weak-cameras-press.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/utils/CHANGELOG.md
  packages/utils/package.json
Labels: chore

#678 chore: upgrade minor and patch versions of packages
  .changeset/purple-bugs-itch.md
  apps/hubble/package.json
  packages/eslint-config-custom/package.json
  packages/hub-nodejs/package.json
  packages/protobufs/package.json
  packages/utils/package.json
  yarn.lock
Labels: chore

#670 refactor: update ethers to v6.1 from v5.7
  .changeset/forty-zoos-tan.md
  apps/hubble/package.json
  apps/hubble/src/eth/ethEventsProvider.test.ts
  apps/hubble/src/eth/ethEventsProvider.ts
  apps/hubble/src/eth/utils.test.ts
  apps/hubble/src/eth/utils.ts
  packages/hub-nodejs/docs/Builders.md
  packages/hub-nodejs/docs/Messages.md
  packages/hub-nodejs/docs/Utils.md
  packages/hub-nodejs/docs/signers/Eip712Signer.md
  packages/hub-nodejs/examples/write-signer.md
  packages/hub-nodejs/package.json
  packages/utils/package.json
  packages/utils/src/builders.test.ts
  packages/utils/src/bytes.test.ts
  packages/utils/src/bytes.ts
  packages/utils/src/crypto/ed25519.test.ts
  packages/utils/src/crypto/eip712.test.ts
  packages/utils/src/crypto/eip712.ts
  packages/utils/src/factories.ts
  packages/utils/src/signers/ed25519Signer.test.ts
  packages/utils/src/signers/eip712Signer.test.ts
  packages/utils/src/signers/eip712Signer.ts
  packages/utils/src/verifications.ts
  yarn.lock
Labels: chore

#680 docs(hub-nodejs): add documentation for pagination, responses
  packages/hub-nodejs/README.md
  packages/hub-nodejs/docs/Builders.md
  packages/hub-nodejs/docs/Client.md
  packages/hub-nodejs/docs/README.md
Labels: docs

#679 fix: Fix memory leak in prune messages job
  apps/hubble/src/network/sync/merkleTrie.test.ts
  apps/hubble/src/storage/db/message.ts
  apps/hubble/src/storage/db/nameRegistryEvent.test.ts
  apps/hubble/src/storage/db/nameRegistryEvent.ts
  apps/hubble/src/storage/db/rocksdb.test.ts
  apps/hubble/src/storage/db/rocksdb.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/jobs/revokeSignerJob.ts
  apps/hubble/src/storage/jobs/updateNameRegistryEventExpiryJob.ts
  apps/hubble/src/storage/stores/castStore.ts
  apps/hubble/src/storage/stores/reactionStore.ts
  apps/hubble/src/storage/stores/signerStore.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
  apps/hubble/src/storage/stores/userDataStore.ts
  apps/hubble/src/storage/stores/verificationStore.ts
Labels: bug

#675 feat: refactor events to create and broadcast in order
  apps/hubble/src/storage/stores/castStore.ts
  apps/hubble/src/storage/stores/reactionStore.ts
  apps/hubble/src/storage/stores/signerStore.ts
  apps/hubble/src/storage/stores/storeEventHandler.test.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
  apps/hubble/src/storage/stores/userDataStore.ts
  apps/hubble/src/storage/stores/verificationStore.ts
  apps/hubble/src/test/bench/syncEngine.ts
Labels: feat

#684 feat: Exit if superseeded by a newer hub
  .changeset/ten-buttons-confess.md
  apps/hubble/src/cli.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/storage/db/rocksdb.ts
Labels: feat

#688 fix: Switch to time-based check for process shutdown file
  .changeset/funny-ears-compare.md
  apps/hubble/src/cli.ts
Labels: bug

#692 chore: Allow specifying hub name via environment variable
  .changeset/clever-seals-greet.md
  apps/hubble/src/hubble.ts
Labels: chore

#695 feat: add reverse rpc pageOption
  .changeset/afraid-adults-travel.md
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/storage/db/message.ts
  apps/hubble/src/storage/stores/castStore.ts
  apps/hubble/src/storage/stores/reactionStore.ts
  apps/hubble/src/storage/stores/signerStore.test.ts
  apps/hubble/src/storage/stores/signerStore.ts
  apps/hubble/src/storage/stores/types.ts
  packages/protobufs/src/generated/gossip.ts
  packages/protobufs/src/generated/hub_event.ts
  packages/protobufs/src/generated/hub_state.ts
  packages/protobufs/src/generated/id_registry_event.ts
  packages/protobufs/src/generated/job.ts
  packages/protobufs/src/generated/message.ts
  packages/protobufs/src/generated/name_registry_event.ts
  packages/protobufs/src/generated/rpc.ts
  packages/protobufs/src/generated/sync_trie.ts
  packages/protobufs/src/schemas/rpc.proto
Labels: feat

#699 feat: sort casts and reactions indices by timestamp
  apps/hubble/src/storage/stores/castStore.test.ts
  apps/hubble/src/storage/stores/castStore.ts
  apps/hubble/src/storage/stores/reactionStore.test.ts
  apps/hubble/src/storage/stores/reactionStore.ts
Labels: feat

#700 chore: bump versions
  .changeset/afraid-adults-travel.md
  .changeset/clever-seals-greet.md
  .changeset/curvy-pianos-wave.md
  .changeset/famous-chefs-nail.md
  .changeset/forty-zoos-tan.md
  .changeset/funny-ears-compare.md
  .changeset/fuzzy-lemons-cheer.md
  .changeset/purple-bugs-itch.md
  .changeset/ten-buttons-confess.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/eslint-config-custom/CHANGELOG.md
  packages/eslint-config-custom/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/protobufs/CHANGELOG.md
  packages/protobufs/package.json
  packages/utils/CHANGELOG.md
  packages/utils/package.json
Labels: chore

#701 docs(hub-nodejs): update invocations to match 0.5.0 release, fix minor typos
  packages/hub-nodejs/README.md
  packages/hub-nodejs/docs/Builders.md
  packages/hub-nodejs/docs/Utils.md
  packages/hub-nodejs/docs/signers/EthersEip712Signer.md
  packages/hub-nodejs/docs/signers/NobleEd25519Signer.md
Labels: docs

#709 docs(hub-nodejs): configuration for use with ethersv5
  packages/hub-nodejs/docs/README.md
  packages/hub-nodejs/docs/signers/EthersEip712Signer.md
Labels: docs

#704 docs(hub-nodejs): add chronological feed example
  packages/hub-nodejs/examples/README.md
  packages/hub-nodejs/examples/feed/README.md
  packages/hub-nodejs/examples/feed/index.ts
  packages/hub-nodejs/examples/feed/package.json
  packages/hub-nodejs/examples/feed/tsconfig.json
  packages/hub-nodejs/examples/feed/yarn.lock
Labels: docs

#705 feat: revoke messages immediately
  apps/hubble/src/hubble.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/jobs/revokeSignerJob.test.ts
  apps/hubble/src/storage/jobs/revokeSignerJob.ts
  apps/hubble/src/storage/stores/castStore.ts
  apps/hubble/src/storage/stores/reactionStore.ts
  apps/hubble/src/storage/stores/signerStore.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
  apps/hubble/src/storage/stores/userDataStore.ts
  apps/hubble/src/storage/stores/verificationStore.ts
Labels: feat

#711 docs(hub-nodejs): add docs for reverse param
  packages/hub-nodejs/docs/Client.md
  packages/hub-nodejs/examples/chron-feed/index.ts
Labels: docs

#713 feat: Reset DB if DB_RESET_TOKEN is set
  .changeset/wise-peaches-remain.md
  apps/hubble/src/cli.ts
Labels: feat

#717 feat: add storage cache to speed up pruning
  apps/hubble/src/hubble.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/engine/storageCache.test.ts
  apps/hubble/src/storage/engine/storageCache.ts
  apps/hubble/src/storage/stores/castStore.ts
  apps/hubble/src/storage/stores/reactionStore.ts
  apps/hubble/src/storage/stores/signerStore.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
  apps/hubble/src/storage/stores/userDataStore.ts
  apps/hubble/src/storage/stores/verificationStore.ts
  packages/utils/src/factories.ts
Labels: feat

#718 chore: use warn rather than error for submit* logs
  apps/hubble/src/hubble.ts
Labels: chore

#721 chore: minor pruning refactor
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/jobs/pruneMessagesJob.ts
  apps/hubble/src/storage/stores/castStore.test.ts
  apps/hubble/src/storage/stores/castStore.ts
  apps/hubble/src/storage/stores/reactionStore.test.ts
  apps/hubble/src/storage/stores/reactionStore.ts
  apps/hubble/src/storage/stores/signerStore.test.ts
  apps/hubble/src/storage/stores/signerStore.ts
  apps/hubble/src/storage/stores/storeEventHandler.test.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
  apps/hubble/src/storage/stores/userDataStore.test.ts
  apps/hubble/src/storage/stores/userDataStore.ts
  apps/hubble/src/storage/stores/verificationStore.test.ts
  apps/hubble/src/storage/stores/verificationStore.ts
  apps/hubble/src/test/bench/syncEngine.ts
Labels: chore

#725 feat: move signer pruning before other sets
  apps/hubble/src/storage/engine/index.ts
Labels: feat

#732 docs(hub-nodejs): small cleanups and improvements
  packages/hub-nodejs/README.md
  packages/hub-nodejs/docs/Client.md
Labels: docs

#741 feat: move revoking messages into delayed job
  .changeset/yellow-islands-join.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/storage/db/types.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/jobs/pruneMessagesJob.ts
  apps/hubble/src/storage/jobs/revokeMessagesBySignerJob.ts
  apps/hubble/src/storage/jobs/updateNameRegistryEventExpiryJob.ts
  apps/hubble/src/storage/jobs/utils/factories.ts
  apps/hubble/src/storage/stores/castStore.ts
  apps/hubble/src/storage/stores/reactionStore.ts
  apps/hubble/src/storage/stores/signerStore.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
  apps/hubble/src/storage/stores/userDataStore.ts
  apps/hubble/src/storage/stores/verificationStore.ts
  packages/protobufs/src/generated/job.ts
  packages/protobufs/src/schemas/job.proto
Labels: feat

#743 docs(hub-nodejs): more cleanup based on user testing
  .changeset/witty-trainers-bake.md
  packages/hub-nodejs/README.md
  packages/hub-nodejs/docs/Client.md
  packages/hub-nodejs/examples/README.md
  packages/hub-nodejs/examples/chron-feed/README.md
Labels: docs

#744 fix(hubble): crash by bumping ethers to 6.2.1
  .changeset/tame-avocados-develop.md
  apps/hubble/package.json
  packages/hub-nodejs/package.json
  packages/utils/package.json
  yarn.lock
Labels: bug

#745 docs(hub-nodejs): fix parentCastId of CastAdd incorrectly labelled
  packages/hub-nodejs/docs/Messages.md
Labels: docs

#747 chore: Include package to enable Node.js runtime metrics collection
  Dockerfile
Labels: chore

#748 feat: commit one event at a time
  apps/hubble/src/storage/db/message.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/jobs/pruneMessagesJob.test.ts
  apps/hubble/src/storage/stores/castStore.test.ts
  apps/hubble/src/storage/stores/castStore.ts
  apps/hubble/src/storage/stores/reactionStore.test.ts
  apps/hubble/src/storage/stores/reactionStore.ts
  apps/hubble/src/storage/stores/signerStore.test.ts
  apps/hubble/src/storage/stores/signerStore.ts
  apps/hubble/src/storage/stores/storeEventHandler.test.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
  apps/hubble/src/storage/stores/userDataStore.test.ts
  apps/hubble/src/storage/stores/userDataStore.ts
  apps/hubble/src/storage/stores/verificationStore.test.ts
  apps/hubble/src/storage/stores/verificationStore.ts
  apps/hubble/src/test/bench/syncEngine.ts
Labels: feat

#752 chore: changeset version and make custom dev packages private
  .changeset/healthy-poems-compare.md
  .changeset/hungry-nails-collect.md
  .changeset/shaggy-hairs-tap.md
  .changeset/spicy-ants-sin.md
  .changeset/tame-avocados-develop.md
  .changeset/ten-ducks-roll.md
  .changeset/wise-peaches-remain.md
  .changeset/wise-sloths-tan.md
  .changeset/witty-trainers-bake.md
  .changeset/yellow-islands-join.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/eslint-config-custom/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/prettier-config-custom/package.json
  packages/protobufs/CHANGELOG.md
  packages/protobufs/package.json
  packages/utils/CHANGELOG.md
  packages/utils/package.json
Labels: chore

#762 docs: release instructions
  CONTRIBUTING.md
Labels: docs

#763 chore(hubble): make syncEngine logs and docs easier to understand
  apps/hubble/src/network/sync/syncEngine.ts
Labels: docs, chore

#769 chore: update revoke and pruning to continue after error for a single record
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/jobs/revokeMessagesBySignerJob.ts
  apps/hubble/src/storage/stores/castStore.ts
  apps/hubble/src/storage/stores/reactionStore.ts
  apps/hubble/src/storage/stores/signerStore.ts
  apps/hubble/src/storage/stores/userDataStore.ts
  apps/hubble/src/storage/stores/verificationStore.ts
Labels: chore

#772 docs(hubble): update instructions for connecting to testnet
  apps/hubble/README.md
Labels: docs

#778 feat: revoke UserDataAdd for fname when fid transfers
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
Labels: feat

#791 feat: add getIdRegistryEventByAddress method
  .changeset/big-apricots-clean.md
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/signerStore.test.ts
  apps/hubble/src/storage/stores/signerStore.ts
  packages/protobufs/src/generated/rpc.ts
  packages/protobufs/src/schemas/rpc.proto
Labels: feat
