Repository farcasterxyz/hub-monorepo, pull requests merged in 2023-05, with the labels that each got.

#934 fix: Fix inSync reporting true when peer is blocked from sync
  apps/hubble/src/network/sync/syncEngine.ts
Labels: t-chore

#928 feat: reject prunable messages on merge
  .changeset/smart-glasses-confess.md
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.test.ts
  apps/hubble/src/network/sync/syncEnginePerf.test.ts
  apps/hubble/src/rpc/test/castService.test.ts
  apps/hubble/src/storage/jobs/pruneMessagesJob.test.ts
  apps/hubble/src/storage/stores/castStore.test.ts
  apps/hubble/src/storage/stores/castStore.ts
  apps/hubble/src/storage/stores/reactionStore.test.ts
  apps/hubble/src/storage/stores/reactionStore.ts
  apps/hubble/src/storage/stores/signerStore.test.ts
  apps/hubble/src/storage/stores/signerStore.ts
  apps/hubble/src/storage/stores/storageCache.test.ts
  apps/hubble/src/storage/stores/storageCache.ts
  apps/hubble/src/storage/stores/storeEventHandler.test.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
  apps/hubble/src/storage/stores/userDataStore.test.ts
  apps/hubble/src/storage/stores/userDataStore.ts
  apps/hubble/src/storage/stores/verificationStore.test.ts
  apps/hubble/src/storage/stores/verificationStore.ts
  packages/core/src/errors.ts
Labels: t-feat

#939 fix: Only consider a peer bad if we failed to merge a large number of messages
  apps/hubble/src/network/sync/syncEngine.ts
Labels: t-bug

#938 chore: Add syncing/replication example for Postgres
  packages/hub-nodejs/examples/README.md
  packages/hub-nodejs/examples/replicate-data-postgres/README.md
  packages/hub-nodejs/examples/replicate-data-postgres/db.ts
  packages/hub-nodejs/examples/replicate-data-postgres/docker-compose.yml
  packages/hub-nodejs/examples/replicate-data-postgres/hubReplicator.ts
  packages/hub-nodejs/examples/replicate-data-postgres/hubSubscriber.ts
  packages/hub-nodejs/examples/replicate-data-postgres/index.ts
  packages/hub-nodejs/examples/replicate-data-postgres/log.ts
  packages/hub-nodejs/examples/replicate-data-postgres/migrations/001_initial_migration.ts
  packages/hub-nodejs/examples/replicate-data-postgres/package.json
  packages/hub-nodejs/examples/replicate-data-postgres/tsconfig.json
  packages/hub-nodejs/examples/replicate-data-postgres/util.ts
  packages/hub-nodejs/examples/replicate-data-postgres/yarn.lock
Labels: t-chore, t-devex

#941 chore: Remove some unused code from replication example
  packages/hub-nodejs/examples/replicate-data-postgres/hubReplicator.ts
  packages/hub-nodejs/examples/replicate-data-postgres/hubSubscriber.ts
Labels: t-chore

#942 chore: ensure we clear the event handler cache in tests
  apps/hubble/src/storage/stores/castStore.test.ts
  apps/hubble/src/storage/stores/reactionStore.test.ts
  apps/hubble/src/storage/stores/signerStore.test.ts
  apps/hubble/src/storage/stores/storeEventHandler.test.ts
  apps/hubble/src/storage/stores/userDataStore.test.ts
  apps/hubble/src/storage/stores/verificationStore.test.ts
Labels: t-chore

#919 fix: improve handling of duplicate messages on gossip
  .changeset/lucky-mails-develop.md
  apps/hubble/src/network/p2p/gossipNode.test.ts
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/p2p/protocol.ts
  apps/hubble/src/network/utils/factories.ts
  apps/hubble/src/test/e2e/gossipNetwork.test.ts
  packages/core/src/protobufs/generated/gossip.ts
  protobufs/schemas/gossip.proto
Labels: t-bug

#943 fix: Reduce memory consumption of replication example
  packages/hub-nodejs/examples/replicate-data-postgres/hubReplicator.ts
  packages/hub-nodejs/examples/replicate-data-postgres/package.json
Labels: t-bug, t-devex

#944 feat: Add a status hubble command for friendly reporting of current hub status
  .changeset/shiny-tables-join.md
  apps/hubble/package.json
  apps/hubble/src/cli.ts
  apps/hubble/src/console/console.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/sync/syncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/network/sync/syncId.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/syncService.test.ts
  apps/hubble/src/test/mocks.ts
  packages/core/src/protobufs/generated/request_response.ts
  packages/hub-nodejs/src/generated/request_response.ts
  packages/hub-nodejs/src/generated/rpc.ts
  packages/hub-web/src/generated/request_response.ts
  packages/hub-web/src/generated/rpc.ts
  protobufs/schemas/request_response.proto
  protobufs/schemas/rpc.proto
Labels: t-feat

#950 chore: Improve documentation for replication example
  packages/hub-nodejs/examples/replicate-data-postgres/README.md
  packages/hub-nodejs/examples/replicate-data-postgres/hubReplicator.ts
  packages/hub-nodejs/examples/replicate-data-postgres/index.ts
  packages/hub-nodejs/examples/replicate-data-postgres/migrations/001_initial_migration.ts
  packages/hub-nodejs/examples/replicate-data-postgres/package.json
Labels: t-docs, t-chore

#951 chore: Adding missing sections of replication README
  packages/hub-nodejs/examples/replicate-data-postgres/README.md
Labels: t-docs, t-chore

#952 chore: Streamline replication example further
  packages/hub-nodejs/examples/replicate-data-postgres/Brewfile
  packages/hub-nodejs/examples/replicate-data-postgres/README.md
  packages/hub-nodejs/examples/replicate-data-postgres/docker-compose.yml
  packages/hub-nodejs/examples/replicate-data-postgres/log.ts
  packages/hub-nodejs/examples/replicate-data-postgres/package.json
  packages/hub-nodejs/examples/replicate-data-postgres/yarn.lock
Labels: t-docs, t-chore

#953 fix: Correct typos in replicator docs
  packages/hub-nodejs/examples/replicate-data-postgres/README.md
  packages/hub-nodejs/examples/replicate-data-postgres/index.ts
Labels: t-bug

#955 chore: Optimize replication example
  packages/hub-nodejs/examples/replicate-data-postgres/README.md
  packages/hub-nodejs/examples/replicate-data-postgres/docker-compose.yml
  packages/hub-nodejs/examples/replicate-data-postgres/hubReplicator.ts
  packages/hub-nodejs/examples/replicate-data-postgres/package.json
  packages/hub-nodejs/examples/replicate-data-postgres/yarn.lock
Labels: t-docs, t-chore

#956 fix: Correct time remaining estimate
  packages/hub-nodejs/examples/replicate-data-postgres/README.md
  packages/hub-nodejs/examples/replicate-data-postgres/docker-compose.yml
  packages/hub-nodejs/examples/replicate-data-postgres/hubReplicator.ts
Labels: t-bug

#957 docs(hub-nodejs): cleanup replicate example readme
  packages/hub-nodejs/examples/README.md
  packages/hub-nodejs/examples/replicate-data-postgres/README.md
Labels: t-docs

#954 feat: Sync status improvements
  .changeset/cuddly-bottles-refuse.md
  apps/hubble/README.md
  apps/hubble/src/cli.ts
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/syncService.test.ts
Labels: t-feat

#947 chore: upgrade to @noble/curves
  .changeset/eleven-lies-wait.md
  apps/hubble/package.json
  apps/hubble/src/utils/periodicTestDataJob.ts
  packages/core/package.json
  packages/core/src/bytes.ts
  packages/core/src/crypto/ed25519.ts
  packages/core/src/factories.ts
  packages/core/src/signers/nobleEd25519Signer.test.ts
  packages/core/src/signers/nobleEd25519Signer.ts
  packages/core/src/validations.ts
  yarn.lock
Labels: t-chore

#960 chore: Switch to rocksdb fork with precompiled Linux ARM build
  .changeset/strange-otters-join.md
  apps/hubble/package.json
  apps/hubble/src/rocksdb.d.ts
  apps/hubble/src/storage/db/rocksdb.ts
  yarn.lock
Labels: t-chore, t-devex

#961 chore: Remove unnecessary @faker-js/faker dependency from core
  .changeset/eight-mangos-change.md
  .changeset/strong-trainers-hide.md
  apps/hubble/package.json
  packages/core/package.json
Labels: t-chore

#962 feat: Add separate Dockerfile for dedicated public image
  .changeset/slimy-ways-argue.md
  .dockerignore
  .github/workflows/ci.yml
  .gitignore
  Dockerfile.hubble
  Dockerfile.hubble.test
  apps/hubble/package.json
  docker-compose.yml
  yarn.lock
Labels: t-feat, t-devex

#963 feat: Quickstart guide for running hubs with TLS
  apps/hubble/quickstart/Caddyfile
  apps/hubble/quickstart/README.md
  apps/hubble/quickstart/docker-compose.yml
  apps/hubble/quickstart/envoy.yaml
Labels: t-feat

#966 fix: Don't require Depot to build images for PRs from forks
  .github/workflows/ci.yml
Labels: t-bug

#959 fix(eth): add stronger retry logic to eth events provider
  .changeset/four-bats-work.md
  apps/hubble/src/eth/ethEventsProvider.test.ts
  apps/hubble/src/eth/ethEventsProvider.ts
  apps/hubble/src/eth/retryProvider.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/test/mocks.ts
  codecov.yml
Labels: t-bug

#967 chore: Add peer ID for `@sds`
  apps/hubble/src/allowedPeers.mainnet.ts
Labels: t-chore

#971 fix: Correctly error when sequence ID exceeds max allowed value
  .changeset/neat-trains-camp.md
  apps/hubble/src/storage/stores/storeEventHandler.test.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
Labels: t-bug

#972 chore: Build and test on Node.js 20
  .github/workflows/ci.yml
  CONTRIBUTING.md
  Dockerfile.hubble
  Dockerfile.hubble.test
  package.json
Labels: t-chore

#974 chore: Update README with Docker-based steps for running hubs
  apps/hubble/README.md
  apps/hubble/docker-compose.yml
  apps/hubble/quickstart/Caddyfile
  apps/hubble/quickstart/README.md
  apps/hubble/quickstart/docker-compose.yml
  apps/hubble/quickstart/envoy.yaml
Labels: t-chore

#975 chore: Fix typos in hub README updates
  apps/hubble/README.md
Labels: t-chore

#976 chore: Run tests on larger VM instances
  .github/workflows/ci.yml
Labels: t-chore

#986 chore(hub-nodejs): add example for replying to a URL (FIP-2)
  packages/hub-nodejs/examples/make-cast/index.ts
Labels: t-chore

#992 fix: Update Messages.md
  packages/hub-nodejs/docs/Messages.md
Labels: t-docs

#995 fix: Fix yarn commands
  apps/hubble/package.json
Labels: t-bug

#996 feat: add fallback to dbreset
  .changeset/rude-items-teach.md
  apps/hubble/src/cli.ts
Labels: t-feat, t-devex

#1000 chore: Release 1.3
  .changeset/dirty-badgers-sparkle.md
  .changeset/neat-trains-camp.md
  .changeset/rude-items-teach.md
  .changeset/thin-hotels-greet.md
  .changeset/thin-rivers-tie.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/hubble/src/hubble.ts
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore
