Repository farcasterxyz/hub-monorepo, pull requests merged in 2023-08, with the labels that each got.

#1203 feat: Implement migrating to L2
  .changeset/rude-rabbits-tease.md
  apps/hubble/src/eth/abis.ts
  apps/hubble/src/eth/l2EventsProvider.test.ts
  apps/hubble/src/eth/l2EventsProvider.ts
  apps/hubble/src/eth/watchContractEvent.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/rpc/adminServer.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/storage/db/onChainEvent.test.ts
  apps/hubble/src/storage/db/onChainEvent.ts
  apps/hubble/src/storage/db/types.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/onChainEventStore.ts
  apps/hubble/src/storage/stores/onchainEventStore.test.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
  apps/hubble/src/test/mocks.ts
  apps/hubble/src/utils/logger.ts
  packages/core/src/factories.ts
  packages/core/src/protobufs/generated/hub_event.ts
  packages/core/src/protobufs/generated/onchain_event.ts
  packages/core/src/protobufs/generated/request_response.ts
  packages/core/src/protobufs/index.ts
  packages/core/src/protobufs/typeguards.ts
  packages/core/src/protobufs/types.ts
  packages/hub-nodejs/src/generated/hub_event.ts
  packages/hub-nodejs/src/generated/onchain_event.ts
  packages/hub-nodejs/src/generated/request_response.ts
  packages/hub-nodejs/src/generated/rpc.ts
  packages/hub-web/src/generated/hub_event.ts
  packages/hub-web/src/generated/onchain_event.ts
  packages/hub-web/src/generated/request_response.ts
  packages/hub-web/src/generated/rpc.ts
  protobufs/schemas/hub_event.proto
  protobufs/schemas/onchain_event.proto
  protobufs/schemas/request_response.proto
  protobufs/schemas/rpc.proto
Labels: t-feat

#1208 chore: Setup grpc server timeouts
  .changeset/rare-bags-reflect.md
  apps/hubble/package.json
  packages/hub-nodejs/package.json
  packages/hub-nodejs/src/client.ts
  yarn.lock
Labels: t-chore

#1209 bug: Fix revoking messages on onchain signer revoke and make l2 options cutomizable
  .changeset/healthy-ghosts-hide.md
  apps/hubble/src/cli.ts
  apps/hubble/src/eth/l2EventsProvider.test.ts
  apps/hubble/src/eth/l2EventsProvider.ts
  apps/hubble/src/eth/watchContractEvent.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
Labels: t-bug

#1210 feat: Refactor storage events to use OnChainEvent
  .changeset/tidy-panthers-speak.md
  apps/hubble/src/console/genCommand.ts
  apps/hubble/src/eth/l2EventsProvider.test.ts
  apps/hubble/src/eth/l2EventsProvider.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/profile/rpcProfile.ts
  apps/hubble/src/rpc/adminServer.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/bulkService.test.ts
  apps/hubble/src/rpc/test/signerService.test.ts
  apps/hubble/src/storage/db/onChainEvent.ts
  apps/hubble/src/storage/db/storageRegistryEvent.test.ts
  apps/hubble/src/storage/db/storageRegistryEvent.ts
  apps/hubble/src/storage/db/types.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/storageCache.test.ts
  apps/hubble/src/storage/stores/storageCache.ts
  apps/hubble/src/storage/stores/storageEventStore.test.ts
  apps/hubble/src/storage/stores/storageEventStore.ts
  apps/hubble/src/storage/stores/store.test.ts
  apps/hubble/src/test/mocks.ts
  apps/hubble/src/utils/logger.ts
  packages/core/src/factories.test.ts
  packages/core/src/factories.ts
  packages/core/src/protobufs/generated/hub_event.ts
  packages/core/src/protobufs/generated/onchain_event.ts
  packages/core/src/protobufs/generated/request_response.ts
  packages/core/src/protobufs/typeguards.ts
  packages/core/src/protobufs/types.ts
  packages/hub-nodejs/src/generated/hub_event.ts
  packages/hub-nodejs/src/generated/onchain_event.ts
  packages/hub-nodejs/src/generated/request_response.ts
  packages/hub-nodejs/src/generated/rpc.ts
  packages/hub-web/src/generated/hub_event.ts
  packages/hub-web/src/generated/onchain_event.ts
  packages/hub-web/src/generated/request_response.ts
  packages/hub-web/src/generated/rpc.ts
  protobufs/schemas/hub_event.proto
  protobufs/schemas/onchain_event.proto
  protobufs/schemas/request_response.proto
  protobufs/schemas/rpc.proto
  protobufs/schemas/storage_event.proto
Labels: t-feat

#1211 feat: Storage RPC
  .changeset/young-lobsters-peel.md
  apps/hubble/src/eth/l2EventsProvider.test.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/bulkService.test.ts
  apps/hubble/src/rpc/test/server.test.ts
  apps/hubble/src/rpc/test/signerService.test.ts
  apps/hubble/src/storage/db/onChainEvent.test.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/castStore.ts
  apps/hubble/src/storage/stores/linkStore.ts
  apps/hubble/src/storage/stores/onchainEventStore.test.ts
  apps/hubble/src/storage/stores/reactionStore.ts
  apps/hubble/src/storage/stores/signerStore.ts
  apps/hubble/src/storage/stores/userDataStore.ts
  apps/hubble/src/storage/stores/verificationStore.ts
  apps/hubble/www/docs/docs/api.md
  packages/core/src/factories.ts
  packages/core/src/protobufs/generated/request_response.ts
  packages/core/src/protobufs/generated/storage_event.ts
  packages/core/src/protobufs/index.ts
  packages/core/src/protobufs/types.ts
  packages/hub-nodejs/src/generated/request_response.ts
  packages/hub-nodejs/src/generated/rpc.ts
  packages/hub-nodejs/src/generated/storage_event.ts
  packages/hub-web/src/generated/request_response.ts
  packages/hub-web/src/generated/rpc.ts
  packages/hub-web/src/generated/storage_event.ts
  protobufs/docs/rpc.md
  protobufs/schemas/request_response.proto
  protobufs/schemas/rpc.proto
Labels: t-feat

#1216 feat: speed up l2 sync and allow rent expiry override for testing
  apps/hubble/src/cli.ts
  apps/hubble/src/eth/l2EventsProvider.ts
  apps/hubble/src/hubble.ts
Labels: t-feat

#1213 feat: Rate limit merges by FID
  .changeset/heavy-pants-poke.md
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/rpcAuth.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/store.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
  apps/hubble/src/utils/rateLimits.test.ts
  apps/hubble/src/utils/rateLimits.ts
Labels: t-feat

#1226 fix: Fix onchain event subscription not sending events correctly
  .changeset/swift-ways-hear.md
  apps/hubble/src/network/sync/syncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/eventService.test.ts
  apps/hubble/src/storage/engine/index.ts
Labels: t-bug

#1227 feat: deprecate time based pruning
  .changeset/tidy-needles-greet.md
  apps/hubble/src/storage/jobs/pruneMessagesJob.test.ts
  apps/hubble/src/storage/stores/store.ts
Labels: t-feat

#1228 chore: Cut Hubble version 1.4.4 and other package upgrades
  .changeset/brave-steaks-change.md
  .changeset/breezy-swans-brake.md
  .changeset/cyan-foxes-wave.md
  .changeset/dull-glasses-admire.md
  .changeset/empty-eggs-cough.md
  .changeset/fifty-feet-punch.md
  .changeset/friendly-icons-sip.md
  .changeset/healthy-ghosts-hide.md
  .changeset/heavy-pants-poke.md
  .changeset/itchy-carrots-tap.md
  .changeset/khaki-clouds-attack.md
  .changeset/light-chairs-approve.md
  .changeset/little-fans-sort.md
  .changeset/nervous-rivers-love.md
  .changeset/rare-bags-reflect.md
  .changeset/rude-rabbits-tease.md
  .changeset/smart-hotels-punch.md
  .changeset/spicy-lamps-swim.md
  .changeset/swift-ways-hear.md
  .changeset/thirty-radios-search.md
  .changeset/tidy-needles-greet.md
  .changeset/tidy-panthers-speak.md
  .changeset/tiny-bears-peel.md
  .changeset/young-lobsters-peel.md
  CONTRIBUTING.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#1231 chore: Cut patch release for core and hub-nodejs
  .changeset/curly-sheep-tell.md
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
Labels: t-chore

#1233 chore: Cut patch release to fix neon shim
  .changeset/clean-bags-kick.md
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
Labels: t-chore

#1224 fix: typo's regarding time utilities in hub-nodejs
  packages/hub-nodejs/docs/Utils.md
Labels: t-docs

#1234 docs(hubble): update allow-list instructions
  apps/hubble/www/docs/intro/networks.md
Labels: t-docs

#1236 chore: remove duplicated peers
  apps/hubble/src/allowedPeers.mainnet.ts
Labels: t-chore

#1235 fix: Move rust code to apps/hubble, @farcaster/core to PureJS
  .changeset/proud-books-impress.md
  apps/hubble/package.json
  apps/hubble/rome.json
  apps/hubble/src/addon/.gitignore
  apps/hubble/src/addon/Cargo.lock
  apps/hubble/src/addon/Cargo.toml
  apps/hubble/src/addon/addon.ts
  apps/hubble/src/addon/rust-toolchain
  apps/hubble/src/addon/src/lib.rs
  apps/hubble/src/network/sync/trieNode.ts
  apps/hubble/src/rustfunctions.test.ts
  apps/hubble/src/rustfunctions.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/engine/validation.worker.ts
  apps/hubble/src/utils/crypto.ts
  packages/core/package.json
  packages/core/rome.json
  packages/core/src/addon/addon.d.ts
  packages/core/src/addon/addon.js
  packages/core/src/index.ts
  packages/core/src/rustfunctions.ts
  packages/core/src/validations.ts
Labels: t-bug

#1241 chore: Simplify rust bridge
  apps/hubble/package.json
  apps/hubble/src/addon/addon.ts
  apps/hubble/src/rustfunctions.ts
Labels: t-chore

#1246 fix: Fix ens proof message sync
  .changeset/tender-dingos-punch.md
  apps/hubble/src/network/sync/syncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
Labels: t-bug

#1247 chore: Update documentation for docker-compose.yml file
  apps/hubble/docker-compose.yml
  apps/hubble/envoy/envoy.yaml
  docker-compose.yml
Labels: t-docs, t-chore

#1256 fix: getUserNameProofsByFid should include fname proofs
  .changeset/eleven-mayflies-sell.md
  apps/hubble/src/rpc/test/userDataService.test.ts
  apps/hubble/src/storage/db/migrations/2.fnameproof.test.ts
  apps/hubble/src/storage/db/migrations/2.fnameproof.ts
  apps/hubble/src/storage/db/migrations/migrations.ts
  apps/hubble/src/storage/db/nameRegistryEvent.ts
  apps/hubble/src/storage/db/types.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/userDataStore.test.ts
  apps/hubble/src/storage/stores/userDataStore.ts
Labels: t-bug

#1258 fix: Fetch L2 network events in parallel
  .changeset/fluffy-vans-bake.md
  apps/hubble/src/eth/l2EventsProvider.ts
Labels: t-devex

#1264 feat: Add an events-reset command to clear l2 events
  .changeset/rare-pigs-teach.md
  apps/hubble/package.json
  apps/hubble/src/cli.ts
  apps/hubble/src/storage/stores/onChainEventStore.ts
  apps/hubble/src/storage/stores/onchainEventStore.test.ts
Labels: t-feat

#1265 chore: Improve gen.submitMessages() for testing
  .changeset/sweet-tools-act.md
  apps/hubble/src/console/genCommand.ts
Labels: t-chore

#1267 feat: enforce storage pruning 1 day after migration
  .changeset/spotty-hats-visit.md
  apps/hubble/src/eth/l2EventsProvider.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/onChainEventStore.ts
  apps/hubble/src/storage/stores/onchainEventStore.test.ts
  apps/hubble/src/storage/stores/storeEventHandler.test.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
  packages/core/src/factories.ts
Labels: t-feat

#1272 fix: Fix fname migration to handle corrupt data
  apps/hubble/src/storage/db/migrations/2.fnameproof.test.ts
  apps/hubble/src/storage/db/migrations/2.fnameproof.ts
  apps/hubble/src/storage/db/migrations/migrations.test.ts
  apps/hubble/src/storage/db/migrations/migrations.ts
Labels: t-bug

#1275 fix: Switch startup checks to check against OP Mainnet
  .changeset/short-seals-invite.md
  apps/hubble/src/cli.ts
Labels: t-bug

#1276 feat: Add new signer event fields and new onchainevent RPC calls
  .changeset/yellow-humans-rescue.md
  apps/hubble/src/eth/abis.ts
  apps/hubble/src/eth/l2EventsProvider.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/signerService.test.ts
  apps/hubble/src/storage/db/onChainEvent.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/onChainEventStore.ts
  apps/hubble/src/storage/stores/onchainEventStore.test.ts
  package.json
  packages/core/src/factories.ts
  packages/core/src/protobufs/generated/onchain_event.ts
  packages/core/src/protobufs/generated/request_response.ts
  packages/hub-nodejs/src/generated/onchain_event.ts
  packages/hub-nodejs/src/generated/request_response.ts
  packages/hub-nodejs/src/generated/rpc.ts
  packages/hub-web/src/generated/onchain_event.ts
  packages/hub-web/src/generated/request_response.ts
  packages/hub-web/src/generated/rpc.ts
  protobufs/schemas/onchain_event.proto
  protobufs/schemas/request_response.proto
  protobufs/schemas/rpc.proto
Labels: t-feat

#1279 feat: SyncEngine syncs from L2 if required post migration
  .changeset/young-lemons-develop.md
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/castStore.test.ts
  apps/hubble/src/storage/stores/reactionStore.test.ts
Labels: t-feat

#1282 feat: fetch contract addresses from network config
  .changeset/green-camels-roll.md
  apps/hubble/src/eth/l2EventsProvider.test.ts
  apps/hubble/src/eth/l2EventsProvider.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/utils/networkConfig.test.ts
  apps/hubble/src/network/utils/networkConfig.ts
Labels: t-feat

#1286 feat: Make l2 rpc url required to start hubble ahead of mainnet migration
  .changeset/new-penguins-end.md
  .github/workflows/ci.yml
  apps/hubble/src/cli.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/utils/startupCheck.ts
Labels: t-feat

#1287 chore: Release 1.5
  .changeset/cool-fans-appear.md
  .changeset/green-camels-roll.md
  .changeset/khaki-pens-clap.md
  .changeset/new-penguins-end.md
  .changeset/rare-pigs-teach.md
  .changeset/short-seals-invite.md
  .changeset/silent-crews-remember.md
  .changeset/spotty-hats-visit.md
  .changeset/sweet-tools-act.md
  .changeset/swift-nails-suffer.md
  .changeset/thick-pumas-collect.md
  .changeset/warm-jars-exist.md
  .changeset/yellow-humans-rescue.md
  .changeset/young-lemons-develop.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/hubble/src/hubble.ts
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#1290 chore: Update bootstrap.sh script URL
  apps/hubble/www/docs/intro/install.md
Labels: t-docs, t-chore

#1292 docs(hubble): update installation and monitoring docs
  apps/hubble/www/docs/.vitepress/config.ts
  apps/hubble/www/docs/intro/install.md
  apps/hubble/www/docs/intro/monitoring.md
Labels: t-docs

#1296 fix: Handle both 'docker-compose' and 'docker compose'
  .changeset/funny-shoes-return.md
  scripts/hubble.sh
Labels: t-bug

#1300 chore: Set final contract addresses as default
  apps/hubble/src/eth/l2EventsProvider.ts
Labels: t-chore

#1303 fix: Temporarily increase the stream message buffer size
  apps/hubble/src/rpc/bufferedStreamWriter.ts
Labels: t-chore

#1306 [fix] Post migration fixes
  .changeset/warm-nails-type.md
  .github/workflows/ci.yml
  apps/hubble/src/rpc/bufferedStreamWriter.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/jobs/pruneMessagesJob.test.ts
  apps/hubble/src/storage/stores/store.ts
Labels: t-bug

#1307 chore: Release 1.5.1
  .changeset/eighty-jeans-smell.md
  .changeset/funny-shoes-return.md
  .changeset/warm-nails-type.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
Labels: t-chore
