Repository farcasterxyz/hub-monorepo, pull requests merged in 2023-11, with the labels that each got.

#1553 fix: Consolidate to a single subscribe stream in Replicator
  .changeset/short-radios-sparkle.md
  apps/replicator/src/hubReplicator.ts
Labels: t-bug

#1554 chore: Cut Replicator 0.2.5
  .changeset/many-walls-give.md
  .changeset/short-radios-sparkle.md
  apps/replicator/CHANGELOG.md
  apps/replicator/package.json
Labels: t-chore

#1555 fix: disallow empty casts
  .changeset/seven-moose-brake.md
  apps/hubble/src/storage/stores/store.test.ts
  packages/core/src/builders.test.ts
  packages/core/src/validations.test.ts
  packages/core/src/validations.ts
Labels: t-bug

#1559 fix: Fix peer check job not actually starting
  .changeset/tricky-birds-move.md
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/p2p/periodicPeerCheck.ts
Labels: t-bug

#1546 fix: Allow syncTrie to handle names that are substrings
  .changeset/smart-terms-smile.md
  apps/hubble/src/network/sync/syncId.test.ts
  apps/hubble/src/network/sync/syncId.ts
  apps/hubble/src/storage/db/migrations/5.fnameSyncIds.test.ts
  apps/hubble/src/storage/db/migrations/5.fnameSyncIds.ts
  apps/hubble/src/storage/db/migrations/migrations.ts
  packages/core/src/validations.ts
  turbo.json
Labels: t-bug

#1562 fix: Fix watching v2 contract events
  apps/hubble/src/eth/l2EventsProvider.ts
Labels: t-bug

#1560 chore: Post migration changes
  .changeset/seven-moose-brake.md
  .changeset/smart-terms-smile.md
  .changeset/tricky-birds-move.md
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/p2p/periodicPeerCheck.ts
  apps/hubble/src/network/sync/syncId.test.ts
  apps/hubble/src/network/sync/syncId.ts
  apps/hubble/src/storage/db/migrations/5.fnameSyncIds.test.ts
  apps/hubble/src/storage/db/migrations/5.fnameSyncIds.ts
  apps/hubble/src/storage/db/migrations/migrations.ts
  apps/hubble/src/storage/stores/store.test.ts
  packages/core/src/builders.test.ts
  packages/core/src/validations.test.ts
  packages/core/src/validations.ts
  turbo.json
Labels: t-chore

#1563 chore: remove old contract references
  .changeset/silent-cooks-cheat.md
  apps/hubble/src/eth/l2EventsProvider.test.ts
  apps/hubble/src/eth/l2EventsProvider.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/network/sync/syncId.test.ts
  apps/hubble/src/network/sync/syncId.ts
  apps/hubble/src/storage/db/migrations/6.oldContractEvents.test.ts
  apps/hubble/src/storage/db/migrations/6.oldContractEvents.ts
  apps/hubble/src/storage/db/migrations/migrations.ts
  packages/core/src/builders.test.ts
Labels: t-chore

#1564 fix: Dont sync deprecated syncIds
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/network/sync/syncId.test.ts
  apps/hubble/src/network/sync/syncId.ts
Labels: t-bug

#1565 fix: Don't throw if unable to migrate certain rows
  apps/hubble/src/storage/db/migrations/5.fnameSyncIds.ts
  apps/hubble/src/storage/db/migrations/6.oldContractEvents.ts
Labels: t-bug

#1566 fix: commit version after every migration instead of all at once
  apps/hubble/src/hubble.ts
  apps/hubble/src/storage/db/migrations/migrations.test.ts
  apps/hubble/src/storage/db/migrations/migrations.ts
Labels: t-bug

#1568 chore: Release 1.7.1
  .changeset/seven-moose-brake.md
  .changeset/silent-cooks-cheat.md
  .changeset/smart-terms-smile.md
  .changeset/tricky-birds-move.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/replicator/.gitignore
  apps/replicator/src/.gitignore
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
Labels: t-chore

#1572 fix: catch and ignore provider errors during retry
  .changeset/good-shrimps-smile.md
  apps/hubble/src/eth/l2EventsProvider.ts
Labels: t-bug

#1573 chore: release 1.7.2
  .changeset/good-shrimps-smile.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
Labels: t-chore

#1582 chore: release v1.8.0
  .changeset/thick-cherries-kneel.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/hubble/src/hubble.ts
Labels: t-chore

#1583 docs: update release steps
  CONTRIBUTING.md
Labels: t-docs

#1587 feat: add EIP-712 helpers
  .changeset/violet-emus-poke.md
  packages/core/src/eth/contracts/abis/bundler.ts
  packages/core/src/eth/contracts/abis/idGateway.ts
  packages/core/src/eth/contracts/abis/idRegistry.ts
  packages/core/src/eth/contracts/abis/index.ts
  packages/core/src/eth/contracts/abis/keyGateway.ts
  packages/core/src/eth/contracts/abis/keyRegistry.ts
  packages/core/src/eth/contracts/abis/signedKeyRequestValidator.ts
  packages/core/src/eth/contracts/abis/storageRegistry.ts
  packages/core/src/eth/contracts/bundler.ts
  packages/core/src/eth/contracts/idGateway.ts
  packages/core/src/eth/contracts/idRegistry.ts
  packages/core/src/eth/contracts/index.ts
  packages/core/src/eth/contracts/keyGateway.ts
  packages/core/src/eth/contracts/keyRegistry.ts
  packages/core/src/eth/contracts/signedKeyRequestValidator.ts
  packages/core/src/eth/contracts/storageRegistry.ts
  packages/core/src/eth/index.ts
  packages/core/src/signers/eip712Signer.ts
  packages/core/src/signers/ethersEip712Signer.ts
  packages/core/src/signers/ethersV5Eip712Signer.ts
  packages/core/src/signers/testUtils.ts
  packages/core/src/signers/viemLocalEip712Signer.ts
Labels: t-feat

#1591 chore: release new package version
  .changeset/violet-emus-poke.md
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#1592 fix: Backfill reactions and storage allocations in Replicator
  .changeset/heavy-books-suffer.md
  apps/replicator/src/jobs/backfillFidData.ts
  apps/replicator/src/jobs/backfillFidOtherOnChainEvents.ts
  apps/replicator/src/jobs/backfillFidStorageAllocations.ts
Labels: t-bug

#1588 typo: SubmitMessage intro paragraph "Message.encode(msg).finish()"
  apps/hubble/www/docs/docs/httpapi/submitmessage.md
Labels: t-docs

#1561 docs: incorrect request parameters
  apps/hubble/www/docs/docs/httpapi/events.md
Labels: t-docs

#1593 chore: Cut Replicator 0.2.6
  .changeset/heavy-books-suffer.md
  apps/replicator/CHANGELOG.md
  apps/replicator/package.json
Labels: t-chore

#1596 chore: release packages
  .changeset/twelve-trainers-scream.md
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
Labels: t-chore
