Repository farcasterxyz/hub-monorepo, pull requests merged in 2023-10, with the labels that each got.

#1442 [feat] Add migration to clear on chain events and force resync
  .changeset/afraid-spies-visit.md
  apps/hubble/src/eth/l2EventsProvider.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/storage/db/migrations/3.clearEvents.test.ts
  apps/hubble/src/storage/db/migrations/3.clearEvents.ts
  apps/hubble/src/storage/db/migrations/migrations.ts
  apps/hubble/src/storage/stores/onChainEventStore.ts
  apps/hubble/src/storage/stores/onchainEventStore.test.ts
Labels: t-feat

#1444 fix: Set pull_policy to always to ensure hubs always upgrade on restart
  apps/hubble/docker-compose.yml
Labels: t-bug

#1432 fix: fall back to eth_getLogs in event sync
  .changeset/great-parents-occur.md
  .changeset/khaki-dots-cheer.md
  apps/hubble/package.json
  apps/hubble/src/eth/l2EventsProvider.ts
  apps/hubble/src/test/utils.ts
  packages/core/package.json
  yarn.lock
Labels: t-bug

#1450 feat: Globally unique verifications
  .changeset/pink-tables-appear.md
  apps/hubble/src/storage/db/migrations/4.uniqueVerifications.test.ts
  apps/hubble/src/storage/db/migrations/4.uniqueVerifications.ts
  apps/hubble/src/storage/db/migrations/migrations.ts
  apps/hubble/src/storage/db/types.ts
  apps/hubble/src/storage/stores/verificationStore.test.ts
  apps/hubble/src/storage/stores/verificationStore.ts
Labels: t-feat

#1454 fix: Handle potentially missed cached events
  apps/hubble/src/eth/l2EventsProvider.ts
Labels: t-bug

#1453 chore: Release 1.6.0
  .changeset/afraid-spies-visit.md
  .changeset/beige-drinks-prove.md
  .changeset/dry-mayflies-raise.md
  .changeset/forty-cycles-cough.md
  .changeset/great-parents-occur.md
  .changeset/khaki-dots-cheer.md
  .changeset/lucky-donuts-sleep.md
  .changeset/new-pears-divide.md
  .changeset/pink-tables-appear.md
  .changeset/silent-guests-cry.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/hubble/src/hubble.ts
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#1458 fix: Improve logging on unhandled errors
  .changeset/five-olives-drum.md
  .gitignore
  apps/hubble/src/cli.ts
  apps/hubble/www/docs/docs/cli.md
Labels: t-bug

#1449 feat: FIP-8 verifications for contract wallets
  .changeset/orange-crabs-double.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/engine/validation.worker.ts
  apps/hubble/src/test/utils.ts
  packages/core/src/crypto/eip712.ts
  packages/core/src/eth/chains.ts
  packages/core/src/eth/clients.ts
  packages/core/src/eth/index.ts
  packages/core/src/factories.ts
  packages/core/src/index.ts
  packages/core/src/protobufs/generated/message.ts
  packages/core/src/signers/eip712Signer.ts
  packages/core/src/signers/ethersEip712Signer.ts
  packages/core/src/signers/ethersV5Eip712Signer.ts
  packages/core/src/signers/testUtils.ts
  packages/core/src/signers/viemLocalEip712Signer.ts
  packages/core/src/validations.test.ts
  packages/core/src/validations.ts
  packages/hub-nodejs/src/generated/message.ts
  packages/hub-web/src/generated/message.ts
  packages/hub-web/src/generated/rpc.ts
  protobufs/schemas/message.proto
Labels: t-feat

#1463 chore: Update tag used by replicator.sh script
  scripts/replicator.sh
Labels: t-chore

#1461 [feat]: Enable events sync by default
  .changeset/thirty-seals-laugh.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/merkleTrie.ts
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/syncService.test.ts
  apps/hubble/src/test/mocks.ts
  packages/core/src/protobufs/generated/hub_state.ts
  packages/hub-nodejs/src/generated/rpc.ts
  packages/hub-web/src/generated/rpc.ts
  protobufs/schemas/hub_state.proto
Labels: t-feat

#1465 fix: Fix off by one error when inserting into trie
  .changeset/unlucky-toes-bake.md
  apps/hubble/src/network/sync/merkleTrie.test.ts
  apps/hubble/src/network/sync/trieNode.ts
Labels: t-bug

#1466 chore: Update replicator script
  scripts/replicator.sh
Labels: t-chore

#1468 fix: Correct Replicator Docker Compose config and bootstrap script
  .changeset/hip-squids-doubt.md
  apps/replicator/docker-compose.yml
  apps/replicator/package.json
  scripts/replicator.sh
Labels: t-bug, t-devex

#1469 fix: Fix overzealous crontab upgrade entry
  .changeset/brave-dancers-cover.md
  scripts/hubble.sh
Labels: t-bug

#1470 chore: Cut replicator release 0.2.0
  .changeset/hip-squids-doubt.md
  apps/replicator/CHANGELOG.md
  apps/replicator/package.json
Labels: t-chore

#1473 chore: Update Replicator README
  apps/replicator/README.md
Labels: t-chore

#1474 fix: Fetch correct replicator app version from package.json
  .changeset/few-cooks-perform.md
  apps/replicator/src/app.ts
Labels: t-bug

#1475 chore: Cut Replicator 0.2.1
  .changeset/few-cooks-perform.md
  apps/replicator/CHANGELOG.md
  apps/replicator/package.json
Labels: t-chore

#1478 fix: Don't check if hub exposes HTTP port in replicator.sh
  scripts/replicator.sh
Labels: t-bug

#1479 fix: Remove infinite prompt loop in replicator.sh
  scripts/replicator.sh
Labels: t-bug

#1488 chore: Release 1.6.1
  .changeset/brave-dancers-cover.md
  .changeset/five-olives-drum.md
  .changeset/orange-crabs-double.md
  .changeset/orange-rabbits-join.md
  .changeset/sharp-students-explode.md
  .changeset/smooth-berries-mate.md
  .changeset/tame-spies-rule.md
  .changeset/thirty-seals-laugh.md
  .changeset/tidy-dolphins-repeat.md
  .changeset/unlucky-toes-bake.md
  .changeset/wild-tigers-beam.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#1490 fix: Bind Replicator job dashboard to all interfaces
  .changeset/five-roses-mix.md
  apps/replicator/src/web.ts
Labels: t-bug

#1493 fix: Avoid displaying large time estimates for Replicator
  .changeset/warm-peas-shave.md
  apps/replicator/src/hubReplicator.ts
Labels: t-bug

#1495 fix: Persist Grafana across restarts for Replicator Docker Compose
  apps/replicator/docker-compose.yml
  scripts/replicator.sh
Labels: t-bug

#1496 chore: Cut Replicator release 0.2.2
  .changeset/five-roses-mix.md
  .changeset/warm-peas-shave.md
  apps/replicator/CHANGELOG.md
  apps/replicator/package.json
Labels: t-chore

#1497 fix: Don't backfill chain events that were already backfilled
  .changeset/fuzzy-scissors-confess.md
  apps/replicator/src/jobs/backfillFidData.ts
Labels: t-bug

#1498 chore: Release Replicator 0.2.3
  .changeset/fuzzy-scissors-confess.md
  apps/replicator/CHANGELOG.md
  apps/replicator/package.json
Labels: t-chore

#1499 fix: viem client interface, pass clients to builders
  .changeset/nice-bulldogs-return.md
  packages/core/src/builders.ts
  packages/core/src/eth/clients.ts
Labels: t-bug

#1500 chore: Release new package version
  .changeset/nice-bulldogs-return.md
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#1502 fix: Exists check should not crash the hub
  apps/hubble/src/network/sync/merkleTrieWorker.ts
Labels: t-bug

#1503 chore: Release 1.6.2
  .changeset/five-gifts-relate.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
Labels: t-chore

#1511 docs: Update examples to use on-chain signers
  packages/hub-nodejs/examples/README.md
  packages/hub-nodejs/examples/chron-feed/package.json
  packages/hub-nodejs/examples/chron-feed/yarn.lock
  packages/hub-nodejs/examples/make-cast/index.ts
  packages/hub-nodejs/examples/make-cast/package.json
  packages/hub-nodejs/examples/make-cast/yarn.lock
  packages/hub-nodejs/examples/replicate-data-postgres/Brewfile
  packages/hub-nodejs/examples/replicate-data-postgres/README.md
  packages/hub-nodejs/examples/replicate-data-postgres/db.ts
  packages/hub-nodejs/examples/replicate-data-postgres/docker-compose.yml
  packages/hub-nodejs/examples/replicate-data-postgres/hubReplicator.ts
  packages/hub-nodejs/examples/replicate-data-postgres/hubSubscriber.ts
  packages/hub-nodejs/examples/replicate-data-postgres/index.ts
  packages/hub-nodejs/examples/replicate-data-postgres/log.ts
  packages/hub-nodejs/examples/replicate-data-postgres/migrations/001_initial_migration.ts
  packages/hub-nodejs/examples/replicate-data-postgres/migrations/002_mainnet.ts
  packages/hub-nodejs/examples/replicate-data-postgres/package.json
  packages/hub-nodejs/examples/replicate-data-postgres/tsconfig.json
  packages/hub-nodejs/examples/replicate-data-postgres/util.ts
  packages/hub-nodejs/examples/replicate-data-postgres/yarn.lock
  packages/hub-nodejs/examples/write-data/README.md
  packages/hub-nodejs/examples/write-data/abi/IdRegistryABI.ts
  packages/hub-nodejs/examples/write-data/abi/KeyRegistryABI.ts
  packages/hub-nodejs/examples/write-data/abi/SignedKeyRequestMetadataABI.ts
  packages/hub-nodejs/examples/write-data/abi/StorageRegistryABI.ts
  packages/hub-nodejs/examples/write-data/index.ts
  packages/hub-nodejs/examples/write-data/package.json
  packages/hub-nodejs/examples/write-data/yarn.lock
Labels: t-docs

#1512 fix: Correct prompt for HUB_SSL in replicator.sh
  scripts/replicator.sh
Labels: t-bug

#1513 fix: Correct additional typos in replicator.sh
  scripts/replicator.sh
Labels: t-bug

#1520 fix: enable asyncValidation so we don't forward invalid messages on gossip
  .changeset/khaki-shoes-jump.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/p2p/gossipNodeWorker.ts
  apps/hubble/src/test/e2e/gossipNetwork.test.ts
Labels: t-bug

#1521 chore: Release 1.6.3
  .changeset/clever-tools-exercise.md
  .changeset/khaki-shoes-jump.md
  .changeset/late-radios-wonder.md
  .changeset/mean-singers-agree.md
  .changeset/old-students-jam.md
  .changeset/rude-needles-look.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#1522 fix: correctly reportValid more messages and bump up seen ttl
  .changeset/odd-maps-matter.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/p2p/gossipNodeWorker.ts
  apps/hubble/src/test/e2e/gossipNetwork.test.ts
Labels: t-bug

#1523 chore: release 1.6.4
  .changeset/odd-maps-matter.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
Labels: t-chore

#1529 fix: Lower seenTTL to 5 mins to reduce memory consumption
  .changeset/nasty-mirrors-check.md
  apps/hubble/src/network/p2p/gossipNodeWorker.ts
Labels: t-bug

#1534 fix: prevent hub startup if protocol version is expired
  .changeset/neat-flowers-pretend.md
  apps/hubble/src/hubble.ts
Labels: t-bug

#1536 chore: release 1.6.5
  .changeset/calm-tables-scream.md
  .changeset/nasty-mirrors-check.md
  .changeset/neat-flowers-pretend.md
  .changeset/ninety-experts-peel.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#1538 chore: Update minimum hub-nodejs version for Replicator
  .changeset/happy-mugs-allow.md
  apps/replicator/package.json
Labels: t-chore

#1540 chore: Release Replicator 0.2.4
  .changeset/happy-mugs-allow.md
  apps/replicator/CHANGELOG.md
  apps/replicator/package.json
Labels: t-chore

#1541 fix: Fix stale contactInfo caches on SyncEngine
  .changeset/kind-plums-grab.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/syncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
Labels: t-bug

#1542 fix: hubble autoupgrade should ensure dependencies and clean unused docker data
  .changeset/chatty-guests-try.md
  apps/hubble/docker-compose.yml
  scripts/hubble.sh
Labels: t-bug

#1543 chore: Release 1.6.6
  .changeset/breezy-dogs-beg.md
  .changeset/chatty-guests-try.md
  .changeset/kind-plums-grab.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
Labels: t-chore

#1526 feat: support v2 id and key registry contracts
  .changeset/pink-beds-beg.md
  apps/hubble/src/cli.ts
  apps/hubble/src/eth/abis.ts
  apps/hubble/src/eth/l2EventsProvider.test.ts
  apps/hubble/src/eth/l2EventsProvider.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/network/utils/networkConfig.test.ts
  apps/hubble/src/network/utils/networkConfig.ts
  apps/hubble/src/rpc/test/server.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/onChainEventStore.ts
  apps/hubble/src/storage/stores/onchainEventStore.test.ts
  apps/hubble/src/test/utils.ts
  apps/hubble/www/docs/docs/cli.md
  packages/core/src/protobufs/generated/onchain_event.ts
  packages/hub-nodejs/src/generated/onchain_event.ts
  packages/hub-web/src/generated/onchain_event.ts
  protobufs/schemas/onchain_event.proto
Labels: t-feat

#1545 feat: Add ContactInfoContent signing + config toggle for strict validation + StrictNoSign
  .changeset/new-fireants-smile.md
  apps/hubble/src/addon/src/lib.rs
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/p2p/gossipNodeWorker.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/network/utils/networkConfig.test.ts
  apps/hubble/src/network/utils/networkConfig.ts
  apps/hubble/src/rustfunctions.test.ts
  apps/hubble/src/rustfunctions.ts
  apps/hubble/src/storage/jobs/updateNetworkConfigJob.ts
  packages/core/src/protobufs/generated/gossip.ts
  packages/core/src/validations.ts
  packages/hub-web/src/generated/rpc.ts
  protobufs/schemas/gossip.proto
Labels: t-feat

#1547 chore: Release 1.7
  .changeset/new-fireants-smile.md
  .changeset/pink-beds-beg.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#1550 fix: Increase default `CONCURRENCY` for replicator
  apps/replicator/README.md
  scripts/replicator.sh
Labels: t-bug

#1551 chore: Update minimum hub-nodejs version for Replicator
  .changeset/many-walls-give.md
  apps/replicator/package.json
Labels: t-chore

#1552 fix: Fallback to docker-compose if docker install fails
  scripts/hubble.sh
Labels: t-bug
