Repository farcasterxyz/hub-monorepo, pull requests merged in 2023-06, with the labels that each got.

#1004 fix: server no longer hangs due to slow subscribers
  .DS_Store
  .changeset/many-birds-remember.md
  .gitignore
  apps/hubble/.DS_Store
  apps/hubble/src/rpc/bufferedStreamWriter.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/bufferedStreamWriter.test.ts
Labels: t-bug

#1001 chore(hubble): General Store
  .changeset/cool-emus-decide.md
  apps/hubble/src/storage/stores/castStore.test.ts
  apps/hubble/src/storage/stores/castStore.ts
  apps/hubble/src/storage/stores/linkStore.test.ts
  apps/hubble/src/storage/stores/linkStore.ts
  apps/hubble/src/storage/stores/reactionStore.test.ts
  apps/hubble/src/storage/stores/reactionStore.ts
  apps/hubble/src/storage/stores/signerStore.test.ts
  apps/hubble/src/storage/stores/signerStore.ts
  apps/hubble/src/storage/stores/store.test.ts
  apps/hubble/src/storage/stores/store.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
  apps/hubble/src/storage/stores/userDataStore.test.ts
  apps/hubble/src/storage/stores/userDataStore.ts
  apps/hubble/src/storage/stores/verificationStore.test.ts
  apps/hubble/src/storage/stores/verificationStore.ts
  apps/hubble/src/test/e2e/gossipNetwork.test.ts
  apps/hubble/src/utils/versions.test.ts
Labels: t-chore

#1016 chore: fix typos in documentation
  CONTRIBUTING.md
  packages/hub-nodejs/docs/Builders.md
  packages/hub-nodejs/docs/Utils.md
Labels: t-chore

#1010 chore: add peerid @kencodes
  apps/hubble/src/allowedPeers.mainnet.ts
Labels: t-chore

#1024 chore: upgrade dev dependencies
  package.json
  yarn.lock
Labels: t-chore

#1025 chore: update allowedPeers.mainnet.ts
  apps/hubble/src/allowedPeers.mainnet.ts
Labels: t-chore

#1029 chore: remove .DS_Store files
  .github/.DS_Store
  apps/.DS_Store
  packages/.DS_Store
  protobufs/.DS_Store
Labels: t-chore

#1014 feat: Support fname registry server and store user name proofs
  .changeset/funny-masks-explode.md
  apps/hubble/package.json
  apps/hubble/src/cli.ts
  apps/hubble/src/defaultConfig.ts
  apps/hubble/src/eth/ethEventsProvider.ts
  apps/hubble/src/eth/fnameRegistryEventsProvider.test.ts
  apps/hubble/src/eth/fnameRegistryEventsProvider.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/storage/db/nameRegistryEvent.ts
  apps/hubble/src/storage/db/types.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/userDataStore.test.ts
  apps/hubble/src/storage/stores/userDataStore.ts
  apps/hubble/src/storage/stores/utils.ts
  apps/hubble/src/test/mocks.ts
  apps/hubble/src/utils/logger.ts
  packages/core/src/crypto/eip712.test.ts
  packages/core/src/crypto/eip712.ts
  packages/core/src/factories.ts
  packages/core/src/protobufs/generated/hub_event.ts
  packages/core/src/protobufs/generated/hub_state.ts
  packages/core/src/protobufs/generated/message.ts
  packages/core/src/protobufs/generated/username_proof.ts
  packages/core/src/protobufs/index.ts
  packages/hub-nodejs/src/generated/hub_event.ts
  packages/hub-nodejs/src/generated/message.ts
  packages/hub-nodejs/src/generated/username_proof.ts
  packages/hub-web/src/generated/hub_event.ts
  packages/hub-web/src/generated/message.ts
  packages/hub-web/src/generated/request_response.ts
  packages/hub-web/src/generated/rpc.ts
  packages/hub-web/src/generated/username_proof.ts
  protobufs/schemas/hub_event.proto
  protobufs/schemas/hub_state.proto
  protobufs/schemas/username_proof.proto
  yarn.lock
Labels: t-feat

#1031 chore: release 1.3.1
  .changeset/cool-emus-decide.md
  .changeset/curvy-hotels-joke.md
  .changeset/funny-masks-explode.md
  .changeset/many-birds-remember.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#997 chore(hubble): use viem to interact with ethereum
  .changeset/blue-dolls-clap.md
  .changeset/fair-cobras-study.md
  .changeset/great-hats-begin.md
  .github/workflows/ci.yml
  CONTRIBUTING.md
  apps/hubble/jest.config.ts
  apps/hubble/package.json
  apps/hubble/src/eth/abis.ts
  apps/hubble/src/eth/ethEventsProvider.test.ts
  apps/hubble/src/eth/ethEventsProvider.ts
  apps/hubble/src/eth/retryProvider.ts
  apps/hubble/src/eth/watchBlockNumber.ts
  apps/hubble/src/eth/watchContractEvent.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/test/constants.ts
  apps/hubble/src/test/globalSetup.js
  apps/hubble/src/test/globalTeardown.js
  apps/hubble/src/test/mocks.ts
  apps/hubble/src/test/utils.ts
  apps/hubble/src/utils/logger.ts
  apps/hubble/src/utils/periodicTestDataJob.ts
  codecov.yml
  packages/core/package.json
  packages/core/src/signers/index.ts
  packages/core/src/signers/testUtils.ts
  packages/core/src/signers/viemLocalEip712Signer.test.ts
  yarn.lock
Labels: t-chore

#1023 Update allowedPeers.mainnet.ts add Hats.finance node
  apps/hubble/src/allowedPeers.mainnet.ts
Labels: t-chore

#1028 chore: update allowedPeers.mainnet.ts
  apps/hubble/src/allowedPeers.mainnet.ts
Labels: t-chore

#1034 fix: Backfill links in replicate-data-postgres example
  packages/hub-nodejs/examples/replicate-data-postgres/docker-compose.yml
  packages/hub-nodejs/examples/replicate-data-postgres/hubReplicator.ts
Labels: t-bug

#1046 fix: Pin Docker base Node.js image to 20.2
  Dockerfile.hubble
Labels: t-bug

#1049 feat: Switch from name events to username proofs
  .changeset/seven-adults-sing.md
  apps/hubble/src/eth/fnameRegistryEventsProvider.test.ts
  apps/hubble/src/eth/fnameRegistryEventsProvider.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/eventService.test.ts
  apps/hubble/src/rpc/test/userDataService.test.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
  apps/hubble/src/storage/stores/userDataStore.ts
  packages/core/src/protobufs/generated/hub_event.ts
  packages/core/src/protobufs/generated/request_response.ts
  packages/core/src/protobufs/typeguards.ts
  packages/core/src/protobufs/types.ts
  packages/hub-nodejs/src/generated/hub_event.ts
  packages/hub-nodejs/src/generated/request_response.ts
  packages/hub-nodejs/src/generated/rpc.ts
  packages/hub-web/src/generated/hub_event.ts
  packages/hub-web/src/generated/request_response.ts
  packages/hub-web/src/generated/rpc.ts
  protobufs/schemas/hub_event.proto
  protobufs/schemas/request_response.proto
  protobufs/schemas/rpc.proto
Labels: t-feat
