Repository farcasterxyz/hub-monorepo, pull requests merged in 2024-05, with the labels that each got.

#1974 feat: support link compact state messages in shuttle
  .changeset/orange-peas-shop.md
  packages/shuttle/src/shuttle.integration.test.ts
  packages/shuttle/src/shuttle/db.ts
  packages/shuttle/src/utils.ts
Labels: t-feat

#1975 chore: Release 1.12
  .changeset/clean-eagles-reflect.md
  .changeset/fifty-garlics-tickle.md
  .changeset/giant-monkeys-walk.md
  .changeset/hot-wasps-care.md
  .changeset/late-feet-roll.md
  .changeset/lazy-emus-sit.md
  .changeset/lemon-olives-change.md
  .changeset/neat-bikes-live.md
  .changeset/orange-peas-shop.md
  .changeset/poor-wolves-invite.md
  .changeset/proud-plums-design.md
  .changeset/real-pets-walk.md
  .changeset/shiny-carrots-behave.md
  .changeset/shy-steaks-study.md
  .changeset/silly-bobcats-yell.md
  .changeset/silver-timers-collect.md
  .changeset/tiny-waves-breathe.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/hubble/src/hubble.ts
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#1995 chore: Switch to WarpBuild for CI builds
  .github/workflows/ci.yml
Labels: t-chore

#1994 fix: Fix incorrect link message padding
  .changeset/fast-emus-own.md
  apps/hubble/src/addon/src/store/cast_store.rs
  apps/hubble/src/addon/src/store/link_store.rs
  apps/hubble/src/addon/src/store/reaction_store.rs
  apps/hubble/src/addon/src/store/store.rs
  apps/hubble/src/addon/src/store/username_proof_store.rs
  apps/hubble/src/addon/src/store/verification_store.rs
  apps/hubble/src/storage/stores/linkStore.test.ts
Labels: t-bug

#2006 fix: Fix grpcWeb import in hub-web
  .changeset/tame-flowers-fry.md
  package.json
  packages/hub-web/src/generated/rpc.ts
Labels: t-bug

#2007 chore: Release 1.12.2
  .changeset/fast-emus-own.md
  .changeset/few-impalas-call.md
  .changeset/lovely-lizards-build.md
  .changeset/tame-flowers-fry.md
  .changeset/tiny-trains-shout.md
  .github/workflows/ci.yml
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#2019 perf: Remove by signer index
  .changeset/four-baboons-wait.md
  apps/hubble/src/addon/src/store/message.rs
  apps/hubble/src/storage/db/message.test.ts
  apps/hubble/src/storage/db/message.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/jobs/validateOrRevokeMessagesJob.test.ts
  apps/hubble/src/storage/jobs/validateOrRevokeMessagesJob.ts
  apps/hubble/src/storage/stores/linkStore.test.ts
Labels: t-perf
