Repository farcasterxyz/hub-monorepo, pull requests merged in 2024-11, with the labels that each got.

#2395 chore: Release shuttle
  .changeset/itchy-feet-cough.md
  .changeset/nasty-numbers-attack.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2396 Fix: Fallback to RPC in more cases when reconcile stream errors
  .changeset/angry-deers-repair.md
  packages/shuttle/src/shuttle.integration.test.ts
  packages/shuttle/src/shuttle/messageReconciliation.ts
Labels: t-bug

#2397 chore: release hubble v1.16.3 and shuttle v0.6.10
  .changeset/angry-deers-repair.md
  .changeset/nice-lions-tickle.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/hub-nodejs/examples/hello-world/index.ts
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2399 fix(shuttle): Use statsd host from env
  .changeset/shaggy-hounds-scream.md
  packages/shuttle/src/statsd.ts
Labels: t-bug

#2400 chore: Release shuttle version
  .changeset/shaggy-hounds-scream.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2398 fix typos in documentation files
  .github/ISSUE_TEMPLATE/feature.md
  apps/hubble/src/addon/README.md
  apps/hubble/www/docs/docs/messages.md
  apps/hubble/www/docs/intro/hubble.md
  packages/hub-nodejs/docs/Messages.md
  packages/hub-nodejs/docs/README.md
  packages/hub-web/CHANGELOG.md
  packages/hub-web/README.grpcweb.md
  packages/shuttle/CHANGELOG.md
  protobufs/README.md
Labels: t-docs
