Repository farcasterxyz/hub-monorepo, pull requests merged in 2024-10, with the labels that each got.

#2345 fix: Split sync health job into 10 min chunks to limit memory usage
  .changeset/gentle-cobras-jam.md
  apps/hubble/src/network/sync/syncHealthJob.ts
Labels: t-bug

#2347 fix: add request length limit for getAllMessagesBySyncIds
  .changeset/three-zoos-mix.md
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/utils/syncHealth.ts
Labels: t-bug

#2283 feat: export makeMessage fn
  packages/core/src/builders.ts
Labels: t-feat

#2351 fix: restore start/stop time for reconcileMessagesForFid
  .changeset/unlucky-pots-retire.md
  packages/shuttle/src/shuttle/messageReconciliation.ts
Labels: t-bug

#2352 chore: Release 1.15.5
  .changeset/gentle-cobras-jam.md
  .changeset/gentle-turtles-accept.md
  .changeset/giant-jokes-end.md
  .changeset/grumpy-lions-brush.md
  .changeset/honest-students-relax.md
  .changeset/long-mayflies-march.md
  .changeset/many-laws-sing.md
  .changeset/seven-cats-beg.md
  .changeset/three-zoos-mix.md
  .changeset/unlucky-pots-retire.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2353 docs: Update disk space requirements
  apps/hubble/www/docs/intro/install.md
  apps/hubble/www/docs/intro/networks.md
  apps/hubble/www/docs/tutorials/gcp.md
Labels: t-docs

#2357 chore: add metrics for rpc server
  .changeset/cyan-chefs-tickle.md
  apps/hubble/src/rpc/server.ts
Labels: t-chore

#2359 chore: release hubble v1.15.6
  .changeset/cyan-chefs-tickle.md
  .changeset/real-hounds-divide.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
Labels: t-chore

#2358 fix: gracefully handle streaming hangups when the server dies unexpected
  .changeset/fast-peaches-retire.md
  packages/shuttle/src/shuttle.integration.test.ts
  packages/shuttle/src/shuttle/messageReconciliation.ts
Labels: t-bug

#2360 Release shuttle v0.6.6
  .changeset/fast-peaches-retire.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2361 chore: add metrics for http/rpc/streaming requests for grafana
  .changeset/strong-teachers-cover.md
  apps/hubble/grafana/grafana-dashboard.json
  apps/hubble/src/rpc/server.ts
Labels: t-chore

#2362 fix: handle timed out connections from hub event subscriber
  .changeset/blue-windows-travel.md
  packages/shuttle/src/shuttle/hubSubscriber.ts
Labels: t-bug

#2363 chore: release shuttle v0.6.7
  .changeset/blue-windows-travel.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2365 feat: add support for user location in the protocol
  .changeset/serious-bulldogs-sort.md
  apps/hubble/src/rpc/test/userDataService.test.ts
  packages/core/src/protobufs/generated/message.ts
  packages/core/src/validations.test.ts
  packages/core/src/validations.ts
  packages/hub-nodejs/src/generated/message.ts
  packages/hub-web/src/generated/message.ts
  protobufs/schemas/message.proto
Labels: t-feat

#2366 chore: release hubble v1.15.7
  .changeset/serious-bulldogs-sort.md
  .changeset/strong-teachers-cover.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#2369 chore: Release 1.16
  .changeset/red-bags-return.md
  .changeset/tricky-badgers-tan.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/hubble/src/hubble.ts
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2378 fix: validate that fid on username add message matches fid on ens proof
  .changeset/warm-cheetahs-drive.md
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
Labels: t-bug

#2379 chore: release hubble v1.16.1
  .changeset/warm-cheetahs-drive.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
Labels: t-chore

#2370 feat: support social verifications for twitter and github
  .changeset/tall-dots-roll.md
  packages/core/src/protobufs/generated/message.ts
  packages/core/src/validations.test.ts
  packages/core/src/validations.ts
  packages/hub-nodejs/src/generated/message.ts
  packages/hub-web/src/generated/message.ts
  protobufs/schemas/message.proto
Labels: t-feat

#2385 feat: Store backups in separate top-level directory
  .changeset/shaggy-stingrays-rest.md
  apps/hubble/src/addon/src/db/rocksdb.rs
Labels: t-feat

#2387 chore: bump version
  .changeset/shaggy-stingrays-rest.md
  .changeset/tall-dots-roll.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#2371 chore: introduce a pattern to help standardize log tag names
  .changeset/nice-lions-tickle.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/sync/syncHealthJob.ts
  apps/hubble/src/utils/logger.ts
Labels: t-chore

#2391 chore: add event timestamp metric for event subscription monitoring
  .changeset/nasty-numbers-attack.md
  packages/shuttle/src/shuttle/hubSubscriber.ts
Labels: t-chore
