Repository farcasterxyz/hub-monorepo, pull requests merged in 2024-08, with the labels that each got.

#2231 fix: Include peerid in bootstrap multiaddr
  .changeset/metal-meals-beg.md
  apps/hubble/src/bootstrapPeers.mainnet.ts
Labels: t-bug

#2233 chore(shuttle): Release 0.5.10
  .changeset/fresh-dragons-compare.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2234 fix(shuttle): Correct example app to use await
  packages/shuttle/src/example-app/app.ts
Labels: t-bug

#2235 chore: Release 1.14.2
  .changeset/metal-meals-beg.md
  .changeset/modern-cows-argue.md
  .changeset/tame-seas-raise.md
  .changeset/violet-steaks-rule.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
Labels: t-chore

#2223 feat: add a job to measure sync health periodically
  .changeset/six-timers-jog.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/network/sync/syncHealthJob.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/test/mocks.ts
  apps/hubble/src/utils/syncHealth.ts
Labels: t-feat

#2236 feat: make snapshot sync retry and parallelize
  .changeset/clever-owls-approve.md
  apps/hubble/src/hubble.ts
Labels: t-feat, t-perf

#2238 submit missing messages via the sync health job and output richer logs
  .changeset/cuddly-windows-glow.md
  .gitignore
  .vscode/settings.json
  apps/hubble/src/cli.ts
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/network/sync/syncHealthJob.ts
  apps/hubble/src/utils/syncHealth.ts
Labels: t-feat

#2240 fix: fix sync id retrieval for sync health job
  .changeset/unlucky-peas-report.md
  .vscode/settings.json
  apps/hubble/src/addon/src/trie/trie_node.rs
  apps/hubble/src/cli.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/utils/syncHealth.ts
Labels: t-bug

#2241 Fix: Add logging when connecting to a gossip address fails
  apps/hubble/src/network/p2p/gossipNode.ts
Labels: t-bug

#2242 feat: add more counts to sync health job logs
  apps/hubble/src/network/sync/syncHealthJob.ts
Labels: t-feat

#2244 feat: add more logging for sync health job
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/syncHealthJob.ts
  apps/hubble/src/utils/syncHealth.ts
Labels: t-feat

#2245 fix: rename log tag from message to errMessage
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/syncHealthJob.ts
Labels: t-bug

#2246 fix: don't include timestamp in log tags
  apps/hubble/src/network/sync/syncHealthJob.ts
Labels: t-bug

#2249 chore: Release 1.14.3
  .changeset/clever-owls-approve.md
  .changeset/cuddly-windows-glow.md
  .changeset/six-timers-jog.md
  .changeset/unlucky-peas-report.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
Labels: t-chore

#2250 fix: adjust grpc keepalive time to 5s
  .changeset/good-meals-cheat.md
  packages/hub-nodejs/src/client.ts
Labels: t-bug

#2251 fix: Reduce reconciliation default pagination size
  .changeset/good-meals-cheat.md
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
  packages/shuttle/src/shuttle/messageReconciliation.ts
Labels: t-perf

#2257 chore: tweak client-side config to set baseline timeout
  .changeset/olive-bottles-greet.md
  apps/hubble/src/hubble.ts
Labels: t-chore

#2258 fix: Update Node version used in intermediate build step
  Dockerfile.hubble
Labels: t-bug

#2259 chore: switch timeout to 25s
  .changeset/tricky-chairs-own.md
  apps/hubble/src/hubble.ts
  packages/hub-nodejs/src/client.ts
Labels: t-chore

#2261 chore: Revert timeout change
  .changeset/olive-bottles-greet.md
  .changeset/tricky-chairs-own.md
  apps/hubble/src/hubble.ts
  packages/hub-nodejs/src/client.ts
Labels: t-chore

#2262 Revert "fix: adjust grpc keepalive time to 5s (#2250)"
  packages/hub-nodejs/src/client.ts
Labels: t-bug

#2263 chore: revert "fix: Upgrade grpc-js to 1.11 (#2214)"
  apps/hubble/package.json
  apps/hubble/src/rpc/bufferedStreamWriter.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/bufferedStreamWriter.test.ts
  packages/hub-nodejs/package.json
  yarn.lock
Labels: t-chore

#2265 chore: revert "chore: revert "fix: Upgrade grpc-js to 1.11 (#2214)" (#2263)"
  apps/hubble/package.json
  apps/hubble/src/rpc/bufferedStreamWriter.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/bufferedStreamWriter.test.ts
  packages/hub-nodejs/package.json
  yarn.lock
Labels: t-chore

#2256 feat: Implement storage extension FIP
  .changeset/smooth-crews-burn.md
  apps/hubble/src/addon/src/store/store.rs
  apps/hubble/src/rpc/test/server.test.ts
  apps/hubble/src/rustfunctions.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/jobs/pruneMessagesJob.test.ts
  apps/hubble/src/storage/stores/castStore.ts
  apps/hubble/src/storage/stores/linkStore.ts
  apps/hubble/src/storage/stores/reactionStore.ts
  apps/hubble/src/storage/stores/rustStoreBase.ts
  apps/hubble/src/storage/stores/storageCache.test.ts
  apps/hubble/src/storage/stores/storageCache.ts
  apps/hubble/src/storage/stores/storeEventHandler.test.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
  apps/hubble/src/storage/stores/userDataStore.ts
  apps/hubble/src/storage/stores/usernameProofStore.test.ts
  apps/hubble/src/storage/stores/usernameProofStore.ts
  apps/hubble/src/storage/stores/verificationStore.ts
  packages/core/src/factories.ts
  packages/core/src/limits.test.ts
  packages/core/src/limits.ts
  packages/core/src/protobufs/generated/request_response.ts
  packages/hub-nodejs/src/generated/request_response.ts
  packages/hub-web/src/generated/request_response.ts
  protobufs/schemas/request_response.proto
Labels: t-feat

#2267 fix: Move storage unit type helper functions to hub-nodejs package
  .changeset/brown-spies-approve.md
  apps/hubble/src/rpc/test/server.test.ts
  apps/hubble/src/storage/stores/storageCache.test.ts
  apps/hubble/src/storage/stores/storageCache.ts
  apps/hubble/src/storage/stores/storeEventHandler.test.ts
  packages/core/src/limits.ts
Labels: t-feat

#2255 feat: add start and stop time to bulk rpcs with large volumes of data
  .changeset/rude-garlics-doubt.md
  apps/hubble/src/addon/src/lib.rs
  apps/hubble/src/addon/src/store/link_store.rs
  apps/hubble/src/addon/src/store/message.rs
  apps/hubble/src/addon/src/store/store.rs
  apps/hubble/src/addon/src/store/user_data_store.rs
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/bulkService.test.ts
  apps/hubble/src/rustfunctions.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/castStore.ts
  apps/hubble/src/storage/stores/linkStore.ts
  apps/hubble/src/storage/stores/reactionStore.ts
  apps/hubble/src/storage/stores/rustStoreBase.ts
  apps/hubble/src/storage/stores/userDataStore.ts
  apps/hubble/src/storage/stores/verificationStore.ts
  packages/core/src/protobufs/generated/request_response.ts
  packages/core/src/validations.test.ts
  packages/core/src/validations.ts
  packages/hub-nodejs/src/generated/request_response.ts
  packages/hub-nodejs/src/generated/rpc.ts
  packages/hub-web/src/generated/request_response.ts
  packages/hub-web/src/generated/rpc.ts
  protobufs/schemas/request_response.proto
  protobufs/schemas/rpc.proto
Labels: t-feat

#2269 feat: use start and stop time range for reconciliation bulk queries
  .changeset/twelve-lies-type.md
  packages/shuttle/src/shuttle.integration.test.ts
  packages/shuttle/src/shuttle/messageReconciliation.ts
Labels: t-feat

#2270 chore: release 1.14.5
  .changeset/brown-spies-approve.md
  .changeset/rude-garlics-doubt.md
  .changeset/twelve-lies-type.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2271 feat(shuttle): Support event level callback in shuttle
  .changeset/stupid-crews-kneel.md
  packages/shuttle/src/example-app/app.ts
  packages/shuttle/src/example-app/db.ts
  packages/shuttle/src/example-app/migrations/003_onchain_events.ts
  packages/shuttle/src/shuttle.integration.test.ts
  packages/shuttle/src/shuttle/hubEventProcessor.ts
  packages/shuttle/src/shuttle/index.ts
Labels: t-feat

#2278 fix: downgrade node version in CI to fix tests
  .github/workflows/ci.yml
Labels: t-bug

#2275 fix: have reconciliation actually use time bounds
  .changeset/purple-spoons-clap.md
  packages/shuttle/src/shuttle/messageReconciliation.ts
Labels: t-bug

#2282 fix: run sync health over a 30 minute window
  apps/hubble/src/network/sync/syncHealthJob.ts
Labels: t-bug

#2273 Streaming support for sync and reconciliation
  .changeset/early-lizards-remember.md
  apps/hubble/src/cli.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/mock.ts
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/network/sync/syncEnginePerf.test.ts
  apps/hubble/src/network/utils/networkConfig.test.ts
  apps/hubble/src/network/utils/networkConfig.ts
  apps/hubble/src/rpc/bufferedStreamWriter.ts
  apps/hubble/src/rpc/server.ts
  packages/core/package.json
  packages/core/src/protobufs/generated/request_response.ts
  packages/hub-nodejs/package.json
  packages/hub-nodejs/src/client.ts
  packages/hub-nodejs/src/generated/request_response.ts
  packages/hub-nodejs/src/generated/rpc.ts
  packages/hub-nodejs/src/index.ts
  packages/hub-web/src/generated/request_response.ts
  packages/hub-web/src/generated/rpc.ts
  protobufs/schemas/request_response.proto
  protobufs/schemas/rpc.proto
Labels: t-feat

#2284 release x.y.2 packages
  .changeset/early-lizards-remember.md
  packages/core/CHANGELOG.md
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#2285 feat: switch shuttle to use stream fetch
  .changeset/chatty-snails-give.md
  packages/shuttle/package.json
  packages/shuttle/src/shuttle.integration.test.ts
  packages/shuttle/src/shuttle/messageReconciliation.ts
Labels: t-feat

#2286 chore: bump shuttle version
  .changeset/chatty-snails-give.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore
