Repository farcasterxyz/hub-monorepo, pull requests merged in 2024-02, with the labels that each got.

#1639 feat: add text input frame field
  .changeset/smooth-bottles-switch.md
  packages/core/src/protobufs/generated/message.ts
  packages/core/src/validations.test.ts
  packages/core/src/validations.ts
  packages/hub-nodejs/src/generated/message.ts
  packages/hub-web/src/generated/message.ts
  protobufs/schemas/message.proto
Labels: t-feat

#1641 chore: Release 1.9.4
  .changeset/old-dolphins-pump.md
  .changeset/smooth-bottles-switch.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/replicator/CHANGELOG.md
  apps/replicator/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#1643 chore: release 1.9.5
  .changeset/brave-trees-report.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/replicator/CHANGELOG.md
  apps/replicator/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#1644 fix: don't penalize peer score for duplicate messages
  .changeset/calm-mails-notice.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/p2p/gossipNodeWorker.ts
  apps/hubble/src/test/e2e/gossipNetwork.test.ts
Labels: t-bug

#1648 fix: Reduce sync frequency
  .changeset/grumpy-otters-retire.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/periodicSyncJob.ts
Labels: t-bug

#1649 chore: Release 1.9.6
  .changeset/calm-mails-notice.md
  .changeset/grumpy-otters-retire.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
Labels: t-chore

#1651 fix: Additional performance tweaks and logging
  .changeset/wet-hairs-cross.md
  apps/hubble/src/cli.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/periodicSyncJob.ts
  apps/hubble/src/storage/jobs/pruneMessagesJob.ts
  apps/hubble/src/storage/stores/storageCache.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
Labels: t-perf

#1652 chore: fix log level for storage cache logging
  apps/hubble/src/storage/stores/storageCache.ts
Labels: t-chore

#1655 fix: Increase sync trie cache to 64MB
  .changeset/swift-flies-tan.md
  apps/hubble/src/network/sync/merkleTrieWorker.ts
Labels: t-chore

#1653 fix: don't force fetch message count for non-existent fids
  apps/hubble/src/storage/stores/storageCache.ts
  apps/hubble/src/storage/stores/store.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
Labels: t-perf

#1656 chore: Release 1.9.7
  .changeset/slimy-snakes-love.md
  .changeset/swift-flies-tan.md
  .changeset/wet-hairs-cross.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
Labels: t-chore

#1664 feat: Add a new DB for Merkle Trie data
  .changeset/swift-goats-lie.md
  apps/hubble/src/network/sync/merkleTrie.ts
  apps/hubble/src/network/sync/merkleTrieWorker.ts
  apps/hubble/src/network/sync/syncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
Labels: t-feat

#1667 feat: Rename verifications message to support multiple protocols
  .changeset/eighty-papayas-lay.md
  apps/hubble/package.json
  apps/hubble/src/console/warpcastTestCommand.ts
  apps/hubble/src/rpc/httpServer.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/bulkService.test.ts
  apps/hubble/src/rpc/test/httpServer.test.ts
  apps/hubble/src/rpc/test/verificationService.test.ts
  apps/hubble/src/storage/db/message.ts
  apps/hubble/src/storage/db/migrations/4.uniqueVerifications.test.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/jobs/pruneMessagesJob.test.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
  apps/hubble/src/storage/stores/verificationStore.test.ts
  apps/hubble/src/storage/stores/verificationStore.ts
  apps/replicator/src/db.ts
  apps/replicator/src/processors/index.ts
  apps/replicator/src/processors/verification.ts
  apps/replicator/src/util.ts
  packages/core/src/builders.test.ts
  packages/core/src/builders.ts
  packages/core/src/crypto/eip712.test.ts
  packages/core/src/crypto/eip712.ts
  packages/core/src/factories.test.ts
  packages/core/src/factories.ts
  packages/core/src/protobufs/generated/message.ts
  packages/core/src/protobufs/typeguards.ts
  packages/core/src/protobufs/types.ts
  packages/core/src/signers/eip712Signer.ts
  packages/core/src/signers/ethersEip712Signer.ts
  packages/core/src/signers/ethersV5Eip712Signer.ts
  packages/core/src/signers/testUtils.ts
  packages/core/src/signers/viemLocalEip712Signer.ts
  packages/core/src/signers/viemWalletEip712Signer.ts
  packages/core/src/validations.test.ts
  packages/core/src/validations.ts
  packages/core/src/verifications.test.ts
  packages/core/src/verifications.ts
  packages/hub-nodejs/docs/Builders.md
  packages/hub-nodejs/src/generated/message.ts
  packages/hub-web/src/generated/message.ts
  protobufs/schemas/message.proto
  yarn.lock
Labels: t-feat

#1673 feat: Save connected peers in DB
  .changeset/tame-pillows-marry.md
  apps/hubble/src/cli.ts
  apps/hubble/src/defaultConfig.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/p2p/gossipNode.test.ts
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/p2p/gossipNodeDb.test.ts
  apps/hubble/src/network/p2p/gossipNodeWorker.ts
  apps/hubble/src/profile/gossipProfileWorker.js
  apps/hubble/src/storage/db/rocksdb.ts
  apps/hubble/src/storage/db/types.ts
  apps/hubble/src/storage/jobs/gossipContactInfoJob.ts
  apps/hubble/src/test/e2e/hubbleStartup.test.ts
Labels: t-feat

#1675 fix: Use pendingUpdates size to flush updates
  .changeset/twelve-guests-type.md
  apps/hubble/src/network/sync/merkleTrieWorker.ts
Labels: t-bug

#1678 fix: Keep the old message type name for backwards compatibility
  apps/hubble/src/storage/db/message.ts
  apps/hubble/src/storage/jobs/pruneMessagesJob.test.ts
  apps/hubble/src/storage/stores/verificationStore.ts
  apps/replicator/src/processors/index.ts
  apps/replicator/src/processors/verification.ts
  apps/replicator/src/util.ts
  packages/core/src/builders.ts
  packages/core/src/factories.ts
  packages/core/src/protobufs/generated/message.ts
  packages/core/src/protobufs/typeguards.ts
  packages/core/src/protobufs/types.ts
  packages/core/src/validations.ts
  packages/hub-nodejs/src/generated/message.ts
  packages/hub-web/src/generated/message.ts
  protobufs/schemas/message.proto
Labels: t-bug

#1681 fix: increase sync timeout
  .changeset/fluffy-apples-reply.md
  apps/hubble/src/network/sync/syncEngine.ts
Labels: t-bug

#1683 fix: Reduce gossip TTL to 5 mins
  .changeset/lovely-timers-argue.md
  apps/hubble/src/network/p2p/gossipNode.ts
Labels: t-bug

#1684 chore: release 1.9.9
  .changeset/eighty-papayas-lay.md
  .changeset/flat-chairs-smash.md
  .changeset/fluffy-apples-reply.md
  .changeset/fuzzy-needles-decide.md
  .changeset/itchy-flowers-cough.md
  .changeset/lovely-timers-argue.md
  .changeset/swift-goats-lie.md
  .changeset/tame-pillows-marry.md
  .changeset/twelve-guests-type.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/replicator/CHANGELOG.md
  apps/replicator/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#1689 fix: Add 8G heap to docker commands
  .changeset/wild-pots-pay.md
  Dockerfile.hubble
  apps/hubble/docker-compose.yml
Labels: t-bug

#1688 fix: Stop old messages from being broadcast on gossip
  .changeset/big-donuts-glow.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/p2p/gossipNodeWorker.ts
  packages/core/src/protobufs/generated/gossip.ts
  protobufs/schemas/gossip.proto
Labels: t-bug

#1692 chore: Release 1.10
  .changeset/big-donuts-glow.md
  .changeset/early-hotels-reflect.md
  .changeset/fair-ducks-bathe.md
  .changeset/itchy-llamas-act.md
  .changeset/wild-pots-pay.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/hubble/src/hubble.ts
  apps/replicator/CHANGELOG.md
  apps/replicator/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#1694 fix: Small optimizations for merge code
  .changeset/funny-weeks-type.md
  apps/hubble/src/storage/db/onChainEvent.ts
  apps/hubble/src/storage/engine/messageDataBytes.test.ts
  apps/hubble/src/storage/stores/store.test.ts
  apps/hubble/src/storage/stores/store.ts
Labels: t-perf

#1697 chore: Log gossip message delay
  .changeset/rich-dodos-remain.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/test/e2e/gossipNetwork.test.ts
Labels: t-chore

#1695 fix: Run validateOrRevoke only if signer is changed
  .changeset/slimy-buses-deny.md
  apps/hubble/src/storage/jobs/validateOrRevokeMessagesJob.test.ts
  apps/hubble/src/storage/jobs/validateOrRevokeMessagesJob.ts
  packages/core/src/protobufs/generated/hub_state.ts
  protobufs/schemas/hub_state.proto
Labels: t-perf

#1699 chore: additional logging for invalid messages
  apps/hubble/src/hubble.ts
Labels: t-chore

#1700 fix: Fix duplicate message ttl check and reduce fname poll timeout
  .changeset/grumpy-donkeys-allow.md
  .changeset/lucky-radios-poke.md
  apps/hubble/src/eth/fnameRegistryEventsProvider.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/syncEngine.ts
Labels: t-bug

#1701 fix: Add additional checks to prevent contact info duplicates
  .changeset/six-nails-listen.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/syncEngine.ts
Labels: t-bug

#1704 fix: Remove DB_RESET_TOKEN
  .changeset/wicked-eels-cheat.md
  apps/hubble/src/cli.ts
Labels: t-bug

#1707 fix: Handle solana verification removes
  .changeset/small-files-rush.md
  apps/hubble/src/rpc/httpServer.ts
  apps/hubble/src/rpc/test/httpServer.test.ts
  apps/hubble/src/storage/engine/index.test.ts
  packages/core/src/factories.ts
  packages/core/src/validations.test.ts
  packages/core/src/validations.ts
Labels: t-bug

#1709 fix: Increase hub stream buffer size to keep up with faster hub merges
  .changeset/ten-cooks-check.md
  apps/hubble/src/rpc/bufferedStreamWriter.ts
Labels: t-bug

#1722 fix: Fix hub crash from bad message data submit
  .changeset/itchy-fireants-wink.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/storage/db/message.ts
  apps/hubble/src/test/e2e/hubbleNetwork.test.ts
Labels: t-bug

#1723 chore: Release 1.10.2
  .changeset/itchy-fireants-wink.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
Labels: t-chore

#1724 feat: Run Hubble via pm2 process supervisor
  .changeset/gentle-pots-laugh.md
  Dockerfile.hubble
  apps/hubble/package.json
  apps/hubble/pm2.config.js
  yarn.lock
Labels: t-feat

#1725 fix: Allow specifying custom args via pm2 initialization
  .github/workflows/ci.yml
  Dockerfile.hubble
  apps/hubble/docker-compose.yml
  apps/hubble/pm2.config.cjs
Labels: t-bug

#1726 feat: Build Hubble base image on Node.js 21 `slim`
  .github/workflows/ci.yml
  Dockerfile.hubble
Labels: t-feat

#1717 feat: frame message state field
  .changeset/cyan-shirts-punch.md
  packages/core/src/protobufs/generated/message.ts
  packages/core/src/validations.test.ts
  packages/core/src/validations.ts
  packages/hub-nodejs/src/generated/message.ts
  packages/hub-web/src/generated/message.ts
  packages/hub-web/src/generated/rpc.ts
  protobufs/schemas/message.proto
Labels: t-feat

#1731 docs: Update install instructions
  apps/hubble/www/docs/intro/install.md
Labels: t-docs

#1732 docs: Fix display of install instructions
  apps/hubble/www/docs/intro/install.md
Labels: t-docs

#1734 fix: Don't duplicate logs
  apps/hubble/pm2.config.cjs
Labels: t-bug

#1735 chore: bump packages
  .changeset/cyan-shirts-punch.md
  .changeset/four-teachers-move.md
  .changeset/gentle-pots-laugh.md
  .changeset/shaggy-knives-move.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/replicator/CHANGELOG.md
  apps/replicator/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#1736 fix: bs58 dependency
  .changeset/grumpy-camels-rescue.md
  packages/core/package.json
Labels: t-bug, dependencies

#1737 chore: bump packages
  .changeset/grumpy-camels-rescue.md
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#1738 chore: upgrade hub-nodejs
  .changeset/hungry-boats-scream.md
  apps/hubble/package.json
  apps/replicator/package.json
Labels: t-chore, dependencies

#1739 chore: bump package versions
  .changeset/hungry-boats-scream.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/replicator/CHANGELOG.md
  apps/replicator/package.json
Labels: t-chore, dependencies

#1730 docs: Add warning about running `docker compose up` from latest `main`
  apps/hubble/docker-compose.yml
Labels: t-docs

#1640 Fix http api example
  apps/hubble/www/docs/docs/httpapi/httpapi.md
Labels: t-docs

#1740 fix: Deprecate raw iterators in favor of forEach iterators
  .changeset/thin-eels-count.md
  apps/hubble/src/network/sync/merkleTrie.test.ts
  apps/hubble/src/rpc/adminServer.ts
  apps/hubble/src/storage/db/message.test.ts
  apps/hubble/src/storage/db/message.ts
  apps/hubble/src/storage/db/onChainEvent.ts
  apps/hubble/src/storage/db/rocksdb.test.ts
  apps/hubble/src/storage/db/rocksdb.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/jobs/revokeMessagesBySignerJob.ts
  apps/hubble/src/storage/stores/castStore.test.ts
  apps/hubble/src/storage/stores/linkStore.test.ts
  apps/hubble/src/storage/stores/linkStore.ts
  apps/hubble/src/storage/stores/reactionStore.test.ts
  apps/hubble/src/storage/stores/reactionStore.ts
  apps/hubble/src/storage/stores/storageCache.ts
  apps/hubble/src/storage/stores/store.ts
Labels: t-bug

#1741 fix: Increase min timeouts for PM2 configuration
  apps/hubble/pm2.config.cjs
Labels: t-bug

#1743 fix: Add restart_delay to PM2 configuration
  apps/hubble/pm2.config.cjs
Labels: t-bug

#1747 fix: gossip connection timeout
  .changeset/cold-hornets-laugh.md
  apps/hubble/src/cli.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/p2p/gossipNodeWorker.ts
  apps/hubble/src/network/sync/merkleTrie.ts
  apps/hubble/src/utils/statsd.ts
Labels: t-bug

#1752 refactor: add tags to key statsd metrics
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/p2p/gossipNodeWorker.ts
Labels: t-devex

#1754 feat: add transaction_id to frame message
  .changeset/cuddly-wolves-sneeze.md
  packages/core/src/protobufs/generated/message.ts
  packages/core/src/validations.test.ts
  packages/core/src/validations.ts
  packages/hub-nodejs/src/generated/message.ts
  packages/hub-web/src/generated/message.ts
  protobufs/schemas/message.proto
Labels: t-feat

#1756 fix: Use UTC for job scheduling
  .changeset/new-ties-appear.md
  apps/hubble/src/storage/jobs/checkIncomingPortsJob.ts
  apps/hubble/src/storage/jobs/gossipContactInfoJob.ts
  apps/hubble/src/storage/jobs/pruneEventsJob.ts
  apps/hubble/src/storage/jobs/pruneMessagesJob.ts
  apps/hubble/src/storage/jobs/revokeMessagesBySignerJob.ts
  apps/hubble/src/storage/jobs/updateNetworkConfigJob.ts
  apps/hubble/src/storage/jobs/validateOrRevokeMessagesJob.ts
Labels: t-bug

#1758 chore: hubble release
  .changeset/cuddly-wolves-sneeze.md
  .changeset/curly-terms-count.md
  .changeset/dull-mails-kick.md
  .changeset/new-ties-appear.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore
