Repository farcasterxyz/hub-monorepo, pull requests merged in 2024-12, with the labels that each got.

#2414 fix: Switch from Warp to standard runners
  .github/workflows/ci.yml
Labels: t-bug

#2415 fix: typo corrections and path updates
  apps/hubble/src/profile/gossipProfileWorker.js
  apps/hubble/src/profile/gossipProfileWorker.ts
  apps/hubble/src/storage/jobs/dbSnapshotBackupJob.ts
  packages/shuttle/src/shuttle/index.ts
Labels: t-docs

#2406 fix(hubble.sh): handle invalid commands gracefully
  scripts/hubble.sh
Labels: t-feat

#2419 chore: Remove node 20 from CI
  .github/workflows/ci.yml
Labels: t-chore

#2418 chore: Release 1.17
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/hubble/src/hubble.ts
  apps/hubble/src/profile/gossipProfileWorker.js
  apps/hubble/src/rpc/server.ts
Labels: t-chore

#2424 chore: Release shuttle 0.6.12
  .changeset/brave-panthers-walk.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2427 docs: fix broken link CONTRIBUTING.md
  CONTRIBUTING.md
Labels: t-docs

#2428 docs: Fix typo Update README.md
  packages/hub-web/README.md
Labels: t-docs

#2426 bugfix: Fix Issue with Path Quoting Update hubble.sh
  scripts/hubble.sh
Labels: t-bug

#2429 fix: Fix openSUSE ID Check Update hubble-bootstrap.sh
  scripts/hubble-bootstrap.sh
Labels: t-bug

#2430 docs: Correct post commands typos and spelling errors
  apps/hubble/src/network/sync/syncEngine.test.ts
Labels: t-docs

#2433 documentation(hub-web): Added getFnameFromFid to readme
  packages/hub-web/README.md
Labels: t-docs
