Repository farcasterxyz/hub-monorepo, pull requests merged in 2024-09, with the labels that each got.

#2291 chore: remove superfluous warn log and update docs
  .changeset/fluffy-fans-sell.md
  apps/hubble/src/rpc/server.ts
  apps/hubble/www/docs/docs/api.md
Labels: t-docs, t-chore

#2290 feat: add a new metric for tracking count of successfully merged messages
  apps/hubble/src/hubble.ts
Labels: t-chore

#2292 chore: increase sync health span
  apps/hubble/src/network/sync/syncHealthJob.ts
Labels: t-chore

#2293 chore: Release 1.15
  .changeset/fluffy-fans-sell.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/hubble/src/hubble.ts
Labels: t-chore

#2294 chore: add message hash to sync health errors
  apps/hubble/src/network/sync/syncHealthJob.ts
  apps/hubble/src/utils/syncHealth.ts
Labels: t-chore

#2296 chore: increase contact announcement interval
  .changeset/angry-fans-search.md
  apps/hubble/src/hubble.ts
Labels: t-chore

#2303 fix: direct peering data needs to be processed by the worker due to obscure node behavior
  .changeset/mean-tomatoes-beg.md
  apps/hubble/src/cli.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/p2p/gossipNodeWorker.ts
Labels: t-bug

#2304 chore: release hubble v1.15.1
  .changeset/angry-fans-search.md
  .changeset/mean-tomatoes-beg.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
Labels: t-chore

#2302 chore: add more metrics to hub stream reader
  .changeset/rude-dogs-whisper.md
  packages/shuttle/src/shuttle/hubSubscriber.ts
Labels: t-chore

#2307 chore: add more tags to event stream metrics
  .changeset/shiny-jobs-deliver.md
  packages/shuttle/src/shuttle/eventStream.ts
Labels: t-chore

#2309 chore: add metric to track events received by kind
  .changeset/giant-maps-remain.md
  packages/shuttle/src/shuttle/eventStream.ts
Labels: t-chore

#2310 chore: release shuttle v0.6.3
  .changeset/giant-maps-remain.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2298 feat: request missing on chain events on error
  .changeset/gold-geckos-remain.md
  apps/hubble/src/eth/l2EventsProvider.test.ts
  apps/hubble/src/eth/l2EventsProvider.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/rpc/test/httpServer.test.ts
  apps/hubble/src/rpc/test/messageService.test.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/onChainEventStore.ts
  packages/core/src/errors.ts
Labels: t-feat

#2314 fix: Fix flaky test
  apps/hubble/src/storage/stores/storageCache.test.ts
Labels: t-bug

#2313 feat: support bulk message RPC
  .changeset/pink-drinks-brush.md
  apps/hubble/src/rpc/server.ts
  apps/hubble/www/docs/docs/api.md
  packages/core/src/protobufs/generated/request_response.ts
  packages/hub-nodejs/src/generated/request_response.ts
  packages/hub-nodejs/src/generated/rpc.ts
  packages/hub-web/src/generated/request_response.ts
  packages/hub-web/src/generated/rpc.ts
  protobufs/schemas/request_response.proto
  protobufs/schemas/rpc.proto
Labels: t-feat

#2316 chore: bump version
  .changeset/gold-geckos-remain.md
  .changeset/pink-drinks-brush.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#2320 chore: upgrade hub-nodejs dependency so interfaces align
  .changeset/fast-bugs-fetch.md
  packages/shuttle/package.json
Labels: t-chore

#2321 chore: release shuttle v0.6.4
  .changeset/fast-bugs-fetch.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2323 chore: add start time and stop time to sync health logs
  .changeset/fifty-news-rest.md
  apps/hubble/src/network/sync/syncHealthJob.ts
Labels: t-chore

#2325 chore: add more message details to sync health errors
  .changeset/short-squids-sparkle.md
  apps/hubble/src/network/sync/syncHealthJob.ts
Labels: t-chore

#2326 feat: pull missing messages into sync trie via sync health job
  .changeset/fast-icons-admire.md
  apps/hubble/src/network/sync/syncHealthJob.ts
Labels: t-feat

#2327 chore: release hubble v1.15.3
  .changeset/fast-icons-admire.md
  .changeset/fifty-news-rest.md
  .changeset/short-squids-sparkle.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
Labels: t-chore

#2324 feat: add the ability to provide ip addresses to sync health job
  .changeset/real-dodos-lay.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/syncHealthJob.ts
  apps/hubble/src/test/mocks.ts
Labels: t-feat

#2330 chore: release hubble v1.15.4
  .changeset/real-dodos-lay.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
Labels: t-chore

#2331 fix: Ignore rate limits for local/loopback IP traffic
  .changeset/long-mayflies-march.md
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/utils/rateLimits.test.ts
  apps/hubble/src/utils/rateLimits.ts
Labels: t-bug

#2335 fix: Ignore local/loopback traffic in IP connection limiter
  .changeset/gentle-turtles-accept.md
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/eventService.test.ts
  apps/hubble/src/utils/rateLimits.ts
Labels: t-bug

#2336 chore: add contact info to sync health logs
  .changeset/seven-cats-beg.md
  apps/hubble/src/network/sync/syncHealthJob.ts
Labels: t-chore

#2338 fix: make the contact info logs for the sync health job richer
  apps/hubble/src/network/sync/syncHealthJob.ts
Labels: t-bug

#2342 feat: Add `--announce-rpc-port` flag
  .changeset/giant-jokes-end.md
  apps/hubble/src/cli.ts
  apps/hubble/src/hubble.ts
  apps/hubble/www/docs/docs/cli.md
Labels: t-feat
