Repository farcasterxyz/hub-monorepo, pull requests merged in 2024-07, with the labels that each got.

#2118 chore: add stats for bundle message delays, stale contact info
  .changeset/dull-dancers-float.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/test/e2e/hubbleNetwork.test.ts
  apps/hubble/src/test/mocks.ts
Labels: t-chore

#2119 fix: validate gossip message for clock skew
  .changeset/silent-planes-promise.md
  apps/hubble/src/hubble.ts
Labels: t-bug

#2120 feat: add unique peer map to sync engine to represent current active peers
  .changeset/popular-shoes-bathe.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/utils/ttl_map.test.ts
  apps/hubble/src/utils/ttl_map.ts
Labels: t-feat

#2121 fix: update start time to farcaster time when submitting message bundles from sync
  apps/hubble/src/network/sync/syncEngine.ts
Labels: t-bug

#2112 apps/hubble: fix docker-compose.yml warning
  apps/hubble/docker-compose.yml
Labels: t-bug

#2133 fix(shuttle): Handle missing group key
  .changeset/calm-rings-lie.md
  packages/shuttle/src/shuttle/eventStream.ts
Labels: t-bug

#2129 fix(hubble): hub operator fid is not set docker compose
  .changeset/new-kids-provide.md
  apps/hubble/docker-compose.yml
Labels: t-bug

#2135 chore: Update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: t-chore

#2136 chore(shuttle) Release 0.4.3
  .changeset/calm-rings-lie.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2139 feat(shuttle): Allow RedisClient's client to be a cluster instance
  .changeset/smart-garlics-sniff.md
  packages/shuttle/src/shuttle/redis.ts
Labels: t-feat

#2140 chore(shuttle): Release 0.4.4
  .changeset/smart-garlics-sniff.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2142 feat: add hub service agreement - there will be no rewards for running a hub
  .changeset/poor-queens-lick.md
  scripts/hubble.sh
Labels: t-feat

#2145 fix: Increase message threshold to reduce snapshot bandwidth usage
  .changeset/light-cobras-judge.md
  apps/hubble/src/defaultConfig.ts
Labels: t-bug

#2146 chore: release 1.13.6
  .changeset/dull-dancers-float.md
  .changeset/light-cobras-judge.md
  .changeset/new-kids-provide.md
  .changeset/poor-queens-lick.md
  .changeset/popular-shoes-bathe.md
  .changeset/silent-planes-promise.md
  .changeset/silver-wombats-rule.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
Labels: t-chore

#2147 feat(shuttle): Allow changing subscriber batch size or flush interval
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
  packages/shuttle/src/shuttle/hubSubscriber.ts
Labels: t-feat

#2154 fix: force acknowledgement of no rewards for existing hubs
  scripts/hubble.sh
Labels: t-bug

#2155 chore: remove unnecessary foundry version pin in ci
  .github/workflows/ci.yml
Labels: t-devex

#2156 chore: upgrade turborepo to v2
  package.json
  turbo.json
  yarn.lock
Labels: t-devex

#2158 chore: upgrade husky to v9
  .husky/pre-commit
  package.json
  yarn.lock
Labels: t-devex

#2141 feat: make message processor handle removals for compact state explicitly, warn on mismatching deletes
  .changeset/silver-weeks-eat.md
  packages/shuttle/src/shuttle.integration.test.ts
  packages/shuttle/src/shuttle/hubEventProcessor.ts
  packages/shuttle/src/shuttle/messageProcessor.ts
Labels: t-feat, t-perf

#2161 chore: fix unhandled type error in tests
  apps/hubble/src/storage/engine/messageDataBytes.test.ts
Labels: t-chore

#2165 chore: upgrade dockerfile to use node 22
  .github/workflows/ci.yml
  Dockerfile.hubble
Labels: t-devex

#2168 chore(shuttle): Release 0.5.2
  .changeset/silver-weeks-eat.md
  .changeset/warm-stingrays-crash.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2169 fix(shuttle): Fix broken build for 0.5.2
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-bug

#2163 chore: upgrade rimraf to 6
  Dockerfile.hubble
  package.json
  yarn.lock
Labels: t-devex

#2171 feat: Assign shards using jump consistent hashing
  .changeset/few-points-fold.md
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/eventService.test.ts
  apps/hubble/src/utils/jumpConsistentHash.ts
Labels: t-feat

#2174 feat: increase frame message URL max length
  .changeset/red-eels-move.md
  packages/core/src/validations.test.ts
  packages/core/src/validations.ts
Labels: t-feat

#2177 chore: Release 0.5.4
  .changeset/dry-insects-design.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2178 fix(shuttle): Switch before/after processing hooks to use batches
  .changeset/silver-coins-search.md
  packages/shuttle/src/shuttle/eventStream.ts
  packages/shuttle/src/shuttle/hubSubscriber.ts
Labels: t-bug

#2179 chore(shuttle): Release 0.5.5
  .changeset/silver-coins-search.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2183 chore(shuttle): Stop recording stream size
  .changeset/gorgeous-taxis-kiss.md
  packages/shuttle/src/shuttle/eventStream.ts
Labels: t-chore

#2185 perf(shuttle): Trim stream at regular intervals instead of every iteration
  .changeset/dry-foxes-appear.md
  packages/shuttle/README.md
  packages/shuttle/src/shuttle/eventStream.ts
Labels: t-perf

#2186 chore(shuttle): Release 0.5.6
  .changeset/dry-foxes-appear.md
  .changeset/gorgeous-taxis-kiss.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2188 chore: release 1.13.7
  .changeset/few-points-fold.md
  .changeset/red-eels-move.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
Labels: t-chore

#2175 fix(docs): Improved GCP tutorial
  apps/hubble/www/docs/assets/images/gcp_compute_engine_api.png
  apps/hubble/www/docs/assets/images/gcp_project_id.png
  apps/hubble/www/docs/tutorials/gcp.md
Labels: t-docs

#2193 fix: force acknowledgement of no rewards for existing hubs
  scripts/hubble.sh
Labels: t-chore

#2194 fix: update hub storage requirement to 200 GB
  .changeset/tiny-elephants-roll.md
  apps/hubble/www/docs/intro/install.md
  apps/hubble/www/docs/tutorials/gcp.md
Labels: t-bug

#2195 feat: Expose event id functions
  .changeset/old-fireants-burn.md
  apps/hubble/src/console/console.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
  packages/core/src/time.ts
Labels: t-feat

#2196 fix(example): fix the argument for makeLinkRemove when removing a follow
  packages/hub-nodejs/examples/write-data/index.ts
Labels: t-docs

#2191 chore: upgrade libp2p to 0.44.0
  .changeset/stupid-pianos-doubt.md
  apps/hubble/package.json
  apps/hubble/src/network/p2p/connectionFilter.test.ts
  apps/hubble/src/network/p2p/connectionFilter.ts
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/p2p/gossipNodeWorker.ts
  yarn.lock
Labels: t-devex

#2197 fix: on conflict criteria is ambiguous and cannot be used for upsert
  .changeset/tidy-apricots-unite.md
  packages/shuttle/src/shuttle/messageProcessor.ts
Labels: t-bug

#2198 fix: ack script
  scripts/hubble.sh
Labels: t-bug

#2199 chore: release 1.13.8
  .changeset/old-fireants-burn.md
  .changeset/stupid-pianos-doubt.md
  .changeset/tidy-apricots-unite.md
  .changeset/tiny-elephants-roll.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2124 fix: full state events should not include deletes
  .changeset/sixty-shoes-occur.md
  apps/hubble/src/addon/src/store/store.rs
  apps/hubble/src/storage/stores/linkStoreCompactState.test.ts
Labels: t-bug

#2204 [fix] Fix race condition with earliest ts hash calculation
  .changeset/violet-poets-camp.md
  apps/hubble/src/addon/src/lib.rs
  apps/hubble/src/addon/src/store/message.rs
  apps/hubble/src/addon/src/store/mod.rs
  apps/hubble/src/addon/src/store/storage_cache.rs
  apps/hubble/src/addon/src/store/store.rs
  apps/hubble/src/addon/src/store/store_event_handler.rs
  apps/hubble/src/addon/src/store/utils.rs
  apps/hubble/src/rustfunctions.ts
  apps/hubble/src/storage/stores/storageCache.test.ts
  apps/hubble/src/storage/stores/storageCache.ts
  apps/hubble/src/storage/stores/storeEventHandler.test.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
Labels: t-bug

#2207 fix: Fix incorrect target fid check for link messages older than the compact state
  .changeset/rare-pots-look.md
  apps/hubble/src/addon/src/store/store.rs
  apps/hubble/src/storage/stores/linkStoreCompactState.test.ts
Labels: t-bug

#2203 fix: do not let deleted fname events allow old fname events to be re-added
  .changeset/serious-falcons-drum.md
  apps/hubble/src/addon/src/store/name_registry_events.rs
  apps/hubble/src/addon/src/store/user_data_store.rs
  apps/hubble/src/eth/fnameRegistryEventsProvider.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/storage/db/nameRegistryEvent.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/stores/userDataStore.test.ts
Labels: t-bug

#2208 chore: Release 1.14
  .changeset/rare-pots-look.md
  .changeset/serious-falcons-drum.md
  .changeset/sixty-shoes-occur.md
  .changeset/violet-poets-camp.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/hubble/src/hubble.ts
Labels: t-chore

#2213 fix: Do not validate messages in shuttle by default
  .changeset/mighty-pants-knock.md
  packages/shuttle/src/shuttle.integration.test.ts
  packages/shuttle/src/shuttle/hubEventProcessor.ts
Labels: t-perf

#2214 fix: Upgrade grpc-js to 1.11
  .changeset/gold-hounds-double.md
  apps/hubble/package.json
  apps/hubble/src/rpc/bufferedStreamWriter.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/bufferedStreamWriter.test.ts
  packages/hub-nodejs/package.json
  yarn.lock
Labels: t-bug

#2216 Release shuttle 0.5.8
  .changeset/gold-hounds-double.md
  .changeset/mighty-pants-knock.md
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2215 perf: Add message merge timing at the store level
  .changeset/late-bananas-lick.md
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/rustStoreBase.ts
Labels: t-perf

#2218 Revert "[fix] Fix race condition with earliest ts hash calculation (#…
  apps/hubble/src/addon/src/lib.rs
  apps/hubble/src/addon/src/store/message.rs
  apps/hubble/src/addon/src/store/mod.rs
  apps/hubble/src/addon/src/store/storage_cache.rs
  apps/hubble/src/addon/src/store/store.rs
  apps/hubble/src/addon/src/store/store_event_handler.rs
  apps/hubble/src/addon/src/store/utils.rs
  apps/hubble/src/rustfunctions.ts
  apps/hubble/src/storage/stores/storageCache.test.ts
  apps/hubble/src/storage/stores/storageCache.ts
  apps/hubble/src/storage/stores/storeEventHandler.test.ts
  apps/hubble/src/storage/stores/storeEventHandler.ts
Labels: t-bug

#2219 chore: Release 1.14.1
  .changeset/gold-hounds-double.md
  .changeset/late-bananas-lick.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
Labels: t-chore

#2224 chore: upgrade libp2p all the way
  .changeset/tame-seas-raise.md
  apps/hubble/package.json
  apps/hubble/src/cli.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/p2p/connectionFilter.test.ts
  apps/hubble/src/network/p2p/connectionFilter.ts
  apps/hubble/src/network/p2p/gossipNode.test.ts
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/p2p/gossipNodeDb.test.ts
  apps/hubble/src/network/p2p/gossipNodeWorker.ts
  apps/hubble/src/network/p2p/protocol.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/network/utils/factories.test.ts
  apps/hubble/src/network/utils/factories.ts
  apps/hubble/src/test/mocks.ts
  packages/core/package.json
  tsconfig.json
  yarn.lock
Labels: t-chore, dependencies

#2228 fix(shuttle): Don't throttle CPU when there are no events to process
  .changeset/friendly-horses-hide.md
  packages/shuttle/src/shuttle/eventStream.ts
Labels: t-bug

#2229 fix: Always assign on-chain events to shard 0 for linear ordering
  .changeset/modern-cows-argue.md
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/eventService.test.ts
  packages/shuttle/docker-compose.yml
Labels: t-bug

#2230 chore(shuttle): Release 0.5.9
  .changeset/friendly-horses-hide.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore
