Repository farcasterxyz/hub-monorepo, pull requests merged in 2024-03, with the labels that each got.

#1760 fix: Log directly from worker threads
  .changeset/smooth-donkeys-repeat.md
  apps/hubble/src/cli.ts
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/p2p/gossipNodeWorker.ts
  apps/hubble/src/network/sync/merkleTrie.ts
  apps/hubble/src/network/sync/merkleTrieWorker.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/utils/logger.ts
Labels: t-chore

#1768 tests: Simplify ci tests
  .changeset/soft-emus-chew.md
  .github/workflows/ci.yml
  apps/hubble/hubble.code-workspace
  apps/hubble/package.json
Labels: t-devex

#1759 fix: hub crash on contract events
  apps/hubble/src/eth/l2EventsProvider.ts
  apps/hubble/src/eth/watchBlockNumber.ts
  apps/hubble/src/eth/watchContractEvent.ts
  apps/hubble/src/hubble.ts
Labels: t-bug

#1771 fix: calculate approx size for DB correctly
  .changeset/sweet-geckos-sip.md
  apps/hubble/src/addon/Cargo.lock
  apps/hubble/src/addon/Cargo.toml
  apps/hubble/src/addon/src/db/rocksdb.rs
  apps/hubble/src/addon/src/lib.rs
  apps/hubble/src/network/sync/merkleTrieWorker.ts
  apps/hubble/src/rustfunctions.ts
  apps/hubble/src/storage/db/rocksdb.ts
Labels: t-bug

#1773 chore: release 1.10.9
  .changeset/large-hotels-watch.md
  .changeset/soft-emus-chew.md
  .changeset/sweet-geckos-sip.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
Labels: t-chore

#1775 perf: Move userdata store to rust
  .changeset/swift-bobcats-promise.md
  apps/hubble/src/addon/src/lib.rs
  apps/hubble/src/addon/src/store/message.rs
  apps/hubble/src/addon/src/store/mod.rs
  apps/hubble/src/addon/src/store/name_registry_events.rs
  apps/hubble/src/addon/src/store/reaction_store.rs
  apps/hubble/src/addon/src/store/store.rs
  apps/hubble/src/addon/src/store/user_data_store.rs
  apps/hubble/src/rustfunctions.ts
  apps/hubble/src/storage/stores/reactionStore.ts
  apps/hubble/src/storage/stores/rustStoreBase.ts
  apps/hubble/src/storage/stores/userDataStore.ts
Labels: t-perf

#1776 chore: Set maximum & default page size for HTTP API requests to 1K
  .changeset/dry-apples-give.md
  apps/hubble/src/rpc/httpServer.ts
  apps/hubble/www/docs/docs/httpapi/httpapi.md
Labels: t-docs, t-chore

#1777 docs: Add note that Postgres 15+ is required
  apps/replicator/README.md
Labels: t-docs

#1770 fix: replicator Unicode error
  .changeset/yellow-guests-turn.md
  Dockerfile.replicator
  apps/replicator/docker-compose.yml
  apps/replicator/src/processors/index.ts
  apps/replicator/src/processors/verification.ts
  apps/replicator/src/util.ts
  apps/replicator/src/worker.ts
  packages/core/src/factories.ts
Labels: t-bug

#1779 fix: solana base58 instead of text decode to avoid null bytes
  apps/replicator/CHANGELOG.md
  apps/replicator/package.json
  apps/replicator/src/util.ts
Labels: t-bug

#1782 fix: Run prune job in thread
  .changeset/curvy-turkeys-allow.md
  apps/hubble/src/addon/src/store/store.rs
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/jobs/pruneMessagesJob.ts
Labels: t-perf

#1783 chore: Move get_merge_conflicts to trait default impl
  .changeset/fluffy-experts-sleep.md
  apps/hubble/src/addon/src/store/store.rs
Labels: t-chore

#1785 fix: When creating a snapshot, tar file first to speedup
  .changeset/happy-birds-admire.md
  .github/workflows/ci.yml
  Dockerfile.hubble
  apps/hubble/src/addon/Cargo.lock
  apps/hubble/src/addon/Cargo.toml
  apps/hubble/src/addon/src/db/rocksdb.rs
  apps/hubble/src/addon/src/lib.rs
  apps/hubble/src/hubble.ts
  apps/hubble/src/rustfunctions.ts
  apps/hubble/tsconfig.json
Labels: t-devex

#1786 test: Setup testing in rust
  .changeset/proud-cherries-turn.md
  apps/hubble/package.json
  apps/hubble/src/addon/src/store/name_registry_events.rs
  apps/hubble/src/addon/src/store/utils.rs
  apps/hubble/src/storage/db/migrations/5.fnameSyncIds.test.ts
Labels: rust

#1781 fix(replicator): updateTableMetrics is using too much postgresql CPU
  .changeset/forty-snakes-try.md
  apps/replicator/src/db.ts
  apps/replicator/src/hubReplicator.ts
Labels: t-bug

#1788 chore: Update docker-compose.yml to avoid port conflicts
  apps/hubble/docker-compose.yml
Labels: t-chore

#1789 chore: Update GH Actions versions to avoid deprecation warnings
  .github/workflows/ci.yml
Labels: t-chore

#1790 fix: Increase read timeout for Fname Registry server requests 2.5s → 5s
  .changeset/great-wolves-push.md
  apps/hubble/src/eth/fnameRegistryEventsProvider.ts
Labels: t-bug

#1791 docs: Fix broken link on http api
  .changeset/sharp-donuts-deliver.md
  apps/hubble/www/.vitepress/cache/deps_temp_f064fcac/package.json
  apps/hubble/www/.vitepress/cache/deps_temp_f064fcac/vue.js
  apps/hubble/www/.vitepress/cache/deps_temp_f064fcac/vue.js.map
  apps/hubble/www/docs/.vitepress/config.ts
  apps/hubble/www/package.json
Labels: t-docs

#1793 fix: Change restart policy to `always`
  .changeset/funny-tables-begin.md
  apps/hubble/docker-compose.yml
Labels: t-bug

#1794 fix: Resolve more deprecation warnings in GitHub Actions
  .github/workflows/ci.yml
Labels: t-docs

#1795 fix: Resolve more deprecation warnings in GitHub Actions
  .github/workflows/ci.yml
Labels: t-bug

#1796 fix: Reduce default chunk size from 10000 to 9999
  .changeset/many-suns-compete.md
  apps/hubble/src/cli.ts
Labels: t-bug

#1787 fix: Don't return '0x' for empty addresses.
  .changeset/violet-falcons-enjoy.md
  apps/hubble/src/rpc/httpServer.ts
  apps/hubble/src/rpc/test/httpServer.test.ts
Labels: t-bug

#1801 fix: Catch and log errors if conflict messages are not found while merging
  .changeset/nine-pugs-sparkle.md
  apps/hubble/src/addon/src/store/store.rs
  apps/hubble/src/storage/stores/store.ts
Labels: t-bug

#1803 chore: release 1.10.10
  .changeset/curvy-turkeys-allow.md
  .changeset/dry-apples-give.md
  .changeset/fluffy-experts-sleep.md
  .changeset/forty-snakes-try.md
  .changeset/funny-tables-begin.md
  .changeset/great-wolves-push.md
  .changeset/happy-birds-admire.md
  .changeset/healthy-masks-sort.md
  .changeset/many-suns-compete.md
  .changeset/mighty-cups-pull.md
  .changeset/new-rivers-tap.md
  .changeset/nine-pugs-sparkle.md
  .changeset/proud-cherries-turn.md
  .changeset/sharp-donuts-deliver.md
  .changeset/swift-bobcats-promise.md
  .changeset/violet-falcons-enjoy.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/replicator/CHANGELOG.md
  apps/replicator/package.json
Labels: t-chore

#1807 feat: add address to frame message
  .changeset/perfect-cameras-relax.md
  apps/hubble/src/addon/src/proto/protobufs.rs
  packages/core/src/protobufs/generated/message.ts
  packages/core/src/validations.test.ts
  packages/core/src/validations.ts
  packages/hub-nodejs/src/generated/message.ts
  packages/hub-web/src/generated/message.ts
  packages/hub-web/src/generated/rpc.ts
  protobufs/schemas/message.proto
Labels: t-feat

#1808 chore: release packages
  .changeset/perfect-cameras-relax.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#1806 perf: migrate link store to Rust
  .changeset/rare-carpets-itch.md
  apps/hubble/src/addon/src/lib.rs
  apps/hubble/src/addon/src/store/link_store.rs
  apps/hubble/src/addon/src/store/message.rs
  apps/hubble/src/addon/src/store/mod.rs
  apps/hubble/src/addon/src/store/reaction_store.rs
  apps/hubble/src/addon/src/store/store.rs
  apps/hubble/src/rustfunctions.ts
  apps/hubble/src/storage/stores/linkStore.ts
Labels: t-perf

#1798 chore: Migrate verifications store to rust
  .changeset/famous-poets-speak.md
  apps/hubble/src/addon/src/lib.rs
  apps/hubble/src/addon/src/store/message.rs
  apps/hubble/src/addon/src/store/mod.rs
  apps/hubble/src/addon/src/store/name_registry_events.rs
  apps/hubble/src/addon/src/store/store.rs
  apps/hubble/src/addon/src/store/verification_store.rs
  apps/hubble/src/rustfunctions.ts
  apps/hubble/src/storage/db/migrations/4.uniqueVerifications.test.ts
  apps/hubble/src/storage/stores/verificationStore.test.ts
  apps/hubble/src/storage/stores/verificationStore.ts
Labels: t-chore

#1804 feat: Generate grpc rust code from protobufs
  .changeset/fluffy-bulldogs-vanish.md
  apps/hubble/src/addon/Cargo.lock
  apps/hubble/src/addon/Cargo.toml
  apps/hubble/src/addon/build.rs
  apps/hubble/src/addon/src/db/rocksdb.rs
  apps/hubble/src/addon/src/lib.rs
  apps/hubble/src/addon/src/proto/protobufs.rs
  apps/hubble/src/addon/src/store/message.rs
  apps/hubble/src/addon/src/store/store_event_handler.rs
  apps/hubble/src/addon/src/store/utils.rs
  apps/hubble/src/storage/engine/index.ts
Labels: t-devex

#1826 perf: Move username proof store to rust
  .changeset/lovely-islands-sit.md
  apps/hubble/src/addon/src/lib.rs
  apps/hubble/src/addon/src/store/mod.rs
  apps/hubble/src/addon/src/store/store.rs
  apps/hubble/src/addon/src/store/username_proof_store.rs
  apps/hubble/src/addon/src/store/verification_store.rs
  apps/hubble/src/rustfunctions.ts
  apps/hubble/src/storage/stores/usernameProofStore.test.ts
  apps/hubble/src/storage/stores/usernameProofStore.ts
Labels: t-perf

#1827 perf: Throttle prune job
  .changeset/orange-starfishes-fry.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/storage/jobs/pruneMessagesJob.test.ts
  apps/hubble/src/storage/jobs/pruneMessagesJob.ts
Labels: t-perf

#1830 feat: Log hub restarts
  .changeset/serious-cats-compete.md
  apps/hubble/src/cli.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/storage/jobs/checkFarcasterVersionJob.ts
  apps/hubble/src/storage/jobs/updateNetworkConfigJob.ts
  apps/hubble/src/test/e2e/hubbleNetwork.test.ts
  apps/hubble/src/test/e2e/hubbleStartup.test.ts
Labels: t-feat

#1834 chore: Release 1.11
  .changeset/famous-poets-speak.md
  .changeset/fluffy-bulldogs-vanish.md
  .changeset/lovely-islands-sit.md
  .changeset/orange-starfishes-fry.md
  .changeset/popular-garlics-warn.md
  .changeset/popular-suits-joke.md
  .changeset/rare-carpets-itch.md
  .changeset/serious-cats-compete.md
  .changeset/shaggy-bags-film.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/hubble/src/hubble.ts
Labels: t-chore

#1829 feat(hubble): update s3 snapshot metadata to include database statistics
  .changeset/six-bats-grab.md
  apps/hubble/package.json
  apps/hubble/src/cli.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/merkleTrie.ts
  apps/hubble/src/utils/snapshot.ts
  apps/hubble/www/docs/docs/cli.md
Labels: t-feat

#1835 bug: Enforce protobuf oneof constraints
  .changeset/hip-cherries-pull.md
  packages/core/src/validations.test.ts
  packages/core/src/validations.ts
Labels: t-bug

#1833 feat(hubble): catchup sync with s3 snapshot
  .changeset/violet-peas-relax.md
  apps/hubble/docker-compose.yml
  apps/hubble/src/cli.ts
  apps/hubble/src/defaultConfig.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/merkleTrie.ts
  apps/hubble/src/network/sync/merkleTrieWorker.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/storage/db/rocksdb.ts
  apps/hubble/src/storage/stores/storageCache.ts
  apps/hubble/www/docs/docs/cli.md
Labels: t-feat

#1836 fix: ValidateOrRevoke an fid's messages every 14 days
  .changeset/spotty-radios-flash.md
  apps/hubble/src/storage/jobs/validateOrRevokeMessagesJob.test.ts
  apps/hubble/src/storage/jobs/validateOrRevokeMessagesJob.ts
Labels: t-feat

#1837 fix(hubble): path checking for num items
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/merkleTrie.ts
  apps/hubble/src/utils/snapshot.ts
Labels: t-bug

#1838 chore: release hubble 1.11.1
  .changeset/hip-cherries-pull.md
  .changeset/six-bats-grab.md
  .changeset/spotty-radios-flash.md
  .changeset/violet-peas-relax.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
Labels: t-chore

#1840 chore: release hubble 1.11.1
  .changeset/hip-cherries-pull.md
  .changeset/six-bats-grab.md
  .changeset/spotty-radios-flash.md
  .changeset/violet-peas-relax.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/hubble/src/network/sync/merkleTrie.ts
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
Labels: t-chore

#1841 chore: release hubble 1.11.2
  .github/workflows/ci.yml
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/hubble/pm2.config.cjs
Labels: t-chore

#1844 fix: handle edge cases of rocksdb instantiation
  .changeset/modern-planes-nail.md
  apps/hubble/src/addon/src/db/rocksdb.rs
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/merkleTrie.ts
Labels: t-bug

#1849 core: release(hubble): v1.11.3
  .changeset/modern-planes-nail.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
Labels: t-chore

#1851 fix(hubble): reduce hub bandwidth with floodsub toggle
  .changeset/flat-seahorses-pay.md
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/p2p/gossipNodeWorker.ts
  apps/hubble/src/rpc/server.ts
Labels: t-bug

#1852 chore(hubble): release 1.11.4
  .changeset/flat-seahorses-pay.md
  .changeset/nice-radios-mate.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
Labels: t-chore
