Repository farcasterxyz/hub-monorepo, pull requests merged in 2024-06, with the labels that each got.

#2022 fix(replicator): heap out of memory
  .changeset/tricky-sheep-sneeze.md
  apps/replicator/.env.sample
  apps/replicator/docker-compose.yml
Labels: t-bug

#2015 chore: fix typos and link broken
  apps/hubble/src/addon/src/store/cast_store.rs
  apps/hubble/src/addon/src/store/message.rs
  apps/hubble/src/addon/src/store/store_event_handler.rs
  apps/hubble/www/docs/tutorials/gcp.md
  packages/hub-nodejs/docs/signers/ViemLocalEip712Signer.md
Labels: t-docs

#2002 chore: Add missing message type
  packages/hub-nodejs/spec.yaml
Labels: t-docs

#2011 chore: fix typos
  apps/hubble/src/network/p2p/gossipNode.ts
  apps/hubble/src/network/sync/merkleTrie.ts
  apps/hubble/src/network/sync/syncEngine.ts
Labels: t-docs

#1971 fix(replicator): respect fnames_username_unique constraint
  .changeset/grumpy-spoons-pay.md
  apps/replicator/src/processors/usernameProof.ts
Labels: t-bug

#2024 fix: Report better error message when hub address unspecified
  .changeset/twelve-needles-beg.md
  packages/hub-nodejs/src/client.ts
  packages/hub-nodejs/src/index.test.ts
Labels: t-bug

#2026 feat(shuttle): add support for reverse reconciliation
  .changeset/beige-suns-poke.md
  packages/shuttle/src/example-app/app.ts
  packages/shuttle/src/shuttle/messageReconciliation.ts
Labels: t-feat

#2028 chore: Release 1.12.3
  .changeset/beige-suns-poke.md
  .changeset/cold-ducks-attack.md
  .changeset/four-baboons-wait.md
  .changeset/grumpy-spoons-pay.md
  .changeset/thirty-flies-sleep.md
  .changeset/tricky-sheep-sneeze.md
  .changeset/twelve-needles-beg.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/replicator/CHANGELOG.md
  apps/replicator/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2030 chore: Release hub-nodejs and core packages
  .changeset/good-singers-press.md
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
Labels: t-chore

#2034 [chore] Update TypeScript 5.0.2 to 5.4.5
  .changeset/two-ghosts-develop.md
  package.json
  packages/shuttle/src/utils.ts
  yarn.lock
Labels: t-chore

#2033 [chore] Add Node 22 to test matrix
  .changeset/chilled-starfishes-chew.md
  .github/workflows/ci.yml
  apps/hubble/src/hubble.ts
Labels: t-chore

#1948 feat: add docker heath checks to services
  Dockerfile.hubble
  apps/hubble/docker-compose.yml
Labels: t-feat

#2036 [chore] Remove old replicator
  .github/workflows/publish-replicator.yml
  Dockerfile.replicator
  apps/replicator/.env.sample
  apps/replicator/.gitignore
  apps/replicator/CHANGELOG.md
  apps/replicator/README.md
  apps/replicator/biome.json
  apps/replicator/docker-compose.yml
  apps/replicator/grafana/grafana-dashboard.json
  apps/replicator/grafana/grafana.ini
  apps/replicator/package.json
  apps/replicator/src/app.ts
  apps/replicator/src/db.ts
  apps/replicator/src/env.ts
  apps/replicator/src/error.ts
  apps/replicator/src/eventProcessor.ts
  apps/replicator/src/hub.ts
  apps/replicator/src/hubReplicator.ts
  apps/replicator/src/hubSubscriber.ts
  apps/replicator/src/jobs.ts
  apps/replicator/src/jobs/backfillFidCasts.ts
  apps/replicator/src/jobs/backfillFidData.ts
  apps/replicator/src/jobs/backfillFidLinks.ts
  apps/replicator/src/jobs/backfillFidOtherOnChainEvents.ts
  apps/replicator/src/jobs/backfillFidReactions.ts
  apps/replicator/src/jobs/backfillFidRegistration.ts
  apps/replicator/src/jobs/backfillFidStorageAllocations.ts
  apps/replicator/src/jobs/backfillFidUserData.ts
  apps/replicator/src/jobs/backfillFidUserNameProofs.ts
  apps/replicator/src/jobs/backfillFidVerifications.ts
  apps/replicator/src/jobs/mergeMessage.ts
  apps/replicator/src/jobs/processHubEvent.ts
  apps/replicator/src/log.ts
  apps/replicator/src/messageProcessor.ts
  apps/replicator/src/migrations/001_initial_migration.ts
  apps/replicator/src/processors/cast.ts
  apps/replicator/src/processors/index.ts
  apps/replicator/src/processors/link.ts
  apps/replicator/src/processors/onChainEvent.ts
  apps/replicator/src/processors/reaction.ts
  apps/replicator/src/processors/userData.ts
  apps/replicator/src/processors/usernameProof.ts
  apps/replicator/src/processors/verification.ts
  apps/replicator/src/redis.ts
  apps/replicator/src/sandboxedJob.ts
  apps/replicator/src/statsd.ts
  apps/replicator/src/util.ts
  apps/replicator/src/web.ts
  apps/replicator/src/worker.ts
  apps/replicator/tsconfig.json
  scripts/publish-replicator-image.sh
  scripts/replicator.sh
Labels: t-chore

#2037 [chore] Remove remaining Envoy references
  apps/hubble/envoy/README.md
  apps/hubble/envoy/envoy-start.sh
  apps/hubble/envoy/envoy.yaml
  apps/hubble/envoy/install-docker.sh
  scripts/hubble.sh
Labels: t-chore

#2038 feat: increase verification signature max length
  .changeset/olive-readers-suffer.md
  packages/core/src/validations.test.ts
  packages/core/src/validations.ts
Labels: t-feat

#2043 chore: Release 1.13
  .changeset/blue-snails-vanish.md
  .changeset/chilled-starfishes-chew.md
  .changeset/olive-readers-suffer.md
  .changeset/two-ghosts-develop.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/hubble/src/hubble.ts
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2045 feat: Implement longer casts FIP
  .changeset/weak-sloths-beg.md
  apps/hubble/src/storage/engine/messageDataBytes.test.ts
  apps/hubble/src/storage/stores/castStore.test.ts
  packages/core/src/protobufs/generated/message.ts
  packages/core/src/validations.test.ts
  packages/core/src/validations.ts
  packages/hub-nodejs/src/generated/message.ts
  packages/hub-web/src/generated/message.ts
  protobufs/schemas/message.proto
Labels: t-feat

#2047 chore: Release 1.13.1
  .changeset/weak-sloths-beg.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore

#2046 Docs improvements
  CONTRIBUTING.md
  apps/hubble/src/addon/README.md
  apps/hubble/src/addon/src/db/rocksdb.rs
  apps/hubble/src/addon/src/store/store.rs
  apps/hubble/src/addon/src/store/username_proof_store.rs
  apps/hubble/src/addon/src/store/utils.rs
  apps/hubble/src/addon/src/trie/trie_node.rs
  apps/hubble/src/console/warpcastTestCommand.ts
  apps/hubble/src/eth/l2EventsProvider.ts
  apps/hubble/src/eth/watchBlockNumber.ts
  apps/hubble/src/eth/watchContractEvent.ts
  apps/hubble/www/README.md
  apps/hubble/www/docs/docs/api.md
  apps/hubble/www/docs/docs/architecture.md
  apps/hubble/www/docs/docs/cli.md
  apps/hubble/www/docs/docs/httpapi/httpapi.md
  apps/hubble/www/docs/docs/httpapi/message.md
  apps/hubble/www/docs/docs/httpapi/userdata.md
  apps/hubble/www/docs/docs/httpapi/usernameproof.md
  apps/hubble/www/docs/docs/messages.md
  apps/hubble/www/docs/intro/monitoring.md
  apps/hubble/www/docs/tutorials/gcp.md
  scripts/hubble.sh
Labels: t-docs

#2048 feat(shuttle): Store cast type in message body
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
  packages/shuttle/src/shuttle/db.ts
  packages/shuttle/src/utils.ts
Labels: t-feat

#2050 fix(shuttle): Fix shuttle hub-nodejs version dep to support long casts
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-bug

#2058 fix: Always log when updating contact info
  .changeset/big-bulldogs-hunt.md
  apps/hubble/src/network/sync/syncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
Labels: t-bug

#2063 chore: Lower level of shuttle logs to debug
  .changeset/hungry-pillows-shout.md
  packages/shuttle/src/shuttle/messageReconciliation.ts
Labels: t-chore

#2065 fix: updated multinode docker compose
  docker-compose-multinode.yml
Labels: t-bug

#2064 chore: Update message.ts
  packages/hub-web/src/generated/message.ts
Labels: t-docs

#2066 docs: updated install and monitoring pages
  apps/hubble/www/docs/intro/install.md
  apps/hubble/www/docs/intro/monitoring.md
Labels: t-docs

#2068 feat: expose LinkCompactState messages via rpc
  .changeset/lazy-flies-rule.md
  apps/hubble/src/addon/src/db/rocksdb.rs
  apps/hubble/src/addon/src/lib.rs
  apps/hubble/src/addon/src/store/cast_store.rs
  apps/hubble/src/addon/src/store/link_store.rs
  apps/hubble/src/addon/src/store/reaction_store.rs
  apps/hubble/src/addon/src/store/store.rs
  apps/hubble/src/addon/src/store/user_data_store.rs
  apps/hubble/src/addon/src/store/username_proof_store.rs
  apps/hubble/src/addon/src/store/verification_store.rs
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rustfunctions.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/linkStore.ts
  apps/hubble/src/storage/stores/linkStoreCompactState.test.ts
  apps/hubble/www/docs/docs/api.md
  packages/core/src/protobufs/generated/message.ts
  packages/hub-nodejs/src/generated/message.ts
  packages/hub-nodejs/src/generated/rpc.ts
  packages/hub-web/src/generated/message.ts
  packages/hub-web/src/generated/rpc.ts
  packages/shuttle/src/shuttle/hubEventProcessor.ts
  protobufs/schemas/rpc.proto
Labels: t-feat

#2070 chore: Segment bundle delay stats by message status
  .changeset/eight-bags-fetch.md
  apps/hubble/src/hubble.ts
Labels: t-chore

#2074 feat: support compact state type for links in message reconciliation
  .changeset/proud-crabs-teach.md
  packages/shuttle/src/shuttle.integration.test.ts
  packages/shuttle/src/shuttle/messageReconciliation.ts
Labels: t-feat

#2075 fix: add patch to libp2p/peer-store to resolve broken peer id load failures
  .changeset/slow-dolphins-live.md
  Dockerfile.hubble
  apps/hubble/package.json
  package.json
  patches/@libp2p+peer-store+7.0.2.patch
  yarn.lock
Labels: t-bug

#2080 fix: Ensure patch files are included in Docker environment during build
  Dockerfile.hubble
Labels: t-bug

#2081 chore: Release 1.13.2
  .changeset/big-bulldogs-hunt.md
  .changeset/cold-shrimps-flow.md
  .changeset/eight-bags-fetch.md
  .changeset/hungry-pillows-shout.md
  .changeset/lazy-flies-rule.md
  .changeset/proud-crabs-teach.md
  .changeset/slow-dolphins-live.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  apps/hubble/src/console/console.ts
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2077 fix: return better error message
  .changeset/yellow-chefs-dance.md
  apps/hubble/src/addon/src/store/cast_store.rs
  apps/hubble/src/addon/src/store/message.rs
  apps/hubble/src/addon/src/store/store.rs
  apps/hubble/src/rpc/server.ts
Labels: t-bug

#2089 fix: Ensure we run `yarn postinstall` script for production build
  Dockerfile.hubble
Labels: t-bug

#2090 fix: Use stricter socket timeout for gossip
  .changeset/wicked-masks-study.md
  apps/hubble/src/network/p2p/gossipNodeWorker.ts
Labels: t-bug

#2091 chore: Release 1.13.3
  .changeset/honest-flies-jog.md
  .changeset/wicked-masks-study.md
  .changeset/yellow-chefs-dance.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
Labels: t-chore

#2103 fix: Fix gossip worker spending too much time iterating peer store
  .changeset/twelve-eggs-bathe.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/p2p/gossipNodeWorker.ts
Labels: t-bug

#2104 chore: Release 1.13.4
  .changeset/long-drinks-collect.md
  .changeset/twelve-eggs-bathe.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
Labels: t-chore

#2106 fix(shuttle): Bump max receive size to fix resource exhaustion error
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
  packages/shuttle/src/shuttle/hub.ts
Labels: t-bug

#2107 fix(shuttle): Use more efficient lookup to avoid errors
  .changeset/clever-roses-call.md
  packages/shuttle/package.json
  packages/shuttle/src/shuttle/db.ts
  packages/shuttle/src/shuttle/messageReconciliation.ts
  yarn.lock
Labels: t-bug

#2111 feat: add experimental HTTP APIs to control sync
  .changeset/tiny-kangaroos-refuse.md
  apps/hubble/src/rpc/httpServer.ts
  apps/hubble/src/rpc/test/httpServer.test.ts
  apps/hubble/www/docs/docs/httpapi/sync.md
Labels: t-feat

#2113 fix: contact info updates
  .changeset/cold-kids-compete.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/network/sync/syncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
Labels: t-bug

#2114 chore: release 1.13.5
  .changeset/cold-kids-compete.md
  .changeset/sweet-students-rule.md
  .changeset/tiny-kangaroos-refuse.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
Labels: t-chore
