Repository farcasterxyz/hub-monorepo, pull requests merged in 2024-04, with the labels that each got.

#1853 perf: Move merkle trie to Rust
  .changeset/healthy-dancers-hide.md
  .changeset/nice-radios-mate.md
  apps/hubble/src/addon/src/db/rocksdb.rs
  apps/hubble/src/addon/src/lib.rs
  apps/hubble/src/addon/src/store/cast_store.rs
  apps/hubble/src/addon/src/store/store.rs
  apps/hubble/src/addon/src/store/utils.rs
  apps/hubble/src/addon/src/trie/merkle_trie.rs
  apps/hubble/src/addon/src/trie/mod.rs
  apps/hubble/src/addon/src/trie/trie_node.rs
  apps/hubble/src/addon/src/trie/trie_node_tests.rs
  apps/hubble/src/network/p2p/gossipNode.test.ts
  apps/hubble/src/network/sync/merkleTrie.test.ts
  apps/hubble/src/network/sync/merkleTrie.ts
  apps/hubble/src/network/sync/merkleTrieWorker.ts
  apps/hubble/src/network/sync/multiPeerSyncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.test.ts
  apps/hubble/src/network/sync/syncEngine.ts
  apps/hubble/src/network/sync/syncEnginePerf.test.ts
  apps/hubble/src/network/sync/trieNode.test.ts
  apps/hubble/src/network/sync/trieNode.ts
  apps/hubble/src/rpc/test/bulkService.test.ts
  apps/hubble/src/rpc/test/castService.test.ts
  apps/hubble/src/rpc/test/concurrency.test.ts
  apps/hubble/src/rpc/test/httpServer.test.ts
  apps/hubble/src/rpc/test/linkService.test.ts
  apps/hubble/src/rpc/test/messageService.test.ts
  apps/hubble/src/rpc/test/reactionService.test.ts
  apps/hubble/src/rpc/test/rpcAuth.test.ts
  apps/hubble/src/rpc/test/server.test.ts
  apps/hubble/src/rpc/test/signerService.test.ts
  apps/hubble/src/rpc/test/syncService.test.ts
  apps/hubble/src/rpc/test/userDataService.test.ts
  apps/hubble/src/rpc/test/verificationService.test.ts
  apps/hubble/src/rustfunctions.ts
  apps/hubble/src/storage/db/migrations/5.fnameSyncIds.test.ts
  apps/hubble/src/storage/db/migrations/5.fnameSyncIds.ts
  apps/hubble/src/storage/db/migrations/6.oldContractEvents.test.ts
  apps/hubble/src/storage/db/migrations/6.oldContractEvents.ts
  apps/hubble/src/storage/db/migrations/7.clearAdminResets.test.ts
  apps/hubble/src/storage/db/migrations/7.clearAdminResets.ts
  apps/hubble/src/storage/db/migrations/migrations.test.ts
  apps/hubble/src/storage/db/rocksdb.ts
  apps/hubble/src/storage/jobs/validateOrRevokeMessagesJob.ts
  apps/hubble/src/storage/stores/linkStore.test.ts
  apps/hubble/src/test/bench/merkleTrie.ts
  apps/hubble/src/utils/crypto.ts
Labels: t-perf

#1858 fix: Online snapshot using rocksdb snapshot iterators
  .changeset/giant-bobcats-perform.md
  apps/hubble/src/addon/Cargo.lock
  apps/hubble/src/addon/Cargo.toml
  apps/hubble/src/addon/src/db/rocksdb.rs
  apps/hubble/src/addon/src/lib.rs
  apps/hubble/src/addon/src/store/store.rs
  apps/hubble/src/addon/src/trie/merkle_trie.rs
  apps/hubble/src/cli.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/rustfunctions.ts
  apps/hubble/src/storage/jobs/dbSnapshotBackupJob.ts
  apps/hubble/src/utils/snapshot.ts
Labels: t-bug

#1868 perf: Use countKeysAtPrefix for storage cache counts
  .changeset/eight-falcons-think.md
  apps/hubble/src/addon/src/db/rocksdb.rs
  apps/hubble/src/addon/src/lib.rs
  apps/hubble/src/rustfunctions.ts
  apps/hubble/src/storage/db/rocksdb.ts
  apps/hubble/src/storage/stores/storageCache.ts
Labels: t-perf

#1873 Initial version of hub-shuttle
  .changeset/neat-kings-clap.md
  .github/workflows/ci.yml
  packages/hub-shuttle/CHANGELOG.md
  packages/hub-shuttle/README.md
  packages/hub-shuttle/architecture.jpg
  packages/hub-shuttle/biome.json
  packages/hub-shuttle/docker-compose.yml
  packages/hub-shuttle/jest.config.ts
  packages/hub-shuttle/package.json
  packages/hub-shuttle/src/app/app.ts
  packages/hub-shuttle/src/app/env.ts
  packages/hub-shuttle/src/app/migration.ts
  packages/hub-shuttle/src/app/migrations/001_initial_migration.ts
  packages/hub-shuttle/src/index.ts
  packages/hub-shuttle/src/log.ts
  packages/hub-shuttle/src/shuttle.integration.test.ts
  packages/hub-shuttle/src/shuttle/db.ts
  packages/hub-shuttle/src/shuttle/hub.ts
  packages/hub-shuttle/src/shuttle/hubEventProcessor.ts
  packages/hub-shuttle/src/shuttle/hubSubscriber.ts
  packages/hub-shuttle/src/shuttle/interfaces.ts
  packages/hub-shuttle/src/shuttle/messageProcessor.ts
  packages/hub-shuttle/src/shuttle/messageReconciliation.ts
  packages/hub-shuttle/src/shuttle/redis.ts
  packages/hub-shuttle/src/utils.ts
  packages/hub-shuttle/tsconfig.json
  packages/hub-shuttle/tsup.config.ts
  yarn.lock
Labels: t-feat

#1874 chore: release hub-shuttle
  .changeset/neat-kings-clap.md
  packages/hub-shuttle/CHANGELOG.md
  packages/hub-shuttle/package.json
Labels: t-chore

#1875 fix: Update hub-shuttle exports
  packages/hub-shuttle/CHANGELOG.md
  packages/hub-shuttle/package.json
  packages/hub-shuttle/src/index.ts
Labels: t-bug

#1881 perf: LRU cache for activeSigner and IdRegistry
  .changeset/sour-yaks-protect.md
  apps/hubble/src/rpc/test/messageService.test.ts
  apps/hubble/src/rpc/test/signerService.test.ts
  apps/hubble/src/storage/db/migrations/3.clearEvents.test.ts
  apps/hubble/src/storage/engine/index.test.ts
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/stores/onChainEventStore.ts
  apps/hubble/src/utils/lruCache.test.ts
  apps/hubble/src/utils/lruCache.ts
Labels: t-perf

#1880 perf: Support multiple validation workers
  .changeset/gold-beds-search.md
  apps/hubble/src/storage/engine/index.ts
  apps/hubble/src/storage/engine/validation.worker.ts
  apps/hubble/src/storage/jobs/validateOrRevokeMessagesJob.ts
Labels: t-perf

#1882 perf: Use threadpool for grpc queries
  .changeset/silly-readers-accept.md
  apps/hubble/src/addon/src/store/cast_store.rs
  apps/hubble/src/addon/src/store/link_store.rs
  apps/hubble/src/addon/src/store/reaction_store.rs
  apps/hubble/src/addon/src/store/utils.rs
Labels: t-perf

#1869 feat: Opt Out Hub Diagnostics
  .changeset/heavy-queens-impress.md
  apps/hubble/docker-compose.yml
  apps/hubble/src/cli.ts
  apps/hubble/src/defaultConfig.ts
  apps/hubble/src/eth/l2EventsProvider.ts
  apps/hubble/src/eth/watchContractEvent.ts
  apps/hubble/src/hubble.ts
  apps/hubble/src/test/utils.ts
  apps/hubble/src/utils/diagnosticReport.ts
  apps/hubble/src/utils/diagnosticReportWorker.ts
  apps/hubble/src/utils/startupCheck.ts
  apps/hubble/www/docs/docs/cli.md
Labels: t-feat

#1887 feat(shuttle): Refactor message reconciliation to use function
  packages/hub-shuttle/CHANGELOG.md
  packages/hub-shuttle/package.json
  packages/hub-shuttle/src/app/app.ts
  packages/hub-shuttle/src/app/migration.ts
  packages/hub-shuttle/src/shuttle.integration.test.ts
  packages/hub-shuttle/src/shuttle/db.ts
  packages/hub-shuttle/src/shuttle/messageReconciliation.ts
Labels: t-chore

#1892 fix(shuttle): fix interfaces export
  packages/hub-shuttle/CHANGELOG.md
  packages/hub-shuttle/package.json
  packages/hub-shuttle/src/shuttle/hubEventProcessor.ts
  packages/hub-shuttle/src/shuttle/interfaces.ts
  packages/hub-shuttle/src/shuttle/messageProcessor.ts
  packages/hub-shuttle/src/utils.ts
Labels: t-bug

#1895 chore: update catchup sync with snapshot default to true
  .changeset/swift-eggs-sparkle.md
  apps/hubble/src/cli.ts
  apps/hubble/src/defaultConfig.ts
Labels: t-chore

#1896 perf: Use threadpool for getMany
  .changeset/proud-feet-draw.md
  apps/hubble/src/addon/src/db/rocksdb.rs
Labels: t-perf

#1899 tests: Cleanup after tests
  .changeset/purple-buses-invent.md
  apps/hubble/src/addon/src/db/rocksdb.rs
  apps/hubble/src/test/e2e/hubbleNetwork.test.ts
  apps/hubble/src/test/e2e/hubbleStartup.test.ts
Labels: t-chore

#1903 feat(shuttle): Read and write events from redis streams and add reconciliation workers
  .changeset/hip-hornets-promise.md
  packages/hub-shuttle/README.md
  packages/hub-shuttle/package.json
  packages/hub-shuttle/src/app.ts
  packages/hub-shuttle/src/example-app/app.ts
  packages/hub-shuttle/src/example-app/env.ts
  packages/hub-shuttle/src/example-app/package.json
  packages/hub-shuttle/src/example-app/worker.ts
  packages/hub-shuttle/src/example-app/yarn.lock
  packages/hub-shuttle/src/shuttle.integration.test.ts
  packages/hub-shuttle/src/shuttle/eventStream.ts
  packages/hub-shuttle/src/shuttle/hub.ts
  packages/hub-shuttle/src/shuttle/hubEventProcessor.ts
  packages/hub-shuttle/src/shuttle/hubSubscriber.ts
  packages/hub-shuttle/src/shuttle/index.ts
  packages/hub-shuttle/src/shuttle/redis.ts
  packages/hub-shuttle/src/statsd.ts
  packages/hub-shuttle/src/utils.ts
  yarn.lock
Labels: t-feat

#1906 fix: Restrict yarn snapshot-url to mainnet
  .changeset/big-ants-drive.md
  apps/hubble/src/cli.ts
Labels: t-bug

#1910 fix: update diagnostics reports to prefix tags with fid and peer_id
  .changeset/large-bobcats-destroy.md
  apps/hubble/src/utils/diagnosticReportWorker.ts
Labels: t-bug

#1914 feat(shuttle): support prune, revokes and deletes
  packages/hub-shuttle/CHANGELOG.md
  packages/hub-shuttle/package.json
  packages/hub-shuttle/src/example-app/app.ts
  packages/hub-shuttle/src/shuttle.integration.test.ts
  packages/hub-shuttle/src/shuttle/eventStream.ts
  packages/hub-shuttle/src/shuttle/hubEventProcessor.ts
  packages/hub-shuttle/src/shuttle/hubSubscriber.ts
  packages/hub-shuttle/src/shuttle/index.ts
Labels: t-feat

#1915 chore(shuttle): Rename package to shuttle and release beta
  .changeset/hip-hornets-promise.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/README.md
  packages/shuttle/architecture.jpg
  packages/shuttle/biome.json
  packages/shuttle/docker-compose.yml
  packages/shuttle/jest.config.ts
  packages/shuttle/package.json
  packages/shuttle/src/app.ts
  packages/shuttle/src/example-app/app.ts
  packages/shuttle/src/example-app/env.ts
  packages/shuttle/src/example-app/log.ts
  packages/shuttle/src/example-app/migration.ts
  packages/shuttle/src/example-app/migrations/001_initial_migration.ts
  packages/shuttle/src/example-app/package.json
  packages/shuttle/src/example-app/tsconfig.json
  packages/shuttle/src/example-app/worker.ts
  packages/shuttle/src/index.ts
  packages/shuttle/src/log.ts
  packages/shuttle/src/shuttle.integration.test.ts
  packages/shuttle/src/shuttle/db.ts
  packages/shuttle/src/shuttle/eventStream.ts
  packages/shuttle/src/shuttle/hub.ts
  packages/shuttle/src/shuttle/hubEventProcessor.ts
  packages/shuttle/src/shuttle/hubSubscriber.ts
  packages/shuttle/src/shuttle/index.ts
  packages/shuttle/src/shuttle/messageProcessor.ts
  packages/shuttle/src/shuttle/messageReconciliation.ts
  packages/shuttle/src/shuttle/redis.ts
  packages/shuttle/src/statsd.ts
  packages/shuttle/src/utils.ts
  packages/shuttle/tsconfig.json
  packages/shuttle/tsup.config.ts
Labels: t-chore

#1921 feat(shuttle): Make event stream more customizable
  packages/shuttle/CHANGELOG.md
  packages/shuttle/README.md
  packages/shuttle/package.json
  packages/shuttle/src/shuttle/eventStream.ts
Labels: t-chore

#1923 fix(shuttle): ack the correct group name to fix stale bug
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
  packages/shuttle/src/shuttle/eventStream.ts
Labels: t-bug

#1926 feat(shuttle): add message state to handler
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
  packages/shuttle/src/example-app/app.ts
  packages/shuttle/src/example-app/db.ts
  packages/shuttle/src/example-app/migrations/002_casts.ts
  packages/shuttle/src/shuttle.integration.test.ts
  packages/shuttle/src/shuttle/hubEventProcessor.ts
  packages/shuttle/src/shuttle/index.ts
Labels: t-feat

#1940 fix(hubble): check reachable gRPC for hubs
  .changeset/silly-bobcats-yell.md
  apps/hubble/src/hubble.ts
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/server.test.ts
  apps/hubble/src/utils/p2p.ts
Labels: t-bug

#1944 fix: Add `ps` to Hubble image
  Dockerfile.hubble
Labels: t-bug

#1931 fix: increase shuttle hub client timeout limit
  .changeset/plenty-badgers-boil.md
  packages/shuttle/src/shuttle/hubSubscriber.ts
Labels: t-bug

#1949 feat(shuttle): add fid sharding to shuttle
  .changeset/wild-llamas-work.md
  packages/shuttle/package.json
  packages/shuttle/src/example-app/app.ts
  packages/shuttle/src/example-app/env.ts
  packages/shuttle/src/index.ts
  packages/shuttle/src/shuttle/hubSubscriber.ts
Labels: t-feat

#1951 fix: sharding events should work when requesting historical events
  .changeset/giant-monkeys-walk.md
  apps/hubble/src/rpc/server.ts
  apps/hubble/src/rpc/test/eventService.test.ts
Labels: t-bug

#1954 fix(shuttle): Preserve redis subscriber backwards compatibility
  .changeset/thin-poems-unite.md
  packages/shuttle/src/shuttle/hubSubscriber.ts
  packages/shuttle/src/shuttle/redis.ts
Labels: t-bug

#1955 fix(shuttle): Fix fromId being undefined
  packages/shuttle/src/shuttle/hubSubscriber.ts
Labels: t-bug

#1953 chore: Buffer statsd calls before sending datagram(s) over socket
  .changeset/quick-stingrays-bathe.md
  packages/shuttle/src/statsd.ts
Labels: t-chore

#1956 chore: Release shuttle 0.2.4
  .changeset/plenty-badgers-boil.md
  .changeset/quick-stingrays-bathe.md
  .changeset/thin-poems-unite.md
  .changeset/wild-llamas-work.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#1957 fix: Validate merge messages only when storing messages
  .changeset/gorgeous-lions-refuse.md
  packages/shuttle/src/shuttle/messageProcessor.ts
Labels: t-bug

#1958 chore: Release Shuttle 0.2.5
  .changeset/gorgeous-lions-refuse.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#1959 chore: Switch to custom hot-shots package
  .changeset/gold-snails-bow.md
  packages/shuttle/package.json
  yarn.lock
Labels: t-chore

#1960 chore: Skip DNS lookups for IP addresses in statsd module
  .changeset/long-onions-lick.md
  packages/shuttle/src/statsd.ts
Labels: t-chore

#1961 chore: Release Shuttle 0.2.6
  .changeset/gold-snails-bow.md
  .changeset/long-onions-lick.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#1966 feat: Allow skipping validation when processing event stream
  .changeset/flat-eels-repeat.md
  packages/shuttle/src/shuttle/messageProcessor.ts
Labels: t-feat

#1968 chore: Release Shuttle 0.2.7
  .changeset/flat-eels-repeat.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#1967 feat: extend verification signature length
  .changeset/neat-bikes-live.md
  packages/core/src/validations.test.ts
  packages/core/src/validations.ts
Labels: t-feat

#1842 chore: set repository urls for npm
  packages/core/package.json
  packages/hub-nodejs/package.json
  packages/hub-web/package.json
Labels: t-chore
