Repository farcasterxyz/hub-monorepo, pull requests merged in 2025-04, with the labels that each got.

#2560 feat: Update builders and examples for snapchain
  .changeset/breezy-birds-jam.md
  packages/core/src/builders.ts
  packages/core/src/validations.ts
  packages/hub-nodejs/examples/chron-feed/index.ts
  packages/hub-nodejs/examples/hello-world/index.ts
  packages/hub-nodejs/examples/write-data/index.ts
Labels: t-feat

#2562 chore: Release snapchain patches
  .changeset/breezy-birds-jam.md
  .changeset/kind-parrots-hear.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/examples/chron-feed/package.json
  packages/hub-nodejs/examples/contract-signatures/package.json
  packages/hub-nodejs/examples/hello-world/package.json
  packages/hub-nodejs/examples/write-data/package.json
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2567 fix: Ensure snapchain error codes are passed through
  .changeset/nasty-eagles-grin.md
  packages/hub-nodejs/src/client.ts
Labels: t-bug

#2568 chore: Release hub-nodejs 0.13.1
  .changeset/nasty-eagles-grin.md
  apps/hubble/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
Labels: t-chore

#2572 fix: support removals for social usernames, already supported upstream
  .changeset/early-pumas-prove.md
  apps/hubble/src/utils/versions.test.ts
  packages/core/src/validations.ts
Labels: t-bug

#2573 chore: release 0.16.1
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
Labels: t-chore

#2574 chore: Extend hubble expiry by a few weeks
  .changeset/witty-kangaroos-sell.md
  apps/hubble/src/hubble.ts
Labels: t-chore

#2575 chore: Release 1.19.3
  .changeset/early-pumas-prove.md
  .changeset/witty-kangaroos-sell.md
  apps/hubble/CHANGELOG.md
  apps/hubble/package.json
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
Labels: t-chore

#2576 feat: More Snapchain updates
  .changeset/heavy-roses-confess.md
  .changeset/mighty-queens-sip.md
  apps/hubble/src/addon/src/store/store.rs
  apps/hubble/src/addon/src/store/user_data_store.rs
  apps/hubble/src/addon/src/store/username_proof_store.rs
  apps/hubble/src/storage/stores/storeEventHandler.ts
  packages/core/src/builders.ts
  packages/core/src/protobufs/generated/hub_event.ts
  packages/core/src/protobufs/typeguards.ts
  packages/hub-nodejs/src/generated/hub_event.ts
  packages/hub-web/src/generated/hub_event.ts
  packages/hub-web/src/generated/message.ts
  packages/shuttle/src/example-app/app.ts
  protobufs/schemas/hub_event.proto
Labels: t-feat

#2577 chore: Release hub-nodejs
  .changeset/heavy-roses-confess.md
  .changeset/mighty-queens-sip.md
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore
