Repository farcasterxyz/hub-monorepo, pull requests merged in 2025-06, with the labels that each got.

#2595 fix: update generated files and fix validations
  .changeset/thick-radios-end.md
  packages/core/src/validations.test.ts
  packages/core/src/validations.ts
  packages/hub-nodejs/src/generated/message.ts
  packages/hub-nodejs/src/generated/onchain_event.ts
  packages/hub-nodejs/src/generated/request_response.ts
  packages/hub-nodejs/src/generated/username_proof.ts
  packages/hub-web/src/generated/message.ts
  packages/hub-web/src/generated/onchain_event.ts
  packages/hub-web/src/generated/request_response.ts
  packages/hub-web/src/generated/username_proof.ts
Labels: t-bug

#2596 chore: Release client libs for snapchain 0.3
  .changeset/thick-radios-end.md
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2602 fix: shuttle should respect validate messages flag everywhere
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
  packages/shuttle/src/shuttle/hubEventProcessor.ts
Labels: t-bug

#2603 chore: switch to generating client libraries off snapchain protos
  .changeset/plenty-penguins-laugh.md
  .changeset/shiny-tables-clap.md
  generate-protos.sh
  packages/core/package.json
  packages/core/src/protobufs/generated/admin_rpc.ts
  packages/core/src/protobufs/generated/blocks.ts
  packages/core/src/protobufs/generated/gossip.ts
  packages/core/src/protobufs/generated/hub_event.ts
  packages/core/src/protobufs/generated/message.ts
  packages/core/src/protobufs/generated/node_state.ts
  packages/core/src/protobufs/generated/request_response.ts
  packages/core/src/protobufs/generated/sync_trie.ts
  packages/core/src/protobufs/typeguards.ts
  packages/core/src/protobufs/types.ts
  packages/hub-nodejs/package.json
  packages/hub-nodejs/src/client.ts
  packages/hub-nodejs/src/generated/admin_rpc.ts
  packages/hub-nodejs/src/generated/blocks.ts
  packages/hub-nodejs/src/generated/hub_event.ts
  packages/hub-nodejs/src/generated/message.ts
  packages/hub-nodejs/src/generated/request_response.ts
  packages/hub-nodejs/src/generated/rpc.ts
  packages/hub-web/package.json
  packages/hub-web/src/client.ts
  packages/hub-web/src/generated/admin_rpc.ts
  packages/hub-web/src/generated/blocks.ts
  packages/hub-web/src/generated/hub_event.ts
  packages/hub-web/src/generated/message.ts
  packages/hub-web/src/generated/request_response.ts
  packages/hub-web/src/generated/rpc.ts
  packages/shuttle/src/shuttle/messageReconciliation.ts
  protobufs/README.md
  protobufs/schemas/gossip.proto
  protobufs/schemas/hub_event.proto
  protobufs/schemas/hub_state.proto
  protobufs/schemas/job.proto
  protobufs/schemas/message.proto
  protobufs/schemas/onchain_event.proto
  protobufs/schemas/request_response.proto
  protobufs/schemas/rpc.proto
  protobufs/schemas/sync_trie.proto
  protobufs/schemas/username_proof.proto
Labels: t-chore

#2605 chore: release new packages
  .changeset/plenty-penguins-laugh.md
  .changeset/shiny-tables-clap.md
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2607 feat: set up monitoring for event stream based on snapchain block numbers
  .changeset/witty-items-punch.md
  generate-protos.sh
  packages/core/src/protobufs/generated/hub_event.ts
  packages/core/src/protobufs/types.ts
  packages/hub-nodejs/src/generated/hub_event.ts
  packages/hub-web/src/generated/hub_event.ts
  packages/shuttle/src/shuttle/eventStream.ts
Labels: t-feat

#2608 fix: track event stream stats by host
  .changeset/gold-glasses-brake.md
  packages/shuttle/src/shuttle/eventStream.ts
Labels: t-bug

#2610 fix: add custom redis key prefix for monitoring
  .changeset/spicy-chairs-judge.md
  packages/shuttle/src/shuttle/eventStream.ts
Labels: t-bug

#2611 chore: release new shuttle version
  .changeset/spicy-chairs-judge.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2612 fix: only maintain counts for expected events in event stream monitoring
  .changeset/strong-horses-melt.md
  packages/shuttle/src/shuttle/eventStream.ts
Labels: t-bug

#2613 chore: release new shuttle version
  .changeset/strong-horses-melt.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2614 fix: use shard id from event in stream monitoring
  .changeset/giant-masks-deny.md
  packages/shuttle/src/shuttle/eventStream.ts
Labels: t-bug

#2615 chore: release new shuttle version
  .changeset/giant-masks-deny.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2616 feat: process events from stream in order
  .changeset/polite-eyes-protect.md
  packages/shuttle/src/shuttle/eventStream.ts
Labels: t-feat

#2618 Revert "feat: process events from stream in order (#2616)"
  .changeset/fast-suits-knock.md
  packages/shuttle/src/shuttle/eventStream.ts
Labels: t-chore

#2619 chore: release new shuttle version
  .changeset/fast-suits-knock.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2620 chore: add logging for event stream monitor
  .changeset/calm-hornets-confess.md
  packages/shuttle/src/shuttle/eventStream.ts
Labels: t-chore

#2621 chore: release new shuttle version
  .changeset/calm-hornets-confess.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore
