Repository farcasterxyz/hub-monorepo, pull requests merged in 2025-07, with the labels that each got.

#2622 feat: Add console example and bump protos
  .changeset/lemon-tools-draw.md
  generate-protos.sh
  packages/core/src/protobufs/generated/admin_rpc.ts
  packages/hub-nodejs/examples/console/adminCommand.ts
  packages/hub-nodejs/examples/console/console.ts
  packages/hub-nodejs/examples/console/package.json
  packages/hub-nodejs/examples/console/protobufCommand.ts
  packages/hub-nodejs/examples/console/rpcClientCommand.ts
  packages/hub-nodejs/examples/console/trackHubDelayCommand.ts
  packages/hub-nodejs/src/generated/admin_rpc.ts
  packages/hub-web/src/generated/admin_rpc.ts
Labels: t-feat

#2623 fix: make shard id required for the hub subscriber
  .changeset/spotty-icons-move.md
  packages/shuttle/src/shuttle/hubSubscriber.ts
Labels: t-bug

#2624 chore: release new packages
  .changeset/lemon-tools-draw.md
  .changeset/spotty-icons-move.md
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/package.json
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2625 feat: Update protos to support new storage unit type in snapchain v0.4.0
  generate-protos.sh
  packages/core/CHANGELOG.md
  packages/core/package.json
  packages/core/src/protobufs/generated/request_response.ts
  packages/hub-nodejs/CHANGELOG.md
  packages/hub-nodejs/examples/console/pnpm-lock.yaml
  packages/hub-nodejs/examples/console/pnpm-workspace.yaml
  packages/hub-nodejs/package.json
  packages/hub-nodejs/src/generated/request_response.ts
  packages/hub-web/CHANGELOG.md
  packages/hub-web/package.json
  packages/hub-web/src/generated/request_response.ts
Labels: t-feat

#2630 chore: release new shuttle version
  .changeset/young-jobs-flash.md
  packages/shuttle/CHANGELOG.md
  packages/shuttle/package.json
Labels: t-chore

#2634 fix: update dataBytes length check for 10k casts
  .changeset/late-geckos-move.md
  packages/core/src/validations.test.ts
  packages/core/src/validations.ts
Labels: t-bug
